add benchmark which compares radix to std::map
pmem/libpmemobj-cpp pull request #1038
Opened 2021-02-15 14:19 UTC by JanDorniak99

2021-02-15 15:38 UTC, igchor requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 96 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaHomX8n0zI8Q-_rCP:-MTaHomX8n0zI8Q-_rCQ:bz4ap1q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L96)):*
> ```cpp
> template <size_t batch_size>
> void
> insert_elements_kv(std::function<void(size_t)> insert_f)
> ```

A slighly faster approach would be to just pass a generic function type (F&& f) - the same way measure works. This allows for better optimizations.
___
*[benchmarks/radix/radix_tree.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaJFYK9BiKVJRWDxkE:-MTaJFYK9BiKVJRWDxkF:b-a05vf7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L109)):*
> ```cpp
> 			measure<std::chrono::nanoseconds>([&] { insert_f(j); });
> 
> 		insert_std_map_time += measure<std::chrono::nanoseconds>([&] {
> ```

Hm, instead of inserting to those maps in a single loop maybe we could just removeing this code for mymap from here and just run insert_elements_kv for the second time with different insert_f function? (the one which would insert to mymap?)
___
*[benchmarks/radix/radix_tree.cpp, line 139 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaI9zk7p2GECr6WkwT:-MTaI9zk7p2GECr6WkwU:bwbj2v6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L139)):*
> ```cpp
> 			r->kv->find(key);
> 	});
> 	std::cout << "Average access time (persistent radix tree): "
> ```

You could probably say it's in nanoseconds.
___
*[benchmarks/radix/radix_tree.cpp, line 191 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaIeBv5X_c0Ks7uqAz:-MTaIP8Q5bccegUT5wgr:bjlaxv4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L191)):*
> ```cpp
> 	auto radix_time = measure<std::chrono::nanoseconds>([&] {
> 		for (auto it = r->kv->begin(); it != r->kv->end();) {
> 			auto tmp_it = it++;
> ```

There's no need for tmp_it. You can just do it = r->kv->erase(it); without any increment operation.


<!-- Sent from Reviewable.io -->

2021-02-16 12:04 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[benchmarks/radix/radix_tree.cpp, line 96 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaHomX8n0zI8Q-_rCP:-MTee2ejD_uC0lUKhZdf:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L96)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

A slighly faster approach would be to just pass a generic function type (F&& f) - the same way measure works. This allows for better optimizations.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 109 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaJFYK9BiKVJRWDxkE:-MTeg09iAIZVypVwtZDu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, instead of inserting to those maps in a single loop maybe we could just removeing this code for mymap from here and just run insert_elements_kv for the second time with different insert_f function? (the one which would insert to mymap?)
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 139 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaI9zk7p2GECr6WkwT:-MTehRSw-2BL_nhQatro:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L139)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You could probably say it's in nanoseconds.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 191 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaIeBv5X_c0Ks7uqAz:-MTehwWJD3dAMACPZUp4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L191)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There's no need for tmp_it. You can just do it = r->kv->erase(it); without any increment operation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 15:07 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 191 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTaIeBv5X_c0Ks7uqAz:-MTkWt0b7or18UYZlyaW:b-y917qy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8c807fb4674a239a311c274a5e6c7b753db0e6c0/benchmarks/radix/radix_tree.cpp#L191)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually this code might not be correct, the erased iterator is possibly invalidated so you should not increment it. I think it's safer to do as I suggest.


<!-- Sent from Reviewable.io -->

2021-02-18 16:55 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 22 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq25up3i8iehvRFzQ4:-MTq25up3i8iehvRFzQ5:b9gcelq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L22)):*
> ```cpp
> struct data {
> 	unsigned long index;
> 	unsigned long data_1, data_2;
> ```

fields data_1 and data_2 are not used
___
*[benchmarks/radix/radix_tree.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpqisn6bFalOJKwGI3:-MTpqiso4ezI1kSPDo8k:bdi8xsm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L55)):*
> ```cpp
>  * be only even keys) */
> void
> gen_ne_keys(void)
> ```

generate_nonexisting_keys() and change all naming to be more human readabl, "ne" means nothing.
___
*[benchmarks/radix/radix_tree.cpp, line 61 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpzdJs6A6vkpG9TFrb:-MTpzdJs6A6vkpG9TFrc:b-ym1uka) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L61)):*
> ```cpp
> 
> 	for (size_t i = 0; i < (count / sample_size); ++i) {
> 		key = static_cast<unsigned long>(rand());
> ```

every unsigned long/unsigned should be changed to size_t
___
*[benchmarks/radix/radix_tree.cpp, line 65 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTptO6W3GV7enivyZTB:-MTptO6W3GV7enivyZTC:bxkhf0b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L65)):*
> ```
> } while ((key1 & 0x1) == 0);
> ```
} while (key1 % 2 == 1);

Also you can change your line:
key1 = static_cast<unsigned>(rand());
into something like following and remove do-while loop:
key1 = static_cast<unsigned>(rand() | 1 << 0);
or
key1 = static_cast<unsigned>(rand());
key1 |= 1 << 0;
___
*[benchmarks/radix/radix_tree.cpp, line 66 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvyeb65zgBS8xVZm0:-MTpvyeb65zgBS8xVZm1:b-y04als) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L66)):*
> ```cpp
> 			key1 = static_cast<unsigned>(rand());
> 		} while ((key1 & 0x1) == 0);
> 		key = key | key1;
> ```

key |= key1;
___
*[benchmarks/radix/radix_tree.cpp, line 83 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvhh_-_fHhzkga2o2:-MTpvhh_-_fHhzkga2o3:b-i6sstz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L83)):*
> ```cpp
> 		do {
> 			key1 = static_cast<unsigned>(rand());
> 		} while ((key1 & 0x1));
> ```

same as above:
key1 |= 1 << 0;
or
rand() | 1 << 0
___
*[benchmarks/radix/radix_tree.cpp, line 84 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvvm_Awnsz8bbF64I:-MTpvvm_Awnsz8bbF64J:b-y04als) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L84)):*
> ```cpp
> 			key1 = static_cast<unsigned>(rand());
> 		} while ((key1 & 0x1));
> 		key = key | key1;
> ```

key |= key1;
___
*[benchmarks/radix/radix_tree.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpwD5J4z2lagnfEdP1:-MTpwD5J4z2lagnfEdP2:ba5vhfz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L103)):*
> ```cpp
> 	std::cout << "Inserting " << count << " elements..." << std::endl;
> 
> 	for (size_t j = 0; j < count; j += batch_size)
> ```

few times above was 'i' instead of 'j' in loops.
___
*[benchmarks/radix/radix_tree.cpp, line 198 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpyWIx4RGqDIaZHjQ7:-MTpyWIy3ordFJsFAe0U:bczw25e) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L198)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	std::cout << "Average remove time (map): "
> 		  << static_cast<unsigned long>(std_map_time) /
> 			keys_to_insert.size()
> 		  << "ns" << std::endl;
> ```
</details>


Code multiplication, change it to:
```
print_time_per_element("Average remove time (map)", std_map_time, keys_to_insert.size());
```

Function can look like this:
```
void print_time_per_element(string msg, unsigned long total_time, size_t num_of_elements) {
    std::cout << msg + ": " 
        << static_cast<unsigned long>(std_map_time) / keys_to_insert.size()
        << "ns" << std::endl;
}
```
___
*[benchmarks/radix/radix_tree.cpp, line 235 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq0lXHC4Bs61ntLznu:-MTq0lXI4siYt3P2oaRb:bbga1fn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L235)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		std::cerr << e.what() << std::endl;
> 		std::cerr
> 			<< "To create pool run: pmempool create obj --layout=radix -s 1G path_to_pool"
> 			<< std::endl;
> ```
</details>


```
std::cerr << e.what() << std::endl
    << "To create pool run: pmempool create obj --layout=radix -s 1G path_to_pool"
    << std::endl;
```
___
*[benchmarks/radix/radix_tree.cpp, line 252 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq2BQS4hsav1297qo_:-MTq2BQS4hsav1297qoa:b-sfsaqo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L252)):*
> ```cpp
> 					for (size_t i = start;
> 					     i < start + batch_size; ++i) {
> 						value_type value;
> ```

Use this if you want to initialize fields.
```
value_type value = { i };
```
___
*[benchmarks/radix/radix_tree.cpp, line 276 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq1_QO6vbY1llCBZF8:-MTq1_QO6vbY1llCBZF9:bh3o6fy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L276)):*
> ```cpp
> 
> 		lookup_elements_kv(pop);
> ```

remove empty line
___
*[benchmarks/radix/radix_tree.cpp, line 278 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq1afB-9XPvZlaDyDy:-MTq1afB-9XPvZlaDyDz:bh3o6fy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L278)):*
> ```cpp
> 
> 		lookup_ne_elements_kv(pop);
> ```

remove empty line
___
*[benchmarks/radix/radix_tree.cpp, line 284 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq2spoDGjk1CTBKjp4:-MTq2spoDGjk1CTBKjp5:behydlz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L284)):*
> ```cpp
> 	} catch (const std::logic_error &e) {
> 		std::cerr << e.what() << std::endl;
> 	}
> ```

Is the complete list of exceptions? 
```
catch (...) {
   std::cerr << "Unexpected exception" << std::endl;
}
```


<!-- Sent from Reviewable.io -->

2021-02-19 11:05 UTC, igchor requested changes
Let's wait with merging this for now

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-:-MTtr6Xe1jnsLgn79DsT:b-nj7agb)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor and @JanDorniak99)



<!-- Sent from Reviewable.io -->

2021-02-22 10:30 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8DtasApRWvG2yDwe9:-MU8DtasApRWvG2yDweA:b9mah57) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L33)):*
> ```cpp
> };
> 
> static std::vector<unsigned long> keys_to_insert;
> ```

It would be better to not hold those vectors in global scope, as it's hard to do major changes on such code later. 
___
*[benchmarks/radix/radix_tree.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8EE414ALCYphX5KXA:-MU8EE414ALCYphX5KXB:b-vq8cyp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L55)):*
> ```cpp
>  * be only even keys) */
> void
> gen_ne_keys(void)
> ```

This function may retrun vecor<size_t>, and get count and size as parameters. 
___
*[benchmarks/radix/radix_tree.cpp, line 72 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8FlctEdrU3NGDIFtf:-MU8FlctEdrU3NGDIFtg:bfq1kg7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L72)):*
> ```cpp
> 
> void
> gen_keys()
> ```

this function may just return vector keys_to_insert, and than you may iterate over returned vector with sample_rate to construct keys_to_lookup. 
Or just iterate over keys_to_insert with sample_rate in lookup_elements functions.


<!-- Sent from Reviewable.io -->

2021-02-23 11:14 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[benchmarks/radix/radix_tree.cpp, line 65 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTptO6W3GV7enivyZTB:-MUDaAzh5TL2mEDP1OTu:brkzj7l) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L65)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> } while ((key1 & 0x1) == 0);
> ```
} while (key1 % 2 == 1);

Also you can change your line:
key1 = static_cast<unsigned>(rand());
into something like following and remove do-while loop:
key1 = static_cast<unsigned>(rand() | 1 << 0);
or
key1 = static_cast<unsigned>(rand());
key1 |= 1 << 0;
</blockquote></details>

```
key1 |= 0x1 
```
would be cleaner


<!-- Sent from Reviewable.io -->

2021-02-23 15:35 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor, @JanDorniak99, and @karczex)

___
*[benchmarks/radix/radix_tree.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8DtasApRWvG2yDwe9:-MUEVihyDJ15EfoILeT8:b-aq4ada) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L33)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It would be better to not hold those vectors in global scope, as it's hard to do major changes on such code later. 
</blockquote></details>

Maybe class describing this workload, then we can also add extra features like getNextKey and received key with specified distribution.
___
*[benchmarks/radix/radix_tree.cpp, line 65 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTptO6W3GV7enivyZTB:-MUEWkvd3N5B6mLeBf5x:b32v57) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L65)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

```
key1 |= 0x1 
```
would be cleaner
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-02-25 11:40 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/radix/radix_tree.cpp, line 22 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq25up3i8iehvRFzQ4:-MUNFTvt4gklclH8rFn4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L22)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

fields data_1 and data_2 are not used
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8DtasApRWvG2yDwe9:-MUNcX501NCvcfjJEx22:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Maybe class describing this workload, then we can also add extra features like getNextKey and received key with specified distribution.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpqisn6bFalOJKwGI3:-MUNG6Kn0wCatev3WnSD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L55)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

generate_nonexisting_keys() and change all naming to be more human readabl, "ne" means nothing.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8EE414ALCYphX5KXA:-MUNcZKX7phkqwrt2W-K:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L55)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This function may retrun vecor<size_t>, and get count and size as parameters. 
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 61 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpzdJs6A6vkpG9TFrb:-MUNJMrk73cKF0iZJK7D:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L61)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

every unsigned long/unsigned should be changed to size_t
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 65 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTptO6W3GV7enivyZTB:-MUNKekW7Y5q27dq4p52:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L65)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 66 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvyeb65zgBS8xVZm0:-MUNL4Yc4f3vDqHZihGO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L66)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

key |= key1;
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 72 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MU8FlctEdrU3NGDIFtf:-MUNccQC4ph49BQVaSBx:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L72)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

this function may just return vector keys_to_insert, and than you may iterate over returned vector with sample_rate to construct keys_to_lookup. 
Or just iterate over keys_to_insert with sample_rate in lookup_elements functions.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 83 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvhh_-_fHhzkga2o2:-MUNWGOBCg17n5NWkJd5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L83)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

same as above:
key1 |= 1 << 0;
or
rand() | 1 << 0
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 84 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpvvm_Awnsz8bbF64I:-MUNWJ-z-LeSpta9agqQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L84)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

key |= key1;
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpwD5J4z2lagnfEdP1:-MUNcyBG3SWTwZ1BDlrI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L103)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

few times above was 'i' instead of 'j' in loops.
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 198 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTpyWIx4RGqDIaZHjQ7:-MUNVTunCucfS_3y-VQ1:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L198)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	std::cout << "Average remove time (map): "
> 		  << static_cast<unsigned long>(std_map_time) /
> 			keys_to_insert.size()
> 		  << "ns" << std::endl;
> ```

Code multiplication, change it to:
```
print_time_per_element("Average remove time (map)", std_map_time, keys_to_insert.size());
```

Function can look like this:
```
void print_time_per_element(string msg, unsigned long total_time, size_t num_of_elements) {
    std::cout << msg + ": " 
        << static_cast<unsigned long>(std_map_time) / keys_to_insert.size()
        << "ns" << std::endl;
}
```
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 235 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq0lXHC4Bs61ntLznu:-MUNVqHT5r7Aou0INWVy:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L235)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		std::cerr << e.what() << std::endl;
> 		std::cerr
> 			<< "To create pool run: pmempool create obj --layout=radix -s 1G path_to_pool"
> 			<< std::endl;
> ```

```
std::cerr << e.what() << std::endl
    << "To create pool run: pmempool create obj --layout=radix -s 1G path_to_pool"
    << std::endl;
```
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 252 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq2BQS4hsav1297qo_:-MUNFawp8xhj1qqMNtQM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42be426d959dab1d74be16a3f016ceb844c16ed0/benchmarks/radix/radix_tree.cpp#L252)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Use this if you want to initialize fields.
```
value_type value = { i };
```
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 276 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MTq1_QO6vbY1llCBZF8:-MUNVx5w5UYBGOyblc [...]

2021-02-25 16:52 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @KFilipek)

___
*[benchmarks/radix/radix_tree.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MUP3cFoA0A3RlxOoJkc:-MUP3cFoA0A3RlxOoJkd:b-7gv5pz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1b89bb537f91c0d92cf16daf89acd851d8a52ed3/benchmarks/radix/radix_tree.cpp#L28)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> struct benchmark_params {
> 	size_t count = 10000;
> 	size_t sample_size = 100;
> 	size_t batch_size = 1000;
> };
> ```
</details>

This struct is used in this file only for containing and grouping this fields/variables.
No offence, it looks good, but IMO better will be (you can now delete further instantiate, ***params*** variable is created here:
```cpp
struct benchmark_params {
	size_t count = 10000;
	size_t sample_size = 100;
	size_t batch_size = 1000;
} params;
```
Also: it's now global visible so you don't have to pass it to every function. Anonymous struct like below is the way for one-file applications with global variables.
```cpp
struct {
	size_t count = 10000;
	size_t sample_size = 100;
	size_t batch_size = 1000;
} benchmark_params;
```
___
*[benchmarks/radix/radix_tree.cpp, line 50 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MUP4tbG28bGfuvUToL7:-MUP4tbG28bGfuvUToL8:bfu9fyl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1b89bb537f91c0d92cf16daf89acd851d8a52ed3/benchmarks/radix/radix_tree.cpp#L50)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> void
> print_time_per_element(std::string msg,
> 		       std::chrono::nanoseconds::rep total_time,
> 		       size_t n_elements)
> {
> 	std::cout << msg << static_cast<size_t>(total_time) / n_elements << "ns"
> 		  << std::endl;
> }
> ```
</details>

Great!
___
*[benchmarks/radix/radix_tree.cpp, line 100 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MUP5FDwEQ2YTJc5ffIR:-MUP5FDwEQ2YTJc5ffIS:bfwgwo1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1b89bb537f91c0d92cf16daf89acd851d8a52ed3/benchmarks/radix/radix_tree.cpp#L100)):*
> ```cpp
> template <typename F>
> void
> insert_elements_kv(F &&insert_f, benchmark_params &params,
> ```

here you will have only 2 args with approach I've proposed on the top


<!-- Sent from Reviewable.io -->

2021-03-01 08:38 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[benchmarks/radix/radix_tree.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MUP3cFoA0A3RlxOoJkc:-MUgvkQIAKQakhkTUQho:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1b89bb537f91c0d92cf16daf89acd851d8a52ed3/benchmarks/radix/radix_tree.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> struct benchmark_params {
> 	size_t count = 10000;
> 	size_t sample_size = 100;
> 	size_t batch_size = 1000;
> };
> ```
This struct is used in this file only for containing and grouping this fields/variables.
No offence, it looks good, but IMO better will be (you can now delete further instantiate, ***params*** variable is created here:
```cpp
struct benchmark_params {
	size_t count = 10000;
	size_t sample_size = 100;
	size_t batch_size = 1000;
} params;
```
Also: it's now global visible so you don't have to pass it to every function. Anonymous struct like below is the way for one-file applications with global variables.
```cpp
struct {
	size_t count = 10000;
	size_t sample_size = 100;
	size_t batch_size = 1000;
} benchmark_params;
```
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 100 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-MUP5FDwEQ2YTJc5ffIR:-MUgvl95-nHklgO8CDpr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1b89bb537f91c0d92cf16daf89acd851d8a52ed3/benchmarks/radix/radix_tree.cpp#L100)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

here you will have only 2 args with approach I've proposed on the top
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-01 10:13 UTC, KFilipek reviewed
Great job: <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-:-MUhGlw88XlteTSS0Kmh:b-tbygtl)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @karczex)



<!-- Sent from Reviewable.io -->

2021-04-27 14:58 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-04-28 09:00 UTC, KFilipek approved these changes

2021-04-28 12:01 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1038#-:-MZNLlUlEA-0Ky0b-E_D:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-04-28 12:02 UTC, merged