Radix: concurrent erase
pmem/libpmemobj-cpp pull request #1078
Opened 2021-06-04 07:58 UTC by JanDorniak99

Only two last commits belong to this PR.

2021-06-04 10:25 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/detail/ebr.hpp, line 47 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLT0NIEtZukNx2LGsq:-MbLT0NIEtZukNx2LGsr:b1nozp5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L47)):*
> ```cpp
> 
> class ebr {
> 	using atomic = std::atomic<size_t>;
> ```

Does it have to be public?
___
*[include/libpmemobj++/detail/ebr.hpp, line 48 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLS40Y2mw1SWuAvDgn:-MbLS40Y2mw1SWuAvDgo:byuxq8c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L48)):*
> ```cpp
> class ebr {
> 	using atomic = std::atomic<size_t>;
> 	using reference = std::reference_wrapper<atomic>;
> ```

Nice, I didn't know about this. But do we have to expose this type publicly? Is there any public method wich accepts/returns this type?
___
*[include/libpmemobj++/detail/ebr.hpp, line 56 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLT6GM2nJEYJQB83QY:-MbLT6GM2nJEYJQB83QZ:ba653qm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L56)):*
> ```cpp
> 
> 	worker register_worker();
> 	void unregister_worker(std::thread::id t_id);
> ```

do we need this function? we can probably just rely on worker dtor
___
*[include/libpmemobj++/detail/ebr.hpp, line 67 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLSkO27J5ko0d-vA51:-MbLSkO3Aoohq28kmKIi:bk9ltuj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L67)):*
> ```cpp
> 		~worker();
> 
> 		void critical(std::function<void()> f);
> ```

I think it would be better to make it a template function and accept `F&& f`. This way we do not have any overhead from std::function. Just write in the docs that this function should not accept nor return anything.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 939 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLW-xQ32iNxpoqi8eA:-MbLW-xQ32iNxpoqi8eB:b-upiimp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/experimental/radix_tree.hpp#L939)):*
> ```cpp
> template <typename Key, typename Value, typename BytesView>
> void
> radix_tree<Key, Value, BytesView>::garbage_collect_force()
> ```

shouldn't you call ebr_full_sync somewhere?
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 1 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLWXU63jSCr4drlbsu:-MbLWXU63jSCr4drlbsv:b-wavtb7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_erase.cpp#L1)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> ```

You can see if it makes sense to port: https://github.com/rmind/libqsbr/blob/master/src/t_stress.c
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 44 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLXSScCKntJhHiKM3C:-MbLXSScCKntJhHiKM3D:blc2gmc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L44)):*
> ```cpp
> 				}
> 			}
> 			UT_ASSERTeq(cnt, INITIAL_ELEMENTS);
> ```

why this should be equal? shouldn't we count elements which were present from the beginning?
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 92 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLXwyXCYQetcZnMHV9:-MbLXwyXCYQetcZnMHVA:b-q3vutj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L92)):*
> ```cpp
> 				for (auto it = ptr->begin(); it != ptr->end();
> 				     ++it) {
> 					if (it->key() % 2) {
> ```

some comment would be helpful (here or just short description of the test above the definition)
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 109 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLY7X1AlSJwXriGlIo:-MbLY7X1AlSJwXriGlIp:b-l5j4wg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L109)):*
> ```cpp
> 	/* It is random how many garbage vectors will be allocated inside the
> 	 * radix (from 0 to 3) */
> 	UT_ASSERT(num_allocs(pop) >= expected_allocs &&
> ```

hm, maybe we could force 3 full gc cycles before the test to make sure all vectors are allocated?


<!-- Sent from Reviewable.io -->

2021-06-08 09:58 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 0 of 19 files reviewed, 8 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/detail/ebr.hpp, line 47 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLT0NIEtZukNx2LGsq:-Mb_bFvY4nDKl-chd0JV:bsrfe89) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Does it have to be public?
</blockquote></details>

Isn't that already private?
___
*[include/libpmemobj++/detail/ebr.hpp, line 48 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLS40Y2mw1SWuAvDgn:-Mb_bLBqExHP36s91UpD:b-vs7gkf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Nice, I didn't know about this. But do we have to expose this type publicly? Is there any public method wich accepts/returns this type?
</blockquote></details>

Isn't that already private?
___
*[include/libpmemobj++/detail/ebr.hpp, line 56 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLT6GM2nJEYJQB83QY:-Mb_bgOz6yLZRMl-GUH_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

do we need this function? we can probably just rely on worker dtor
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/ebr.hpp, line 67 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLSkO27J5ko0d-vA51:-Mb__RJg2j5filMAXSTV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/detail/ebr.hpp#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better to make it a template function and accept `F&& f`. This way we do not have any overhead from std::function. Just write in the docs that this function should not accept nor return anything.
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 44 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLXSScCKntJhHiKM3C:-Mb_cqNg8iyfBFrIb4nE:bktncjr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why this should be equal? shouldn't we count elements which were present from the beginning?
</blockquote></details>

We actually count this elements (look there is !(it->value() == new_elements_value)). It is probably a little bit unclear so I will add operator!= for this comparison in test utils (currently we have only ==).
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 92 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLXwyXCYQetcZnMHV9:-Mb_lliy5Xbf18wLmUbi:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L92)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

some comment would be helpful (here or just short description of the test above the definition)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-08 15:37 UTC, igchor reviewed
Please rebase the impmenetation

> Reviewed 2 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-:-MbgGIjE26DcL-qiVPck:bv8ej5u)* status: 2 of 19 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)



<!-- Sent from Reviewable.io -->

2021-06-10 11:58 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 2 of 19 files reviewed, 14 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ebr.hpp, line 127 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbp6mWr8kNsiYP66w_5:-MbpQzB71pR19dUtX1NP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/include/libpmemobj++/detail/ebr.hpp#L127)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this number 3 could be a global const, I guess
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 939 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLW-xQ32iNxpoqi8eA:-MbfGQBaDptZe179S4Oi:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/include/libpmemobj++/experimental/radix_tree.hpp#L939)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't you call ebr_full_sync somewhere?
</blockquote></details>

Done.
___
*[tests/radix_tree/radix.hpp, line 161 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpAG9k44RARyEWpkSs:-MbpgrWJCAwVDBR11DMF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix.hpp#L161)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you can rename `writer` here
</blockquote></details>

Done.
___
*[tests/radix_tree/radix.hpp, line 175 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbp8aIf9MEZ65Mg4UN6:-Mbpa9Oj0mQcTCApXlbe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix.hpp#L175)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls break this long line
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent.cpp, line 124 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbp9B6p7s1mAzUgnmi2:-MbpbYNs9TqoFNXBdAI6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent.cpp#L124)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why does it only work with int values? and I see you hardcoded container "int_int" - what about other value types as keys?

it the comment makes sense, perhaps move it to the test function instead; otherwise you can remove this comment
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 4 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpBYgWCPBXReFNX8UR:-MbpaLoM2E5RKN_v6gSM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent_erase.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need to include it here?
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 28 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbp9yvn88dOcC90g3-f:-MbpgKbW7ABcswbyVWmB:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent_erase.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`writer_f` ? ;)
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 86 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpB36DEZGqEo27aeN5:-MbpgQk31zP_dLOxAnuX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent_erase.cpp#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls write a short comment, what is achieved here (I'm not sure what the emplace does here with `value_repeats`, tbh)

in general, you could add few comments to sections of all of these tests (or at least a "per test" comment)
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 6 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpBZk0BUdvocRoDhp2:-MbpaR2a00Kze1OUqXqg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent_iterate.cpp#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need to include it here?
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 300 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpCNghC902NolHZQ03:-MbpaSQpA7vx__soXu2j:b-pmlhkk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix_concurrent_iterate.cpp#L300)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why you can't run these on drd?
</blockquote></details>

It takes too much time to test it for all types, and it results in a timeout.


<!-- Sent from Reviewable.io -->

2021-06-11 06:09 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 1 of 20 files reviewed, 16 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ebr.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbteP-KA9TaKfHFzydH:-MbteP-KA9TaKfHFzydI:b-m1vk2i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/detail/ebr.hpp#L153)):*
> ```cpp
> 	auto current_epoch = global_epoch.load();
> 
> 	mtx.lock();
> ```

Instead of mt.lock/unlock you can use std::scoped_lock 
___
*[include/libpmemobj++/detail/ebr.hpp, line 183 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbte7wWAQNz3kPqYqg7:-Mbte7wWAQNz3kPqYqg8:bnu4s30) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/detail/ebr.hpp#L183)):*
> ```cpp
> 	size_t syncs_cnt = 0;
> 	while (true) {
> 		if (sync() && ++syncs_cnt == EPOCHS_NUMBER) {
> ```

How did you come up with this implementation? Is it equvialent to: https://github.com/rmind/libqsbr/blob/master/src/ebr.c#L273? 
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1026 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbtftGZ7AW2uPFZZWdf:-MbtftGZ7AW2uPFZZWdg:b1yuubx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L1026)):*
> ```cpp
>  * Disables single-writer multiple-readers concurrency with read uncommitted
>  * isolation. This property is NOT persistent. Disabling must be done before
>  * each application close.
> ```

Please add comment, that this function must also be called before calling radix_tree dtor.


<!-- Sent from Reviewable.io -->

2021-06-16 08:07 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 1 of 21 files reviewed, 16 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbp5VL417Qcjfbnbaxd:-McDyWrK4HdtuXFs2_db:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

your commit "radix_tree: allow concurrent erase and read" should also update the top-level LICENSE file (with new exception - the ebr file)
</blockquote></details>

Done.

---
___
*[include/libpmemobj++/detail/ebr.hpp, line 153 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbteP-KA9TaKfHFzydH:-McDt4gZ0cum8P5uOH2c:bqz5lwg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/detail/ebr.hpp#L153)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Instead of mt.lock/unlock you can use std::scoped_lock 
</blockquote></details>

I changed to lock_guard (scoped_lock is since c++17)
___
*[include/libpmemobj++/detail/ebr.hpp, line 183 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mbte7wWAQNz3kPqYqg7:-McDwtkq9ijQX_WZEA1-:b9ssryz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/detail/ebr.hpp#L183)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How did you come up with this implementation? Is it equvialent to: https://github.com/rmind/libqsbr/blob/master/src/ebr.c#L273? 
</blockquote></details>

Yes, I guess it will have the same effect.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1026 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbtftGZ7AW2uPFZZWdf:-McDuyud0kBoEO6lt-4m:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L1026)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add comment, that this function must also be called before calling radix_tree dtor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-16 08:30 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 10 files at r5, 3 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 5 of 21 files reviewed, 10 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[LICENSE, line 45 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIs8TF7_PfpEdL2mSu:-McIs8TF7_PfpEdL2mSv:b-4upcl4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dd609c27d1f635faf7a481f4417d2e5d9247acce/LICENSE#L45)):*
> ```
> * include/detail/ebr.hpp contain EBR implementation adapted
>   from: https://github.com/rmind/libqsbr which is covered by
>   licence included in those files.
> ```

in this file
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 326 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIl_ihCn8hubW-Omk6:-McIl_ihCn8hubW-Omk7:b-otdodu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L326)):*
> ```cpp
> 	p<uint64_t> size_;
> 	v<uint64_t> mt;
> 	vector<pointer_type> garbages[3];
> ```

magic number 3 - pls fix with EPOCHS_NUMBER [in all files]
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 957 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIlznFEdNhVbDBho43:-McIlznFEdNhVbDBho44:b-8z7wyl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L957)):*
> ```cpp
>  * insert_or_assign or assign_val in concurrent mode (if runtime_initialize_mt
>  * was called). It is not guaranteed that this method will free any memory. It
>  * depence on operations currently performed by other threads.
> ```

depence -> depends
___
*[tests/radix_tree/radix.hpp, line 161 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbpAG9k44RARyEWpkSs:-McIsySEEfonNptNbkZP:b2nid0f) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f0ed63e8caec6ba5710537d43a668a6cc0aee2f/tests/radix_tree/radix.hpp#L161)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 173 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIu8HJ2mKxlTfZjaKl:-McIu8HJ2mKxlTfZjaKm:b-88mb1a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dd609c27d1f635faf7a481f4417d2e5d9247acce/tests/radix_tree/radix_concurrent_erase.cpp#L173)):*
> ```cpp
> 	});
> 
> 	/* check if something was removed permamently */
> ```

misspell (`permanently`)


<!-- Sent from Reviewable.io -->

2021-06-16 09:46 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 5 of 21 files reviewed, 10 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[LICENSE, line 45 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIs8TF7_PfpEdL2mSu:-McIyGs78ogEXR0m6SlX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dd609c27d1f635faf7a481f4417d2e5d9247acce/LICENSE#L45)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in this file
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 326 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIl_ihCn8hubW-Omk6:-McIzHfd4S_3k7jIURoz:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L326)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

magic number 3 - pls fix with EPOCHS_NUMBER [in all files]
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 957 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIlznFEdNhVbDBho43:-McIzPX04xr1Dwzukr4i:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/458b133860eef689dc6633a174160e160867fef9/include/libpmemobj++/experimental/radix_tree.hpp#L957)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

depence -> depends
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 173 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McIu8HJ2mKxlTfZjaKl:-McIzWNe5fw0OfoyErWe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dd609c27d1f635faf7a481f4417d2e5d9247acce/tests/radix_tree/radix_concurrent_erase.cpp#L173)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell (`permanently`)
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 109 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLY7X1AlSJwXriGlIo:-McJCbYE6cWs_5LtWK4X:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_iterate.cpp#L109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

hm, maybe we could force 3 full gc cycles before the test to make sure all vectors are allocated?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 08:10 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 12 files at r9, 5 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-:-MchbiNL6fFWrBBqD3C5:bnfp4nl)* status: 13 of 21 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-22 07:50 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 18 files at r4, 2 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-:-Mcmgik4E3lTWwSVPaKx:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-22 07:51 UTC, KFilipek reviewed
> Reviewed 2 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-23 18:37 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 12 files at r9, 6 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: all files reviewed, 12 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mcu8x095-EicwUEyDbb:-Mcu8x095-EicwUEyDbc:b-cpf1pg) (no related file):*
not sure if necessary in this PR, but perhaps update the example (with GC usage)

---
___
*[include/libpmemobj++/detail/ebr.hpp, line 26 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctVyemCN-2OsMn2Yn8:-MctVyemCN-2OsMn2Yn9:bc60je) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L26)):*
> ```cpp
>  * SUCH DAMAGE.
>  */
> ```

pls add a file description (doxygen's  `@file` annotation)
___
*[include/libpmemobj++/detail/ebr.hpp, line 133 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctjakY-50s27V8tche:-MctjakY-50s27V8tchf:b2vbk9v) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L133)):*
> ```cpp
> 	std::lock_guard<std::mutex> lock(mtx);
> 	auto res = workers.emplace(std::this_thread::get_id(), 0);
> 	assert(res.second);
> ```

maybe throw instead of assert - if someone adds the second worker in the same thread it will crash
___
*[include/libpmemobj++/detail/ebr.hpp, line 141 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctbnHW-Db3MAaFYHzo:-MctbnHX3NxUDmeiVjBS:b6tphxx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L141)):*
> ```cpp
>  * Attempts to synchronise and announce a new epoch.
>  *
>  * The synchronisation points must be serialised (e.g. if there are multiple G/C
> ```

`serialised` -> `serialized` (pls pick the latter form, as it's used later on in this file)
___
*[include/libpmemobj++/detail/ebr.hpp, line 143 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctcz93BU857uiEe8e8:-Mctcz93BU857uiEe8e9:b-7ashw1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L143)):*
> ```cpp
>  * The synchronisation points must be serialised (e.g. if there are multiple G/C
>  * workers or other writers). Generally, calls to ebr::staging_epoch() and
>  * ebr::gc_epoch() would be a part of the same serialised path.
> ```

what do you mean by `Generally, calls to ebr::staging_epoch() and ebr::gc_epoch() would be a part of the same serialised path.`?
___
*[include/libpmemobj++/detail/ebr.hpp, line 144 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctbCya0F1qW8scYJ7j:-MctbCybDGjvub5niSF0:bd83841) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L144)):*
> ```cpp
>  * workers or other writers). Generally, calls to ebr::staging_epoch() and
>  * ebr::gc_epoch() would be a part of the same serialised path.
>  *
> ```

you could write, **why** this method may return false
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 943 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctgq98BBd268vtcunL:-Mctgq98BBd268vtcunM:b-y01wto) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L943)):*
> ```cpp
>  * garbage produced by erase, clear, insert_or_assign or assign_val in
>  * concurrent mode (if runtime_initialize_mt was called).
>  *
> ```

do we have any guarantees in this method, to free any memory?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 980 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McthHaA4MLgLQ7DhJX8:-McthHaA4MLgLQ7DhJX9:bp49wk3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L980)):*
> ```cpp
> radix_tree<Key, Value, BytesView>::clear_garbage(size_t n)
> {
> 	assert(n >= 0 && n <= 2);
> ```

`n < EPOCHS_NUMBER`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1015 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mcthc7R60sKV-mzBh8h:-Mcthc7S09_HF_J7QVCx:b-8bx6kx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L1015)):*
> ```cpp
>  * By default, concurrency is not enabled.
>  *
>  * @param[in] e pointer to own ebr, default it will be created automatically.
> ```

`own` -> `custom`? (I'm not sure what wording would be the best)
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1031 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctiUCNEau3OkpdFbjS:-MctiUCNEau3OkpdFbjT:bou0ed9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L1031)):*
> ```cpp
>  * Disables single-writer multiple-readers concurrency with read uncommitted
>  * isolation. This property is NOT persistent. Disabling must be done before
>  * each application close and before calling radix destructor.
> ```

`Disabling must be done` or else what...?
___
*[tests/ebr/ebr.cpp, line 6 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctt3gP-aGWh93YOYlv:-Mctt3gP-aGWh93YOYlw:b-pu5idb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/tests/ebr/ebr.cpp#L6)):*
> ```cpp
> #include "libpmemobj++/detail/ebr.hpp"
> #include "../common/thread_helpers.hpp"
> #include "../common/unittest.hpp"
> ```

is `../common/` part needed?
___
*[tests/radix_tree/radix.hpp, line 181 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mcu8pzaAGWoeF3X6O3K:-Mcu8pzbDLpeFWu-lmRT:bko17ea) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/tests/radix_tree/radix.hpp#L181)):*
> ```cpp
> template <typename ModifyF, typename ReadF>
> static void
> parallel_write_read(ModifyF modifier, std::vector<ReadF> &readers,
> ```

you could also modify the name of the function ;)
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 1 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLWXU63jSCr4drlbsu:-MctvY4g7tNWmbDhsLll:bs0b4c7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_erase.cpp#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can see if it makes sense to port: https://github.com/rmind/libqsbr/blob/master/src/t_stress.c
</blockquote></details>

what about this?


<!-- Sent from Reviewable.io -->

2021-06-24 11:46 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 13 of 21 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ebr.hpp, line 26 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctVyemCN-2OsMn2Yn8:-McxJf1vE8IjBhiYTmgs:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a file description (doxygen's  `@file` annotation)
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/ebr.hpp, line 133 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctjakY-50s27V8tche:-McxLKGy14PZgTCgV6aN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L133)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe throw instead of assert - if someone adds the second worker in the same thread it will crash
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/ebr.hpp, line 141 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctbnHW-Db3MAaFYHzo:-McxOGey1WUgH4L8Qc0e:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L141)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`serialised` -> `serialized` (pls pick the latter form, as it's used later on in this file)
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/ebr.hpp, line 143 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctcz93BU857uiEe8e8:-McxolVtEiRFb88iC8EA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L143)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by `Generally, calls to ebr::staging_epoch() and ebr::gc_epoch() would be a part of the same serialised path.`?
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/ebr.hpp, line 144 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctbCya0F1qW8scYJ7j:-McxmlS_23bfsXaL1w_m:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/detail/ebr.hpp#L144)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could write, **why** this method may return false
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 943 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctgq98BBd268vtcunL:-McxmySGBtRafIsr-yql:b-x3b5ka) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L943)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we have any guarantees in this method, to free any memory?
</blockquote></details>

Yes, it will free everything.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 980 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-McthHaA4MLgLQ7DhJX8:-McxOQln2Gx_4Que2neH:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L980)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`n < EPOCHS_NUMBER`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1015 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mcthc7R60sKV-mzBh8h:-McxOwmvCzBl63WBf_3Z:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L1015)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`own` -> `custom`? (I'm not sure what wording would be the best)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1031 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MctiUCNEau3OkpdFbjS:-McxngbRD1Z31D95yyKg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L1031)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Disabling must be done` or else what...?
</blockquote></details>

Done.
___
*[tests/ebr/ebr.cpp, line 6 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mctt3gP-aGWh93YOYlv:-McxPj36-wsAPeVE_laa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/tests/ebr/ebr.cpp#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is `../common/` part needed?
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 1 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MbLWXU63jSCr4drlbsu:-Mcxj5rIEV9QJ_rlrChR:b-6k03wo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a779bb3c78b144681e64efc7a17158000c082bb8/tests/radix_tree/radix_concurrent_erase.cpp#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about this?
</blockquote></details>

A similar test is already in ebr.cpp


<!-- Sent from Reviewable.io -->

2021-06-28 09:04 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 16 of 21 files reviewed, 11 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 124 at r12](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MdGqwKQ3fWT_YWemL1W:-MdGqwKQ3fWT_YWemL1X:bdkbaii) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a8ff87e58088e80454b4a8f6dc07df731e5d894b/include/libpmemobj++/experimental/radix_tree.hpp#L124)):*
> ```cpp
> 	using const_reverse_iterator = std::reverse_iterator<const_iterator>;
> 	using difference_type = std::ptrdiff_t;
> 	using ebr = detail::ebr;
> ```

please also add alias for ebr::worker (maybe instead of ebr, it;s not used directly, right?):
```
using worker_type = detail::ebr::worker
```


<!-- Sent from Reviewable.io -->

2021-06-28 10:48 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @igchor, @JanDorniak99, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ebr.hpp, line 237 at r12](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MdHDSeyDxqgDkcZ2P6G:-MdHDSeyDxqgDkcZ2P6H:b-unb0eb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a8ff87e58088e80454b4a8f6dc07df731e5d894b/include/libpmemobj++/detail/ebr.hpp#L237)):*
> ```cpp
> /**
>  * Unregisters the worker from the list of the workers in the ebr.
>  */
> ```

Please add info that all workers should be destroyed PRIOR to the destruction of ebr class (otherwise we will try to access unordered map which is already destroyed). Please also create an issue - Feature request to lift this requirement (e.g. by using shared_ptr). You can also mention that mpsc_queue has the same problem.


<!-- Sent from Reviewable.io -->

2021-06-29 10:02 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ebr.hpp, line 237 at r12](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MdHDSeyDxqgDkcZ2P6G:-MdMD5NF2ZuMmvEpMeN_:b-chaz7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a8ff87e58088e80454b4a8f6dc07df731e5d894b/include/libpmemobj++/detail/ebr.hpp#L237)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add info that all workers should be destroyed PRIOR to the destruction of ebr class (otherwise we will try to access unordered map which is already destroyed). Please also create an issue - Feature request to lift this requirement (e.g. by using shared_ptr). You can also mention that mpsc_queue has the same problem.
</blockquote></details>

Done. #1109 
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 124 at r12](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-MdGqwKQ3fWT_YWemL1W:-MdM0mQe9-xZo-kpUUKm:b-48k00i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a8ff87e58088e80454b4a8f6dc07df731e5d894b/include/libpmemobj++/experimental/radix_tree.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please also add alias for ebr::worker (maybe instead of ebr, it;s not used directly, right?):
```
using worker_type = detail::ebr::worker
```
</blockquote></details>

Done, ebr is used in runtime_initialize_mt(ebr* e)


<!-- Sent from Reviewable.io -->

2021-06-30 13:33 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-:-MdMENhpAjkPa6ppsWOm:bnfp4nl)* status: 12 of 21 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-07-02 10:31 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 8 files at r11, 3 of 4 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-:-MdalLmYEuizqhnLmz7B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1015 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1078#-Mcthc7R60sKV-mzBh8h:-Mdal4GL8OsMxBc1Sw_l:b-q74txj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a51b0312f3646ac0fa4e5fd47cc61de17e2532c2/include/libpmemobj++/experimental/radix_tree.hpp#L1015)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

great!


<!-- Sent from Reviewable.io -->

2021-07-02 10:34 UTC, merged