Make cpp-format targets always working
pmem/libpmemobj-cpp pull request #1118
Opened 2021-07-02 07:29 UTC by karczex

As cpp-format targets are always generated anyway, they should work even
if CHECK_CPP_STYLE flag is disabled.

2021-07-02 09:03 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[CMakeLists.txt, line 193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdaRs91D5W7OBFcrykB:-MdaRs91D5W7OBFcrykC:b-cik2vr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L193)):*
> ```CMake
> endif()
> 
> if(CHECK_CPP_STYLE)
> ```

this change was initially done to avoid looking for clang-format (v. 9) on some OSes. It will be an issue on these OSes, which don't have the required clang-format, so I believe it's not the solution.. :wink:


<!-- Sent from Reviewable.io -->

2021-07-02 09:37 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

___
*[CMakeLists.txt, line 193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdaRs91D5W7OBFcrykB:-MdaZDkBC6OLVTEBxDDC:b-s74i2o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L193)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this change was initially done to avoid looking for clang-format (v. 9) on some OSes. It will be an issue on these OSes, which don't have the required clang-format, so I believe it's not the solution.. :wink:
</blockquote></details>

or maybe not :smile:

but pls check the other OSes


<!-- Sent from Reviewable.io -->

2021-07-05 15:24 UTC, lukaszstolarczuk reviewed
beside the two minor issues it looks good :+1:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-:-MdrGHjaESogbN-GJjcE:bmwoe0j)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[CMakeLists.txt, line 186 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdrFxut1NPwKeEL1M5R:-MdrFxut1NPwKeEL1M5S:b-226qt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L186)):*
> ```CMake
> 			BSD-3-Clause)
> 
> find_program(CLANG_FORMAT NAMES clang-format clang-format-9 clang-format-9.0)
> ```

I guess we should re-order these names - firstly try to find cf9 (and 9.0), then cf
___
*[CMakeLists.txt, line 189 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdrFhmGBpa9YMJlUnUR:-MdrFhmGBpa9YMJlUnUS:b-kcw74b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L189)):*
> ```CMake
> set(CLANG_FORMAT_REQUIRED "9.0")
> if(CLANG_FORMAT)
> 	message(STATUS "Found clang-format: ${CLANG_FORMAT} (version: ${CLANG_FORMAT_VERSION})")
> ```

pls switch the order of these two lines - `${CLANG_FORMAT_VERSION}` is only set after the `get_program_version_major_minor` function call :wink:


<!-- Sent from Reviewable.io -->

2021-07-05 15:26 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-:-MdrGo0bDtm5M24tU5Pc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-07-22 08:46 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[cmake/functions.cmake, line 102 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MfCO52J4Pet4f073x1P:-MfCO52J4Pet4f073x1Q:bshnm2e) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/cmake/functions.cmake#L102)):*
> ```CMake
> # ${name} must be unique.
> function(add_cppstyle name)
> 	if(NOT CLANG_FORMAT AND NOT (CLANG_FORMAT_VERSION VERSION_EQUAL CLANG_FORMAT_REQUIRED))
> ```

AND? Shouldn't this be OR?


<!-- Sent from Reviewable.io -->

2021-07-29 16:20 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 186 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdrFxut1NPwKeEL1M5R:-MfXTvER87zHjAz5tLKi:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L186)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess we should re-order these names - firstly try to find cf9 (and 9.0), then cf
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 189 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MdrFhmGBpa9YMJlUnUR:-MfmtteW6pOSMXr8afCF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/CMakeLists.txt#L189)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls switch the order of these two lines - `${CLANG_FORMAT_VERSION}` is only set after the `get_program_version_major_minor` function call :wink:
</blockquote></details>

Done.
___
*[cmake/functions.cmake, line 102 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-MfCO52J4Pet4f073x1P:-Mfn3FgR8nVabuESaPXh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6721c39b658d7214dda7a5802240e29146b08767/cmake/functions.cmake#L102)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

AND? Shouldn't this be OR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 16:44 UTC, KFilipek reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-07-29 16:45 UTC, KFilipek approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

2021-07-29 16:45 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1118#-:-Mfn8vLs1ygBZZ3D6Yoh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-07-29 18:14 UTC, merged