Mpsc queue docs
pmem/libpmemobj-cpp pull request #1119
Opened 2021-07-02 10:35 UTC by karczex

2021-07-02 12:23 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[examples/mpsc_queue/mpsc_queue.cpp, line 49 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdb9XgpD34dDtAL-5EM:-Mdb9XgpD34dDtAL-5EN:b-nsijol) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6a7e044a54eb018bba5d35d1541efa4b889b76c8/examples/mpsc_queue/mpsc_queue.cpp#L49)):*
> ```cpp
> 		[&](pmem::obj::experimental::mpsc_queue::batch_type rd_acc) {
> 			for (pmem::obj::string_view str : rd_acc) {
> 				std::cout << str.data() << std::endl;
> ```

Problem with printing garbage is that there is no null terminator. This is once again problem with no operator<< for string_view. 
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 37 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdb9nJAAuXdv886RAoW:-Mdb9nJAAuXdv886RAoX:b-ppcjoq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6a7e044a54eb018bba5d35d1541efa4b889b76c8/include/libpmemobj++/experimental/mpsc_queue.hpp#L37)):*
> ```cpp
>  * In case of crash or shutdown, reading and writing may be continued
>  * by new process, without loss of any, already produced data.
>  *
> ```

Please add that, try_consume_batch MUST be called after restart (otherwise produce might fail even if the queue is empty).


<!-- Sent from Reviewable.io -->

2021-07-05 07:34 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 37 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdb9nJAAuXdv886RAoW:-Mdp_pkEDv6_x1tWiXR2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6a7e044a54eb018bba5d35d1541efa4b889b76c8/include/libpmemobj++/experimental/mpsc_queue.hpp#L37)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add that, try_consume_batch MUST be called after restart (otherwise produce might fail even if the queue is empty).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-05 12:09 UTC, igchor requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[examples/mpsc_queue/CMakeLists.txt, line 5 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdqYw9TB9OVpNnlL02k:-MdqYw9TB9OVpNnlL02l:b-gdmccz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/CMakeLists.txt#L5)):*
> ```CMake
> 
> cmake_minimum_required(VERSION 3.3)
> project(inline_string CXX)
> ```

inline_string?
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 322 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdqZRyK9zWX9CoFqkCc:-MdqZRyK9zWX9CoFqkCd:blwnmd9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L322)):*
> ```cpp
> 
> /**
>  * Evaluates function f for the data, which is ready to be consumed.
> ```

Please also mention that try_consume_batch starts transaction internally (user callback is called within a transaction).
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 330 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdqZOHQBVoEiNCysDrB:-MdqZOHQBVoEiNCysDrC:b-kej3uw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L330)):*
> ```cpp
>  *
>  * see also: mpsc_queue::worker::try_produce()
>  *
> ```

@throws transaction_scope_error ...


<!-- Sent from Reviewable.io -->

2021-07-05 15:40 UTC, KFilipek reviewed
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-07-06 09:42 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: all files reviewed, 30 unresolved discussions (waiting on @karczex)

___
*[examples/CMakeLists.txt, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdukzYEAacdgKYClTtz:-MdukzYEAacdgKYClTu-:b22p3tg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/CMakeLists.txt#L49)):*
> ```CMake
> # Add developer checks
> add_cppstyle(examples ${CMAKE_CURRENT_SOURCE_DIR}/*/*.*pp)
> add_check_whitespace(examples ${CMAKE_CURRENT_SOURCE_DIR}/*.*)
> ```

you've missed on level - `/*`
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 39 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdullZB23PuhDipVn7J:-MdullZC9T7v7XJTbZ8i:bwym8py) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L39)):*
> ```cpp
> 	pmem::obj::persistent_ptr<root> proot = pop.root();
> 
> 	/* Create mpsc_queue runtime, which uses pmem_log_type object to store
> ```

**at** runtime (?)

I'm not sure what you had in mind
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 43 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdum33N1c0s_M7n0Jwh:-Mdum33N1c0s_M7n0Jwi:b-oxdtnt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L43)):*
> ```cpp
> 	auto queue = pmem::obj::experimental::mpsc_queue(*proot->log, 1);
> 
> 	/* Consume data, which was left in the queue from the previous run of
> ```

`left ... from the prev.` -> `stored ... in the prev.`
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 44 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdumBSH-GGH0MJV2Ldq:-MdumBSH-GGH0MJV2Ldr:bj6cmt8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L44)):*
> ```cpp
> 
> 	/* Consume data, which was left in the queue from the previous run of
> 	 * application */
> ```

the application
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 78 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MduniHIEjGADWbDaT8c:-MduniHIEjGADWbDaT8d:b-9k9qwp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L78)):*
> ```cpp
> 			});
> 	}
> 	//! [try_produce_string_view]
> ```

did you check that nested snippets are working flawlessly?
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdunpcT44pJ2rXzUYO4:-MdunpcUEkRhgKV6Fqyd:b-vzkbt0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L79)):*
> ```cpp
> 	}
> 	//! [try_produce_string_view]
> 	/* Porduce data to be consumed in next run of application. */
> ```

`Porduce` misspell
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdunsXA13zvBVx2Jk8V:-MdunsXA13zvBVx2Jk8W:bj6cmt8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L79)):*
> ```cpp
> 	}
> 	//! [try_produce_string_view]
> 	/* Porduce data to be consumed in next run of application. */
> ```

the application
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 3 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5ap-5L8bz_0XduE1:-Mdv5ap-5L8bz_0XduE2:b-ugw5u1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L3)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

pls add `\file` description
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 35 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv41kXBQT_pdCWFpqm:-Mdv41kXBQT_pdCWFpqn:b-mbegys) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L35)):*
> ```cpp
>  * queue.
>  *
>  * In case of crash or shutdown, reading and writing may be continued
> ```

continued from the last position...? pls extend
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 38 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv3wpx340BO1Q3T0HI:-Mdv3wpx340BO1Q3T0HJ:btq1v3m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L38)):*
> ```cpp
>  * by new process, without loss of any, already produced data.
>  *
>  * note: try_consume_batch() MUST be called after restart (otherwise produce
> ```

what for must it be called? pls extend
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 38 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv8_8HDD5b-NUHIJ4X:-Mdv8_8HDD5b-NUHIJ4Y:bxbya24) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L38)):*
> ```cpp
>  * by new process, without loss of any, already produced data.
>  *
>  * note: try_consume_batch() MUST be called after restart (otherwise produce
> ```

after restart of what?
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 101 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5OwY9_YOBMNXIOUE:-Mdv5OwY9_YOBMNXIOUF:b-n2rdob) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L101)):*
> ```cpp
> public:
> 	/**
> 	 * Helper type, which allows to iterate over mpsc_queue's ranges via
> ```

`helper type` doesn't sound well, imho ;)

perhaps write it similar to below: `Type representing...`
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 118 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv4o83-xeWPERpUo9d:-Mdv4o83-xeWPERpUo9e:b7ij9ws) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L118)):*
> ```cpp
> 	/**
> 	 * mpsc_queue producer worker class.
> 	 * note:  All workers should be destroyed before destruction of
> ```

should -> have to
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 121 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5-uyCD7gDnhz5GPE:-Mdv5-uyCD7gDnhz5GPF:bxo1tsh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L121)):*
> ```cpp
> 	 * mpsc_queue
> 	 *
> 	 * see also: mpsc_queue:try_produce_batch()
> ```

Doxygen syntax: `\see MyOtherClass::alloc()`
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 154 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv57g8CQhXRV_3Ueiw:-Mdv57g8CQhXRV_3Ueix:brvd671) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L154)):*
> ```cpp
> 	 * mpsc_queue.
> 	 *
> 	 * Object of this type have to be managed by pmem::obj::pool, to be
> ```

has to be
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 178 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5jpk8E-8HGf6QqMp:-Mdv5jpk8E-8HGf6QqMq:b-jgnu6s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L178)):*
> ```cpp
>  *
>  * @param[in] pmem reference to already allocated  pmem_log_type object
>  * @param[in] max_workers maximum number of workers witch may be used by the
> ```

witch -> which
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 178 at r2](https://reviewable.io/re [...]

2021-07-08 14:24 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: 0 of 4 files reviewed, 30 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, @lukaszstolarczuk, and @throws)

___
*[examples/CMakeLists.txt, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdukzYEAacdgKYClTtz:-Mdw45Mu4HR12F47z-d2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/CMakeLists.txt#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you've missed on level - `/*`
</blockquote></details>

Done.
___
*[examples/mpsc_queue/CMakeLists.txt, line 5 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdqYw9TB9OVpNnlL02k:-Mdr9m4pCLqgwQimIRpA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/CMakeLists.txt#L5)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

inline_string?
</blockquote></details>

Done.
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 39 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdullZB23PuhDipVn7J:-Me5Ukzl9nFiLtAzz46o:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**at** runtime (?)

I'm not sure what you had in mind
</blockquote></details>

Done.
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 43 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdum33N1c0s_M7n0Jwh:-Mdw27MU2YmoAjWhG59d:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`left ... from the prev.` -> `stored ... in the prev.`
</blockquote></details>

Done.
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 44 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdumBSH-GGH0MJV2Ldq:-Mdw2A928QKMX49KG67j:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the application
</blockquote></details>

Done.
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 78 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MduniHIEjGADWbDaT8c:-Mdw2BF2EB11r1pTlt1A:b2nign6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you check that nested snippets are working flawlessly?
</blockquote></details>

yes
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdunpcT44pJ2rXzUYO4:-Mdw2L609EWWM4f_Ec7A:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Porduce` misspell
</blockquote></details>

Done.
___
*[examples/mpsc_queue/mpsc_queue.cpp, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-MdunsXA13zvBVx2Jk8V:-Mdw2MiVBvH1hcJYeXBw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/examples/mpsc_queue/mpsc_queue.cpp#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the application
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 3 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5ap-5L8bz_0XduE1:-Mdw5msX9KaRQjFcH8XV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `\file` description
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 35 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv41kXBQT_pdCWFpqm:-Mdw6Nlq9SdaPVOllV6o:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

continued from the last position...? pls extend
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 38 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv3wpx340BO1Q3T0HI:-Me5QlQ_6s4SgC6zkFCi:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what for must it be called? pls extend
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 38 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv8_8HDD5b-NUHIJ4X:-Me5QkUoE0lgnfz63c6p:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

after restart of what?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 101 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5OwY9_YOBMNXIOUE:-Me5BeeCAIzhJ4OZB6s9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L101)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`helper type` doesn't sound well, imho ;)

perhaps write it similar to below: `Type representing...`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 118 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv4o83-xeWPERpUo9d:-Me5A-inAvvhbiHX5an9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should -> have to
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 121 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5-uyCD7gDnhz5GPE:-Mdw2nF851Mbsc4R-LKV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Doxygen syntax: `\see MyOtherClass::alloc()`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 154 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv57g8CQhXRV_3Ueiw:-Mdw2rrU5pV53UtGoQFG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

has to be
</blockquote></details>

Done.
___ [...]

2021-07-08 16:00 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119)* status: 0 of 4 files reviewed, 30 unresolved discussions (waiting on @igchor, @KFilipek, @lukaszstolarczuk, and @throws)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 178 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv5vM5720iC7bw1yNF:-Me5cwfY4e8ZJkptLxJo:blzctq1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L178)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean `may be used`? if I try to create more than that, then what?
</blockquote></details>

That's tricky ;) as currently there is an assert. 
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 272 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-Mdv66FY5MnFjiijlZcK:-Me5cVu12Yl7Xrtpd-3n:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bbfb3344a3759549e8ee3a31e450ad7e246968bc/include/libpmemobj++/experimental/mpsc_queue.hpp#L272)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in what units?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-08 16:22 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1119#-:-Me5vLiT50_gbyo4YKuC:bnfp4nl)* status: 1 of 4 files reviewed, 27 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-07-09 10:20 UTC, merged