Extend radix_tree tests
pmem/libpmemobj-cpp pull request #1156
Opened 2021-07-13 14:53 UTC by lukaszstolarczuk

- extend existing tests
- cleanup
- add concurrent erase & increment/decrement tests that are failing for the moment

operator--
```
radix_concurrent_erase: ../libpmemobj-cpp/include/libpmemobj++/experimental/radix_tree.hpp:3255: bool pmem::obj::experimental::radix_tree<Key, Value, BytesView, MtMode>::radix_tree_iterator<IsConst>::try_decrement()
[with bool IsConst = false; Key = pmem::obj::experimental::basic_inline_string<char>; Value = pmem::obj::experimental::basic_inline_string<char>; BytesView = pmem::obj::experimental::bytes_view<pmem::obj::experimental::basic_inline_string<char>, void>; bool MtMode = true]:
Assertion `parent_ptr' failed.
```

operator++
```
radix_concurrent_erase: ../libpmemobj-cpp/include/libpmemobj++/experimental/radix_tree.hpp:3177: bool pmem::obj::experimental::radix_tree<Key, Value, BytesView, MtMode>::radix_tree_iterator<IsConst>::try_increment()
[with bool IsConst = false; Key = pmem::obj::experimental::basic_inline_string<char>; Value = pmem::obj::experimental::basic_inline_string<char>; BytesView = pmem::obj::experimental::bytes_view<pmem::obj::experimental::basic_inline_string<char>, void>; bool MtMode = true]:
Assertion `leaf_' failed.
```

2021-07-14 07:56 UTC, igchor requested changes
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3155 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeYzv831KLe9_KPhgeU:-MeYzv831KLe9_KPhgeV:bx9wl1p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/72f7e39fa7ca2eaa80015d984d3dc17efe879313/include/libpmemobj++/experimental/radix_tree.hpp#L3155)):*
> ```cpp
> /*
>  * If MtMode == true it's not safe to use this operator (iterator may end up
>  * invalid if concurrent erase happen).
> ```

Actually, the operator++ should work just fine, there's a problem only with operator--.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 161 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeZ-EqnDB2bIqhOPcyt:-MeZ-EqnDB2bIqhOPcyu:b-2dszxc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/72f7e39fa7ca2eaa80015d984d3dc17efe879313/tests/radix_tree/radix_concurrent_erase.cpp#L161)):*
> ```cpp
> // 								i,
> // 								value_repeats));
> // 					++it;
> ```

The assertion fires here beacuse you are going out of bounds (call ++it on iterator which is already end()). This loops iterates for INITIAL_ELEMENTS times, but the actual number of element in the tree can be less due to the concurrent erases. If you fix this, this test should pass I belive.


<!-- Sent from Reviewable.io -->

2021-07-14 12:29 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3155 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeYzv831KLe9_KPhgeU:-MeZ8JlfEqsNtLJFBwZa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/72f7e39fa7ca2eaa80015d984d3dc17efe879313/include/libpmemobj++/experimental/radix_tree.hpp#L3155)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually, the operator++ should work just fine, there's a problem only with operator--.
</blockquote></details>

Done.
___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 161 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeZ-EqnDB2bIqhOPcyt:-MeZtUPaBya6CEebhoYK:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/72f7e39fa7ca2eaa80015d984d3dc17efe879313/tests/radix_tree/radix_concurrent_erase.cpp#L161)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The assertion fires here beacuse you are going out of bounds (call ++it on iterator which is already end()). This loops iterates for INITIAL_ELEMENTS times, but the actual number of element in the tree can be less due to the concurrent erases. If you fix this, this test should pass I belive.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-14 13:57 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 104 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-Me_IUu1CmZJ3aJSynA3:-Me_IUu1CmZJ3aJSynA4:b7o0bi5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fc9d5d9a93230723e7387502b5b892c7c9f8958e/tests/radix_tree/radix_concurrent_erase.cpp#L104)):*
> ```cpp
> //								i,
> //								value_repeats));
> //					--it;
> ```

I think that this test has the same problem as the one for operator++ (that is, if we fix operator--, this test will still fail). 


<!-- Sent from Reviewable.io -->

2021-07-14 17:03 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 104 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-Me_IUu1CmZJ3aJSynA3:-Me_xzF5BS81hi_VPgoC:b9acjnf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fc9d5d9a93230723e7387502b5b892c7c9f8958e/tests/radix_tree/radix_concurrent_erase.cpp#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that this test has the same problem as the one for operator++ (that is, if we fix operator--, this test will still fail). 
</blockquote></details>

right now it.. works - I run this in the loop and it didn't fail... so I guess, something is wrong...?


<!-- Sent from Reviewable.io -->

2021-07-15 07:02 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 104 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-Me_IUu1CmZJ3aJSynA3:-MecxJz5BKl8fiW9CLBc:b-bndl87) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fc9d5d9a93230723e7387502b5b892c7c9f8958e/tests/radix_tree/radix_concurrent_erase.cpp#L104)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

right now it.. works - I run this in the loop and it didn't fail... so I guess, something is wrong...?
</blockquote></details>

Well, operator-- will fail only in some specific cases, e.g.:
- try_decrement fails due to concurrent erase (it can be the element pointed to by the iterator)
- operator-- calls lower_boud which returns end() (the tree is now empty)
- try_decrement crashes because we decerement beyond begin()

So, one idea for a test would be to just have a single element in the tree and in one thread call find() and then operator--, in another thread, just remove this element. Probably this should be done in a loop.


<!-- Sent from Reviewable.io -->

2021-07-15 09:09 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[tests/radix_tree/radix_concurrent_erase.cpp, line 104 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-Me_IUu1CmZJ3aJSynA3:-MedQNjG4P7kxN2DqQxu:b-q67vbm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fc9d5d9a93230723e7387502b5b892c7c9f8958e/tests/radix_tree/radix_concurrent_erase.cpp#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Well, operator-- will fail only in some specific cases, e.g.:
- try_decrement fails due to concurrent erase (it can be the element pointed to by the iterator)
- operator-- calls lower_boud which returns end() (the tree is now empty)
- try_decrement crashes because we decerement beyond begin()

So, one idea for a test would be to just have a single element in the tree and in one thread call find() and then operator--, in another thread, just remove this element. Probably this should be done in a loop.

</blockquote></details>

I've done it a bit differently with random removals - now it fails randomly


<!-- Sent from Reviewable.io -->

2021-07-15 09:24 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-:-MedTtHaB-wM277556Oz:bnfp4nl)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-07-15 11:00 UTC, lukaszstolarczuk reviewed
as discussed I switched implementation, to disable `operator--` when MtMode is enabled

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-:-MedoeNi0jzjyn5zxniy:bgbjdo4)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-07-15 11:31 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-:-MedvsjBCnIKRfMCEBkI:bnfp4nl)* status: 3 of 9 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-07-16 07:23 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 249 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeiBCvT1drbXOZHANil:-MeiBCvUCovW5eaSnHPx:b-ak5evo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/75d04ac846b57f36dc95025eb047968a7f22f961/tests/radix_tree/radix_concurrent_iterate.cpp#L249)):*
> ```cpp
> 		middle_key.end());
> 
> 	auto last = std::next(ptr->begin(), static_cast<int>(ptr->size() - 1));
> ```

I'm not sure if this is exactly what we wanted here? Will the find & erase (below) do the job as we wanted?


<!-- Sent from Reviewable.io -->

2021-07-16 07:35 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-:-MeiEIpW15RO49QIJ7_r:bnfp4nl)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/radix_tree/radix_concurrent_iterate.cpp, line 249 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1156#-MeiBCvT1drbXOZHANil:-MeiDvS9-xfSKpx-rbkJ:b-xz3jjp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/75d04ac846b57f36dc95025eb047968a7f22f961/tests/radix_tree/radix_concurrent_iterate.cpp#L249)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if this is exactly what we wanted here? Will the find & erase (below) do the job as we wanted?
</blockquote></details>

Yes, I think it's the same.


<!-- Sent from Reviewable.io -->

2021-07-16 10:56 UTC, merged