docs: update and extend containers information
pmem/libpmemobj-cpp pull request #1201
Opened 2021-09-16 17:28 UTC by lukaszstolarczuk

- add Containers group/feature descriptions,
- fix misspells,
- add some missing Doxygen comments,
- update basic containers' descriptions.

// Before:
https://pmem.io/libpmemobj-cpp/master/doxygen/modules.html
// After:
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/modules.html

2021-09-17 08:39 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-:-MjmuHEp4jsG9wUNtmDg:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-09-17 09:11 UTC, KFilipek requested changes
> Reviewed 12 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxjdY3Y-9SRnyzxUQ:-MjmxjdY3Y-9SRnyzxUR:b2kvqsq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L8)):*
> ```
>   *
>   * Persistent containers are implemented-from-scratch with optimized on-media layouts
>   * and algorithms to fully exploit the potential and features of persistent memory
> ```

missing dot
___
*[doc/groups_definitions.dox, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxvqC-fhLHlZeILVI:-MjmxvqC-fhLHlZeILVJ:b-gudn01) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L9)):*
> ```
>   * Persistent containers are implemented-from-scratch with optimized on-media layouts
>   * and algorithms to fully exploit the potential and features of persistent memory
>   * These methods guarantee atomicity, consistency and durability. Besides specific
> ```

If this methods also guarantee isolation we can mention about ACID acronym in this place, before you roll out this.
___
*[doc/groups_definitions.dox, line 13 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmyjxkC32uSGB_3FdB:-MjmyjxkC32uSGB_3FdC:bt1209t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L13)):*
> ```
> group/"feature"
> ```
One of those should leave
___
*[doc/groups_definitions.dox, line 53 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmweZc49pUyCuQHPh7:-MjmweZdAGuM6DKFebAu:bwxlcn8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L53)):*
> ```
> still
> ```
are still?
___
*[doc/groups_definitions.dox, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjmx9E5DsxtFDZNz767:-Mjmx9E5DsxtFDZNz768:b-owa2k1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L55)):*
> ```
> It's very important to note:
> ```
This should be removed. @note annotation gives a big highlight with "note" label on the left:
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/group__experimental__containers.html
___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1616 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjn-gqB6JZqbbwHvDvO:-Mjn-gqB6JZqbbwHvDvP:b-98zy0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/container/concurrent_hash_map.hpp#L1616)):*
> ```
> @note Testing note:
> ```
Inverted case: under "Note" we have "Testing note:".
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1concurrent__hash__map.html#details


<!-- Sent from Reviewable.io -->

2021-09-17 12:18 UTC, karczex commented
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjng26q8IyyJ6dYbDeG:-Mjng26q8IyyJ6dYbDeH:bwic4yb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/experimental/concurrent_map.hpp#L24)):*
> ```
>  * Persistent memory aware implementation of Intel TBB concurrent_map with
>  * API partially compatible to std::map.
> ```
I looked at the preview, and this should link to tbb instead of libpmemobj concurrent_map 
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1experimental_1_1concurrent__map.html


<!-- Sent from Reviewable.io -->

2021-09-17 12:19 UTC, karczex commented
___
*[include/libpmemobj++/detail/ebr.hpp, line 65 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjnex9V-An99WzNFwdx:-Mjnex9V-An99WzNFwdy:b-ia6xdi) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/detail/ebr.hpp#L65)):*
> ```cpp
>  * epochs are needed (e, e-1 and e-2), therefore we use clock arithmetic.
>  *
>  * Reference:
> ```

Shouldn't it be /ref? 


<!-- Sent from Reviewable.io -->

2021-09-17 14:59 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 11 of 15 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[doc/groups_definitions.dox, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxjdY3Y-9SRnyzxUQ:-Mjo2I_01l1xHsdMY3sO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L8)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing dot
</blockquote></details>

Done.
___
*[doc/groups_definitions.dox, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxvqC-fhLHlZeILVI:-Mjo2d1U-vUh-GnCILub:bu2y899) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L9)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If this methods also guarantee isolation we can mention about ACID acronym in this place, before you roll out this.
</blockquote></details>

I'm not sure if that's true for all methods...

and what do you mean by "before you roll out this"?
___
*[doc/groups_definitions.dox, line 13 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmyjxkC32uSGB_3FdB:-Mjo2mzF2mkY8uUNVw3n:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L13)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> group/"feature"
> ```
One of those should leave
</blockquote></details>

Done.
___
*[doc/groups_definitions.dox, line 53 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmweZc49pUyCuQHPh7:-Mjo37Or9De-gEwkUD3m:b-il9wt2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L53)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> still
> ```
are still?
</blockquote></details>

I guess it was correct, but on the second thought - it wasn't required.
___
*[doc/groups_definitions.dox, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjmx9E5DsxtFDZNz767:-Mjo3J6T878lPCeJoqFO:bp7adp4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L55)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> It's very important to note:
> ```
This should be removed. @note annotation gives a big highlight with "note" label on the left:
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/group__experimental__containers.html
</blockquote></details>

I know, I just believed (and still do) it's really important to underline this. I might be biased since I wrote this.
I rephrased it a bit, though - please let me know if you'd still remove this.
___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1616 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjn-gqB6JZqbbwHvDvO:-Mjo4cGXEX85AY-lV1NG:b8vtz2k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/container/concurrent_hash_map.hpp#L1616)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> @note Testing note:
> ```
Inverted case: under "Note" we have "Testing note:".
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1concurrent__hash__map.html#details
</blockquote></details>

hah, true, thx - rephrased it.
___
*[include/libpmemobj++/detail/ebr.hpp, line 65 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjnex9V-An99WzNFwdx:-Mjo6wIp6KL0oAE8rQjt:b-s4vfwu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/detail/ebr.hpp#L65)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Shouldn't it be /ref? 
</blockquote></details>

`\ref` is used to link to another named section, if I understand correctly, but I've made something more user friendly here, I hope
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjng26q8IyyJ6dYbDeG:-Mjo765h0gDmFuemB942:b-iu89o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/experimental/concurrent_map.hpp#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
>  * Persistent memory aware implementation of Intel TBB concurrent_map with
>  * API partially compatible to std::map.
> ```
I looked at the preview, and this should link to tbb instead of libpmemobj concurrent_map 
https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1experimental_1_1concurrent__map.html
</blockquote></details>

hah, yeah, that's tricky - the keywords are automatically replaced by a link to docs, so sometimes there's a weird loop to itself... nonetheless I fixed this one.


<!-- Sent from Reviewable.io -->

2021-09-20 08:40 UTC, karczex requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjng26q8IyyJ6dYbDeG:-Mk1LHmAAQK1hRPiHmpt:bwrqf5s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/experimental/concurrent_map.hpp#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, yeah, that's tricky - the keywords are automatically replaced by a link to docs, so sometimes there's a weird loop to itself... nonetheless I fixed this one.
</blockquote></details>

Since 1.8.0 Doxygen supports markdown syntax. 
I've tried it, and it looks much better in the source file, while generated link still points to TBB documentation. (tested on doxygen 1.8.17)

https://www.doxygen.nl/manual/markdown.html


<!-- Sent from Reviewable.io -->

2021-09-20 12:29 UTC, igchor reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxvqC-fhLHlZeILVI:-Mk29nJ47Hj5vrYVPVTm:b-3my2e7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if that's true for all methods...

and what do you mean by "before you roll out this"?
</blockquote></details>

There is no isoloation by default for STL-like data structures. 

What does "these" refer to? I would suggest to add some more info here, e.g. write about modifier/access methods, like here: https://pmem.io/2019/02/20/cpp-vector.html


<!-- Sent from Reviewable.io -->

2021-09-20 12:37 UTC, KFilipek approved these changes
> Reviewed 1 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjmx9E5DsxtFDZNz767:-Mk21N-TCvu4RCt3axSv:b-ci493b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know, I just believed (and still do) it's really important to underline this. I might be biased since I wrote this.
I rephrased it a bit, though - please let me know if you'd still remove this.
</blockquote></details>

Now looks better, thanks :) 


<!-- Sent from Reviewable.io -->

2021-09-21 11:03 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[doc/groups_definitions.dox, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MjmxvqC-fhLHlZeILVI:-Mk705wc-U6OFLZ7HtYa:b-hjaam0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/doc/groups_definitions.dox#L9)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There is no isoloation by default for STL-like data structures. 

What does "these" refer to? I would suggest to add some more info here, e.g. write about modifier/access methods, like here: https://pmem.io/2019/02/20/cpp-vector.html
</blockquote></details>

I believe these sentences were copied from our README file (which was probably written by you :smile: ) - I think they were about our accessors/modifiers methods. I've added the additional sentence about modifiers from the blog post.
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-Mjng26q8IyyJ6dYbDeG:-Mk70VekDRt68Sdf7cg6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d3c3a27982817f024aa39132f4249073501eb4d7/include/libpmemobj++/experimental/concurrent_map.hpp#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Since 1.8.0 Doxygen supports markdown syntax. 
I've tried it, and it looks much better in the source file, while generated link still points to TBB documentation. (tested on doxygen 1.8.17)

https://www.doxygen.nl/manual/markdown.html
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-22 07:36 UTC, karczex approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-:-MkBQgyQE2QboavQEq4K:bnfp4nl)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-09-23 09:03 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

___
*[doc/groups_definitions.dox, line 15 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MkGtGKMEnOv2VgMaTl4:-MkGtGKMEnOv2VgMaTl5:b-z0g9iu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/35a86c8f463bcbff7ac24a2750af679f4d5aa1b9/doc/groups_definitions.dox#L15)):*
> ```
>   * and guarantees full exception safety (modifications will be either committed or
>   * rolled-back if an exception was thrown, or crash happened). There is no need
>   * for using transaction when calling modifier methods whatsoever.
> ```

Myabe also a short description what is a modifier (method which modifes state of the  container itself, like resize, push_back, etc.)?


<!-- Sent from Reviewable.io -->

2021-09-23 09:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

___
*[doc/groups_definitions.dox, line 15 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-MkGtGKMEnOv2VgMaTl4:-MkGy6AX7jYQlr4ZNOcX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/35a86c8f463bcbff7ac24a2750af679f4d5aa1b9/doc/groups_definitions.dox#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Myabe also a short description what is a modifier (method which modifes state of the  container itself, like resize, push_back, etc.)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-23 10:07 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1201#-:-MkH714R40ftzBVGoP2q:bnfp4nl)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)



<!-- Sent from Reviewable.io -->

2021-09-23 11:18 UTC, merged