std::atomic specialization for self_relative_pointer
pmem/libpmemobj-cpp pull request #835
Opened 2020-08-14 10:06 UTC by avdosev

2020-08-19 08:54 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 11 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 69 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEvK-BVAkX3avWtZYPc:-MF4uHs3DVTnzRSFLiLs:b-uxu3j) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dfc9717e8e1c1d34820edaf293b173fa043a3ace/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

1. Yes, but in my opinion std::atomic<pmem_whathever> should not be transnational at all.
2.1. + 3. Agree, that's why maybe we could have atomic_self_relative_ptr class instead of std::atomic specialization? Like https://en.cppreference.com/w/cpp/experimental/atomic_shared_ptr

So, I see two solutions:
1. Create atomic_self_relative_ptr and disallow from using inside tx + add some function for singlethreded tx modifications
2. Stay with std::atomic<self_relative_ptr> and do not snapshot the data (but also do not throw exceptions).

I'm not really sure which solution is better, disallowing using this class within transaction even for single threaded workloads is quite limiting (for example, in concurrent_hash_map/skip_list to implement swap() we have to snapshot and modify the pointers but the swap method itself can only be called in a single threaded workload so it's fine). So I think I would prefer the second solution. (in that case, in the swap() method we can just manually snapshot the variable).

Maybe @szyrom or @pbalcer have some other ideas?
</blockquote></details>

I am not sure that we should check everything on the code level developers also should understand what they do. Like with multi-threaded programming we cannot catch all issues on the code level and throw an exception in case of possible data race. Actually, pmemcheck is able to find the issue when several concurrent transactions snapshot the same memory.
As for the ```atomic_shared_ptr```, it was experimental feature which evolved to ```std::atomic<shared_ptr<T>>```.


<!-- Sent from Reviewable.io -->

2020-08-19 08:57 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 10 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 245 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEwVCbRAFvcPAsuC5XL:-MF4vvu347dWNJjdeCd-:bwefi6q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/44c305c46cf12fb9376754414910e80514bbbde5/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L245)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should it be ```sizeof(atomic_node_pointer)```. To make it generic I suggest the following ```sizeof(nexts[0])```.
</blockquote></details>

To make it generic I suggest the following: ```sizeof(nexts[0])```


<!-- Sent from Reviewable.io -->

2020-08-19 08:57 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 69 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEvK-BVAkX3avWtZYPc:-MF4vvCFDZa1RE1uIxUR:b-jcwjqv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dfc9717e8e1c1d34820edaf293b173fa043a3ace/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L69)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I am not sure that we should check everything on the code level developers also should understand what they do. Like with multi-threaded programming we cannot catch all issues on the code level and throw an exception in case of possible data race. Actually, pmemcheck is able to find the issue when several concurrent transactions snapshot the same memory.
As for the ```atomic_shared_ptr```, it was experimental feature which evolved to ```std::atomic<shared_ptr<T>>```.
</blockquote></details>

Ok, so, do we agree on solution 2?


<!-- Sent from Reviewable.io -->

2020-08-19 09:05 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 69 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEvK-BVAkX3avWtZYPc:-MF4w5Uu8o-gQZHuMaFR:b-8dk2qu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dfc9717e8e1c1d34820edaf293b173fa043a3ace/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L69)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, so, do we agree on solution 2?
</blockquote></details>

I agree that we should not throw an exception. Regarding "do not snapshot" I am not sure... because, as you said:
1. We do not see a use case when atomic is updated inside the concurrent transactions.
2. In case of single-threaded functions (like swap) atomic should be snapshotted.

For me it sounds like: if atomic is updated inside a transaction then it is a single-threaded or isolated transaction and atomic should be tracked by the transaction; and if atomic is updated concurrently it happens outside of any transaction. Otherwise, the pmemcheck should identify the issue.

So maybe we should the current version as is.

BTW, I am not pushing you... just brainstorming. Maybe we can discuss it today during sync-up


<!-- Sent from Reviewable.io -->

2020-08-19 09:08 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 143 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEvvDJCEytX9gEkvcLo:-MF4vs2a0Yhea9LQoLXL:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/44c305c46cf12fb9376754414910e80514bbbde5/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L143)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEvz6UF4x614UVD-p2H:-MF4w3RzBdK3M90Oxq7o:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/44c305c46cf12fb9376754414910e80514bbbde5/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

are those const_casts really necessary?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 39 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0G3D91LAziDNAvBoW:-MF4w-Rk8Iqjo8FyE2fn:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/896633b9c8077e1c14740a9f29e9be1584575f23/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L39)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if I understand this comment. It is not really equal to std::atomic<T*>.  I think the first sentence is enough.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 253 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0Eobu0RVQIa2hNvgx:-MF4yU_HDbPuA4QJb2-0:bsmltcg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/896633b9c8077e1c14740a9f29e9be1584575f23/include/libpmemobj++/experimental/self_relative_ptr.hpp#L253)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why we are not doing this in the base class?
</blockquote></details>

In the process of implementation, I thought it would be better, but then I refused it.
___
*[tests/CMakeLists.txt, line 247 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF-qMxe4YXSX16bD5xq:-MF4w8Xv60-chLLrSaV9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/312a3121b2c6b82b72f3c9572d2271b8d378b7f8/tests/CMakeLists.txt#L247)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please add also helgrind
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-19 09:24 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 1 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 245 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MEwVCbRAFvcPAsuC5XL:-MF512Mb3H7aB1KDlR-l:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/44c305c46cf12fb9376754414910e80514bbbde5/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L245)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

To make it generic I suggest the following: ```sizeof(nexts[0])```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-19 09:24 UTC, vinser52 reviewed
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)



<!-- Sent from Reviewable.io -->

2020-08-19 09:51 UTC, igchor requested changes
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF4xTDa5iIzyAspf0Zs:-MF4xTDa5iIzyAspf0Zt:b-cr0pj1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bad77bc665b2e1fa1087dbc6e6ff46e7c00ab735/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
> ```cpp
> 	 */
> 	void *
> 	to_void_pointer_by_offset(difference_type other_offset) const
> ```

why this is not called 'offset_to_pointer' ?
___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 253 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0Eobu0RVQIa2hNvgx:-MF4wodZ70wK7lIjGIjR:b-t5yqkw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/896633b9c8077e1c14740a9f29e9be1584575f23/include/libpmemobj++/experimental/self_relative_ptr.hpp#L253)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why we are not doing this in the base class?
</blockquote></details>

There also a missing self-asignment check here. Can't we just call `return base_type::operator=()`?
___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.hpp, line 225 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF4wxSnEBrNrtRrPcfP:-MF4wxSnEBrNrtRrPcfQ:b-dlbtw4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bad77bc665b2e1fa1087dbc6e6ff46e7c00ab735/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.hpp#L225)):*
> ```cpp
> 	test_exchange<volatile_atomic>();
> 	test_compare_exchange<volatile_atomic>();
> }
> ```

please add newline here


<!-- Sent from Reviewable.io -->

2020-08-19 09:55 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF-sA-R9LaGSbS5c4yx:-MF577i918ISvKG-Ap81:b4eluty) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/312a3121b2c6b82b72f3c9572d2271b8d378b7f8/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, this test basivally checks if there is no intermidiate value (it's either first or last), right? In that case maybe it would make sense to make first and second differ on each byte? (0 vs 0xffffffff)
</blockquote></details>

`before` is a local copy of std :: atomic <relative pointer> with a local offset from self position. This offset cannot be controlled.


<!-- Sent from Reviewable.io -->

2020-08-19 10:07 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 253 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0Eobu0RVQIa2hNvgx:-MF58xQp7pJmtTg-GAny:b-njkp4u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/896633b9c8077e1c14740a9f29e9be1584575f23/include/libpmemobj++/experimental/self_relative_ptr.hpp#L253)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There also a missing self-asignment check here. Can't we just call `return base_type::operator=()`?
</blockquote></details>

This check is done in the base class.
`return base_type::operator=()` can`t be returned because `base_type::operator=()` return `base_type&`. `base_type&` need cast to `self_relative_ptr&`


<!-- Sent from Reviewable.io -->

2020-08-19 10:09 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 253 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0Eobu0RVQIa2hNvgx:-MF5BAfB1wD1E_bSPxQn:b-9oqy5u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/896633b9c8077e1c14740a9f29e9be1584575f23/include/libpmemobj++/experimental/self_relative_ptr.hpp#L253)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

This check is done in the base class.
`return base_type::operator=()` can`t be returned because `base_type::operator=()` return `base_type&`. `base_type&` need cast to `self_relative_ptr&`

</blockquote></details>

But you will unnecessarily snapshot the pointer. But this is maybe not a big problem


<!-- Sent from Reviewable.io -->

2020-08-19 10:10 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 2 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF-sA-R9LaGSbS5c4yx:-MF5BWH27iHb4NlgyAoK:b-2kq1ct) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/312a3121b2c6b82b72f3c9572d2271b8d378b7f8/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp#L77)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

`before` is a local copy of std :: atomic <relative pointer> with a local offset from self position. This offset cannot be controlled.
</blockquote></details>

I know, I was watling about first and last.


<!-- Sent from Reviewable.io -->

2020-08-19 10:33 UTC, vinser52 reviewed
> Reviewed 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)



<!-- Sent from Reviewable.io -->

2020-08-19 10:39 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF4xTDa5iIzyAspf0Zs:-MF5BGC36CqciA6pB_UQ:b-gcqizj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bad77bc665b2e1fa1087dbc6e6ff46e7c00ab735/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why this is not called 'offset_to_pointer' ?
</blockquote></details>

That's a good idea. I renamed this method.
___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.hpp, line 225 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF4wxSnEBrNrtRrPcfP:-MF5HaR31Jw8HRLFJNPR:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bad77bc665b2e1fa1087dbc6e6ff46e7c00ab735/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.hpp#L225)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please add newline here
</blockquote></details>

Done.
___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF-sA-R9LaGSbS5c4yx:-MF5HVDn-zALNnRbB2hm:b7zb147) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/312a3121b2c6b82b72f3c9572d2271b8d378b7f8/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp#L77)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I know, I was watling about first and last.
</blockquote></details>

hm, i do that


<!-- Sent from Reviewable.io -->

2020-08-19 10:49 UTC, igchor requested changes
> Reviewed 2 of 7 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 46 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5G66aCgVUQ_2IDyE7:-MF5G66b95lTBQul1YZ6:b-85cxei) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L46)):*
> ```cpp
> 	using byte_type = uint8_t;
> 	using byte_ptr_type = byte_type *;
> 	using const_byte_ptr_type = const volatile byte_type *;
> ```

why volatile?
___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 255 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5GPxl4F0tSd3zlDil:-MF5GPxl4F0tSd3zlDim:b-deqiuo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L255)):*
> ```cpp
> 			reinterpret_cast<const_byte_ptr_type>(&ptr) -
> 			reinterpret_cast<const_byte_ptr_type>(this);
> 		distance_between_self &= static_cast<difference_type>(mask);
> ```

Hm, I'm not sure if it's safe to use bitwise operations on signed type. Imo it would be better to cast distance_between_self to uinptr_t, mask the value and convert the result to difference_type.

Btw, do you mask signed values anywhere else?


<!-- Sent from Reviewable.io -->

2020-08-19 10:51 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5L-QmDXTSaDUzULJM:-MF5L-QmDXTSaDUzULJN:bvf3w75) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46ddc36a5b0ee848bb997228f94ad0e2b37dfa48/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
> ```cpp
> 	 */
> 	void *
> 	offset_to_pointer(difference_type other_offset) const volatile noexcept
> ```

Hm, I'm not sure if marking this function as volatile is the best idea. I think it can limit the optimizations.


<!-- Sent from Reviewable.io -->

2020-08-19 11:23 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 255 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5GPxl4F0tSd3zlDil:-MF5OE810x1I3_4aINHj:ba9z3ug) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L255)):*
> Btw, do you mask signed values anywhere else?
No, that's the only use.

I don't think the result will change. Because only 0x00000000 and 0xFFFFFFFF are used.
___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5L-QmDXTSaDUzULJM:-MF5O3835ng5h5CZrlcJ:bsoeau) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46ddc36a5b0ee848bb997228f94ad0e2b37dfa48/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I'm not sure if marking this function as volatile is the best idea. I think it can limit the optimizations.
</blockquote></details>

I think the compiler has no limits for optimizations, because we use non-volatile other_offset and don't use volatile offset


<!-- Sent from Reviewable.io -->

2020-08-19 12:01 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 255 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5GPxl4F0tSd3zlDil:-MF5_rCj0cDALqnk8A8d:b-7z5igy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L255)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

> Btw, do you mask signed values anywhere else?
No, that's the only use.

I don't think the result will change. Because only 0x00000000 and 0xFFFFFFFF are used.
</blockquote></details>

You're probably right but I still fear this might be implementation sepcific: https://stackoverflow.com/questions/11644362/are-the-results-of-bitwise-operations-on-signed-integers-defined Whether it;s 0xFFFFFFFF or not is determined by whether we're using two's complement or not. I believe it could be more generic to use unsigned values always.
___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5L-QmDXTSaDUzULJM:-MF5ZgJr2TXR9rIfEKP1:b-qz6ozf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46ddc36a5b0ee848bb997228f94ad0e2b37dfa48/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

I think the compiler has no limits for optimizations, because we use non-volatile other_offset and don't use volatile offset
</blockquote></details>

But the function itself is volatile - it means that the entire self_relative_ptr will be treated as volatile: https://stackoverflow.com/questions/4826719/c-volatile-member-functions
___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF-sA-R9LaGSbS5c4yx:-MF5_7UcCdOiqvpI6OuR:b-z3stf4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/312a3121b2c6b82b72f3c9572d2271b8d378b7f8/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp#L77)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

hm, i do that
</blockquote></details>

Ok but nvm, you were right ;d


<!-- Sent from Reviewable.io -->

2020-08-19 13:03 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @avdosev, @igchor, @pbalcer, @szyrom, and @vinser52)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 255 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5GPxl4F0tSd3zlDil:-MF5o6Re4Y-lpZp0CuEk:b56prkz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L255)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You're probably right but I still fear this might be implementation sepcific: https://stackoverflow.com/questions/11644362/are-the-results-of-bitwise-operations-on-signed-integers-defined Whether it;s 0xFFFFFFFF or not is determined by whether we're using two's complement or not. I believe it could be more generic to use unsigned values always.
</blockquote></details>

I think we can simply use reinterpret_cast instead of static_cast when converting the mask. In that case bit representation of the mask would not be changed.


<!-- Sent from Reviewable.io -->

2020-08-20 08:46 UTC, igchor reviewed
> Reviewed 1 of 7 files at r5, 1 of 7 files at r7, 1 of 2 files at r8, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: all files reviewed, 6 unresolved discussions (waiting on @avdosev)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 255 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5GPxl4F0tSd3zlDil:-MFA-ZZs3aomRTBNIV-v:b-m6cio4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b6b3227bdbbb54df9866434eb3e34d582cee00cf/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L255)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I think we can simply use reinterpret_cast instead of static_cast when converting the mask. In that case bit representation of the mask would not be changed.
</blockquote></details>

Ok, I think you're right. It should be fine in that case.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 40 at r11](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFA1rLZ3PDYrm7EW8Mv:-MFA1rLZ3PDYrm7EW8Mw:b-pp4nzu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/abbeb420b534fe2599abe862d7d0d10a821b31d6/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L40)):*
> ```cpp
>  * Atomic specialization for self_relative_ptr
>  *
>  * Doesn't automatically add itself to the transaction
> ```

I would also say that the user is responsible for persisting the data.


<!-- Sent from Reviewable.io -->

2020-08-20 10:26 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: all files reviewed, 6 unresolved discussions (waiting on @avdosev and @igchor)

___
*[include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp, line 209 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF5L-QmDXTSaDUzULJM:-MF9wG0B6yb2z6kiez6h:bnptxob) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46ddc36a5b0ee848bb997228f94ad0e2b37dfa48/include/libpmemobj++/detail/self_relative_ptr_base_impl.hpp#L209)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, even if the optimizations are allowed for this function, I see some other which are marked volatile and could decrease performance.
</blockquote></details>

Marking a member function volatile is like marking it const; it means that the receiver object is treated as though it were declared as a volatile T *. Consequentially, any reference to offset will be treated as a volatile read in the member function. Moreover, a volatile object can only call volatile member functions. But i don`t use volatile offset. I am use non-volatile function argument which does not limit compiler optimizations. Rather, you are confused by the use of this, but its use does not limit the optimization in any way, since it is of type const volatile * this_type const, that is, it is a constant pointer that points to volatile data, and not a volatile pointer. Since I am not dereferencing this pointer, the compiler is not limited in optimization.


<!-- Sent from Reviewable.io -->

2020-08-20 12:22 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @avdosev, @igchor, and @vinser52)

___
*[tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp, line 205 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MF0jyK2Ei8Z8_zKqkUx:-MFAoRSt1LdIc2HGZNV3:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe7dc70ea8513ee3a9878f8da0f04f818572977/tests/self_relative_ptr_atomic/self_relative_ptr_atomic.cpp#L205)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I think it should be a separate function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-24 08:54 UTC, igchor requested changes
> Reviewed 2 of 3 files at r15, 1 of 1 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @avdosev and @vinser52)

___
*[include/libpmemobj++/transaction.hpp, line 476 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUddh_92s5Ws649Yva:-MFUddha53T_BKOIZ5Oq:bdfn8zc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/transaction.hpp#L476)):*
> ```cpp
> 	 * supplied block of memory has to be within the pool registered in the
> 	 * transaction. This function must be called during transaction. This
> 	 * overload only participates in overload resolution of function
> ```

This comment should be updated probably.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 189 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUebMn7SgG8JrpFUdf:-MFUebMn7SgG8JrpFUdg:bwbevgf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L189)):*
> ```cpp
> 
> 	bool
> 	is_lock_free() const noexcept
> ```

I'm wondering if we should even expose is_locK_free and is_always_lock_free in atomic_self_relative_ptr. Maybe instead we should just assert/throw exception in ctors if the underlying std::atomic<offset> is not lock free? Because if it not not lock free than we end up storing some locks on pmem which are not reinitialized on restart. What do you think @vinser52 ?


<!-- Sent from Reviewable.io -->

2020-08-24 09:08 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @avdosev and @vinser52)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 189 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUebMn7SgG8JrpFUdf:-MFUhMk26PoJzLHBMDB7:b-s58hpu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L189)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm wondering if we should even expose is_locK_free and is_always_lock_free in atomic_self_relative_ptr. Maybe instead we should just assert/throw exception in ctors if the underlying std::atomic<offset> is not lock free? Because if it not not lock free than we end up storing some locks on pmem which are not reinitialized on restart. What do you think @vinser52 ?
</blockquote></details>

I think what you described is the implementation details. I can imagine alternative lock-based implementation which is suitable for pmem. It could be the following:
1. On pmem we store the non-atomic self_relative_ptr.
2. On DRAM we store the map where the key is the address of the self_relative_ptr and the value is the corresponding mutex.
3. The map on DRAM is lazy-initialized on each process restart. 

In that case the atomic specialization is lock-based. I am not talking if it is optimal or not, just for illustration.
But I think we should have these interface methods and internally we have an assert for our current implementation


<!-- Sent from Reviewable.io -->

2020-08-24 09:09 UTC, vinser52 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-:-MFUidTo6HDNuwC6tc4q:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @avdosev and @vinser52)



<!-- Sent from Reviewable.io -->

2020-08-24 09:09 UTC, vinser52 reviewed
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: all files reviewed, 1 unresolved discussion (waiting on @avdosev)



<!-- Sent from Reviewable.io -->

2020-08-24 11:20 UTC, avdosev reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @igchor and @vinser52)

___
*[include/libpmemobj++/transaction.hpp, line 476 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUddh_92s5Ws649Yva:-MFVBUBW9xxofUEddE0p:b-wt370b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/transaction.hpp#L476)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This comment should be updated probably.
</blockquote></details>

Is that what you meant?


<!-- Sent from Reviewable.io -->

2020-08-24 12:21 UTC, vinser52 reviewed
> Reviewed 3 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-08-25 09:08 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: all files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[include/libpmemobj++/transaction.hpp, line 476 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUddh_92s5Ws649Yva:-MFZpay61Sesyrxi_C3H:b2nhswy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/transaction.hpp#L476)):*
<details><summary><i>Previously, avdosev wrote…</i></summary><blockquote>

Is that what you meant?
</blockquote></details>

Yes
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 189 at r17](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-MFUebMn7SgG8JrpFUdf:-MFZpml0552p_iQMe38g:b-khhklp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4dd817391f7fba7b16f38c49ce6613ac606e5aab/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L189)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I think what you described is the implementation details. I can imagine alternative lock-based implementation which is suitable for pmem. It could be the following:
1. On pmem we store the non-atomic self_relative_ptr.
2. On DRAM we store the map where the key is the address of the self_relative_ptr and the value is the corresponding mutex.
3. The map on DRAM is lazy-initialized on each process restart. 

In that case the atomic specialization is lock-based. I am not talking if it is optimal or not, just for illustration.
But I think we should have these interface methods and internally we have an assert for our current implementation
</blockquote></details>

Ok, I see.  But shouldn;t we add asserts for std::atomic<offset>::is_lock_free for now? If we would have our own lock-based implementation then that's fine but if std::atomic<offset> is lock-based then it will be problematic.


<!-- Sent from Reviewable.io -->

2020-08-25 09:46 UTC, vinser52 reviewed
> Reviewed 2 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 09:47 UTC, vinser52 reviewed
> Reviewed 1 of 7 files at r7, 2 of 3 files at r15, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 09:48 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835#-:-MF_03zG0LOwndKekXC9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 09:50 UTC, igchor approved these changes
> Reviewed 2 of 4 files at r14, 2 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 10:40 UTC, vinser52 reviewed
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/835)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @igchor and @vinser52)



<!-- Sent from Reviewable.io -->

2020-08-25 11:43 UTC, merged