Radix tree improvements
pmem/libpmemobj-cpp pull request #838
Opened 2020-08-19 14:22 UTC by igchor

Closes #828

2020-08-19 14:29 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 0 of 10 files reviewed, all discussions resolved

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF65uLh4I2uYkUPg9xM:b-cwmko5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
> ```cpp
> 
> 		/* it is still valid */
> 		assert(pmem::obj::string_view(it->value()).compare("some long string") == 0);
> ```

Here, it is updated to point to the new node if relocation happens. But if it is done in a transaction and the transaction aborts, it will be invalid (the pointer in iterator will not be rolled back).

I was thinking whether we should use callbacks to also restore this pointer (it would be registered after the ptr modification in radix_tree.hpp:2029). @szyrom @pbalcer @vinser52 do you see any problems with a callback approach?


<!-- Sent from Reviewable.io -->

2020-08-19 14:30 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 0 of 10 files reviewed, all discussions resolved

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF6710ZDBSEvVp6r-pq:b8ap5m2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Here, it is updated to point to the new node if relocation happens. But if it is done in a transaction and the transaction aborts, it will be invalid (the pointer in iterator will not be rolled back).

I was thinking whether we should use callbacks to also restore this pointer (it would be registered after the ptr modification in radix_tree.hpp:2029). @szyrom @pbalcer @vinser52 do you see any problems with a callback approach?
</blockquote></details>

Of course I mean transactional callbacks callbacks (explicitly a C++ on abort callback).


<!-- Sent from Reviewable.io -->

2020-08-20 15:50 UTC, lukaszstolarczuk requested changes
> Reviewed 5 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 5 of 12 files reviewed, 17 unresolved discussions (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBYf2j2Le2PYTbd9xB:-MFBYf2kE4UVll6xUY0h:bosa6lb) (no related file):*
in commit "inline_string: add capacity field" you have misspell: `refernce`

---
___
*[examples/CMakeLists.txt, line 100 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBS9m-7e-tbxhvoH5S:-MFBS9m-7e-tbxhvoH5T:b-yr1kqy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/CMakeLists.txt#L100)):*
> ```CMake
> 
> add_cppstyle(examples-inline_string ${CMAKE_CURRENT_SOURCE_DIR}/inline_string/*.*pp)
> add_check_whitespace(examples-inline_string ${CMAKE_CURRENT_SOURCE_DIR}/inline_string/*.*pp)
> ```

`*.*pp` -> `*.*`
___
*[examples/CMakeLists.txt, line 103 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSDroBHRVlx1ztKne:-MFBSDroBHRVlx1ztKnf:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/CMakeLists.txt#L103)):*
> ```CMake
> 
> add_cppstyle(examples-radix_tree ${CMAKE_CURRENT_SOURCE_DIR}/radix_tree/*.*pp)
> add_check_whitespace(examples-radix_tree ${CMAKE_CURRENT_SOURCE_DIR}/radix_tree/*.*pp)
> ```

.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSi2V7K8NEKuVcqja:-MFBSi2V7K8NEKuVcqjb:bci4t07) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/radix_tree/radix_tree_inline_string.cpp#L5)):*
> ```cpp
> 
> /**
>  * radix_tree_basic.cpp -- example which shows how to use
> ```

pls update
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSuUAA5PGR9RPuZ7H:-MFBSuUAA5PGR9RPuZ7I:bci4t07) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L70)):*
> ```cpp
> 
> 	/**
> 	 * Constructs inline string from a string_view.
> ```

pls update
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 137 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBWKPY7boV5zgXWUVe:-MFBWKPY7boV5zgXWUVf:b-fabj72) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L137)):*
> ```cpp
> 
> 	/**
> 	 * @return number of characters that can be held in inline_string.
> ```

in **the** inline_string
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 141 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBXC1J909RQtgpouc-:-MFBXC1J909RQtgpouc0:bfr295i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L141)):*
> ```cpp
> 	 * The space actually occupied by inline_string is equal to
> 	 * sizeof(inline_string) + capacity() + sizeof('\0')
> 	 */
> ```

maybe it's worth mentioning (here?) it can't be expanded (can't it, right?)
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 165 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBUHLgDVB53IyIKJqw:-MFBUHLgDVB53IyIKJqx:b-sgukgr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L165)):*
> ```cpp
> 	 * Transactionally assign content of string_view.
> 	 *
> 	 * It does not check whether there is enough capacity - it's
> ```

update pls
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 57 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBO2cE3VxS6ielWWtP:-MFBO2cE3VxS6ielWWtQ:b3xwfwb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L57)):*
> ```cpp
> 
> /**
>  * Radix tree is an associative, ordered container. It's API is similar
> ```

`It's` -> `Its`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOO4W281FHIxBoNqx:-MFBOO4W281FHIxBoNqy:b-w8iar3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L61)):*
> ```cpp
>  *
>  * Unlike std::map radix tree does not use comparison (std::less or equivalent)
>  * to locate elements. Instead a keys is mapped to a sequence of bytes using
> ```

`Instead a keys is` -> `Instead, keys are`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 66 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOcNq0vzdWAmI1XvI:-MFBOcNq0vzdWAmI1XvJ:b-8jhbwt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L66)):*
> ```cpp
>  * treated as a hash function) but with sorted elements.
>  *
>  * The elements ordering is defined based on the BytesView mapping. The byte
> ```

`elements` -> `elements'`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOsi07hPPgnUJItrU:-MFBOsi07hPPgnUJItrV:b-hxfbhl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L70)):*
> ```cpp
>  *
>  * BytesView should accept a pointer to the key type in a constructor and
>  * provide operator[] and size methods. The declaration should be as following:
> ```

`methods` -> `method`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 84 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPU3G-B4uRkex6X5N:-MFBPU3G-B4uRkex6X5O:b980dnb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L84)):*
> ```cpp
>  * little-endian.
>  *
>  * Iterators and reference are stable (are not invalidated by inserts or erases
> ```

`reference` -> `references`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 88 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPPBj85EcWNe9Uhjn:-MFBPPBj85EcWNe9Uhjo:b980dnb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L88)):*
> ```cpp
>  * inline_string.
>  *
>  * In case of inline_string, iterators and reference are not invalidated by
> ```

`reference` -> `references`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 89 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBP79dCzZxBl82lA58:-MFBP79dCzZxBl82lA59:bj6rxsa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L89)):*
> ```cpp
>  *
>  * In case of inline_string, iterators and reference are not invalidated by
>  * other inserts or erases but might be invalidated by assigning new value to
> ```

`but` -> `, but`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 90 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPGDz19jXclZEh3zT:-MFBPGE-AgYyeeIEOVMX:b-cpvfvq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L90)):*
> ```cpp
>  * In case of inline_string, iterators and reference are not invalidated by
>  * other inserts or erases but might be invalidated by assigning new value to
>  * the element. Using find(K).assign_val("new_value") might invalidate other
> ```

`might` -> `may` (?)
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 742 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#- [...]

2020-08-24 08:24 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 5 of 12 files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBYf2j2Le2PYTbd9xB:-MFUVt1k0U9puxB73Cxh:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in commit "inline_string: add capacity field" you have misspell: `refernce`
</blockquote></details>

Done.

---
___
*[examples/CMakeLists.txt, line 100 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBS9m-7e-tbxhvoH5S:-MFUWD6Q8EesqkuBcWOm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/CMakeLists.txt#L100)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`*.*pp` -> `*.*`
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 103 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSDroBHRVlx1ztKne:-MFUWDLk6GFiu3jFdOGu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/CMakeLists.txt#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 5 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSi2V7K8NEKuVcqja:-MFUWKZ9ETdW3OGNkQ7q:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/examples/radix_tree/radix_tree_inline_string.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBSuUAA5PGR9RPuZ7H:-MFUXXl73e08kaOz-ha_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 137 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBWKPY7boV5zgXWUVe:-MFUX_3A1o9_8ubcR_VN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L137)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in **the** inline_string
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 141 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBXC1J909RQtgpouc-:-MFUXco8DPESLGQ3j0rP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L141)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe it's worth mentioning (here?) it can't be expanded (can't it, right?)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 165 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBUHLgDVB53IyIKJqw:-MFUXnRH9I27pUC8X5XX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/inline_string.hpp#L165)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update pls
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 57 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBO2cE3VxS6ielWWtP:-MFUY3K24kQv8AwLYkYQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`It's` -> `Its`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 61 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOO4W281FHIxBoNqx:-MFUY6hk1v1IaU3aNl2w:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Instead a keys is` -> `Instead, keys are`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 66 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOcNq0vzdWAmI1XvI:-MFUY8sIDARB4E1-6rfD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`elements` -> `elements'`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 70 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBOsi07hPPgnUJItrU:-MFUYCJX361DDArRKt1n:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`methods` -> `method`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 84 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPU3G-B4uRkex6X5N:-MFUYEv9CyZjzxqAi0iT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`reference` -> `references`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 88 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPPBj85EcWNe9Uhjn:-MFUYGGiCjD4Cd8E0-kc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`reference` -> `references`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 89 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBP79dCzZxBl82lA58:-MFUYI1VCHUE-e6EEl1Y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`but` -> `, but`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 90 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBPGDz19jXclZEh3zT:-MFUYLGS3iLYL0rdPgdx:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8982193b066118c8446f04c51134028b46dbe62a/include/libpmemobj++/experimental/radix_tree.hpp#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`might` -> `may` (?)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 742 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MFBQ1i_9a1rKgUDpx6M:-MFUYUvP1YYG5xuCvMAW:b-896fix) ([raw file](https://github [...]

2020-08-25 11:20 UTC, KFilipek reviewed
> Reviewed 4 of 12 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: all files reviewed, 18 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 68 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_Kk25CskhS5PiuSJF:-MF_Kk25CskhS5PiuSJG:b-okgdik) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L68)):*
> ```cpp
> 		 * invalidated */
> 		(void)it2;
> 		// assert(it2->value().data()[0] == 's') /* dangerous, it2 might
> ```

Is it necessary?


<!-- Sent from Reviewable.io -->

2020-08-25 11:36 UTC, kilobyte reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 11 of 15 files reviewed, 22 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/inline_string/inline_string.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_NfvMB-Iz9B5CW-FB:-MF_NfvMB-Iz9B5CW-FC:by3amr0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8bea3a1c52165f034e3ecfa69aa796d12c6195be/examples/inline_string/inline_string.cpp#L77)):*
> ```cpp
> 	if (pmemobj_alloc_usable_size(pmemobj_oid(r->o.get())) -
> 		    sizeof(Object) >=
> 	    strlen(new_value) + sizeof('\0')) {
> ```

sizeof(char) is by definition 1, no point in using an atypical construct here.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_O44Z2-xxZgDKIhVB:-MF_O44_1eAgGJ7OQ_UI:b-t0lo7g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L54)):*
> ```cpp
> 			it->value() = "some long string";
> 		} catch (std::out_of_range &) {
> 			/* The capacity might not be enough, use assing_val
> ```

assign
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 65 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_OAEo1VZpr4eHF0-H:-MF_OAEo1VZpr4eHF0-I:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L65)):*
> ```cpp
> 			       .compare("some long string") == 0);
> 
> 		/* If reallocation happend on assing_val, it2 will be
> ```

.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 11 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_OSLzAI6VE4nVjqrc:-MF_OSLzAI6VE4nVjqrd:b-o146cf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/include/libpmemobj++/experimental/radix_tree.hpp#L11)):*
> ```cpp
>  * The implementation is a variation of a PATRICIA trie - the internal
>  * nodes do not store the path explicitly, but only a position at which
>  * the keys differ. Keys are stored entirely in leafs.
> ```

leaves


<!-- Sent from Reviewable.io -->

2020-08-25 11:46 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 10 of 15 files reviewed, 22 unresolved discussions (waiting on @KFilipek, @kilobyte, and @lukaszstolarczuk)

___
*[examples/inline_string/inline_string.cpp, line 77 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_NfvMB-Iz9B5CW-FB:-MF_QH5gEoCXIc-YudYX:b40su1q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8bea3a1c52165f034e3ecfa69aa796d12c6195be/examples/inline_string/inline_string.cpp#L77)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

sizeof(char) is by definition 1, no point in using an atypical construct here.
</blockquote></details>

Yes, the idea was to just make it clear where did this 1 came from. But anyway, it is now removed.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 54 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_O44Z2-xxZgDKIhVB:-MF_Qf8A6j5LfiaO-TEE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L54)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

assign
</blockquote></details>

Done.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 65 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_OAEo1VZpr4eHF0-H:-MF_QcFS9sFbrrgUlkVU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L65)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 68 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_Kk25CskhS5PiuSJF:-MF_Ovg1B1hZjqT7Tfot:bwxqbm3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L68)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Is it necessary?
</blockquote></details>

You mean this comment or the `(void)it2` line? The comment is just an example of what not to do, and the `(void)it2` is needed so that there is no "unused variable" warning.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 11 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_OSLzAI6VE4nVjqrc:-MF_PqyFCTOg436JaUTE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/include/libpmemobj++/experimental/radix_tree.hpp#L11)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

leaves
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-25 11:51 UTC, KFilipek reviewed
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 11 of 15 files reviewed, 17 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 68 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF_Kk25CskhS5PiuSJF:-MF_RXWjE6Udm44p4gWj:b-fi5br7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05f7199245f3deb067f71c68d47453dbfce55329/examples/radix_tree/radix_tree_inline_string.cpp#L68)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You mean this comment or the `(void)it2` line? The comment is just an example of what not to do, and the `(void)it2` is needed so that there is no "unused variable" warning.
</blockquote></details>

Ok, maybe better is to use block comment, then it looks more like "documentation style", unlike mistake during code pushing
```
  /*
  * assert(it2->value().data()[0] == 's') 
  * dangerous, it2 might be invalid
  */
```


<!-- Sent from Reviewable.io -->

2020-08-25 11:51 UTC, KFilipek reviewed
> Reviewed 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-08-25 12:34 UTC, szyrom approved these changes
> Reviewed 8 of 12 files at r3, 2 of 4 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF_YQ0qCDyAxD3vKoG5:b-ezut6p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
> 2029
as I understand, the current behavior of iterator is similar to the std::map::iterator with the exception when the modification is done within tx (and tx get aborted).

regarding the behavior when tx aborts: imho we should restore the previous pointer (I can't see any problems with a callback approach atm). The example below should cover this scenario as well. 


<!-- Sent from Reviewable.io -->

2020-08-25 12:47 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 14 of 15 files reviewed, 17 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF_dJo62VXr7cxT-sFl:bkqbyqk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

> 2029
as I understand, the current behavior of iterator is similar to the std::map::iterator with the exception when the modification is done within tx (and tx get aborted).

regarding the behavior when tx aborts: imho we should restore the previous pointer (I can't see any problems with a callback approach atm). The example below should cover this scenario as well. 
</blockquote></details>

Ok, I'll add that in a separate PR.


<!-- Sent from Reviewable.io -->

2020-08-25 13:01 UTC, szyrom reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-:-MF_hLiS6SG8T3fF4BKl:bnfp4nl)* status: 14 of 15 files reviewed, 17 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF_hDy4ABn7RSClapcU:b-c1scpc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, I'll add that in a separate PR.
</blockquote></details>

please add this together with the extension of this example (to illustrate the issue)


<!-- Sent from Reviewable.io -->

2020-08-25 13:15 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: 14 of 15 files reviewed, 17 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/radix_tree/radix_tree_inline_string.cpp, line 62 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-MF65uLh4I2uYkUPg9xL:-MF_kNWqEeSCpFatn7l_:b-y4pfb0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb2eba299cb17143e01fc53bf6645c6a27c5ef02/examples/radix_tree/radix_tree_inline_string.cpp#L62)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

please add this together with the extension of this example (to illustrate the issue)
</blockquote></details>

I'd like to add both extension of this example and the pointer restoration in separate PR. I think it will be easier to discuss the change (or to spot some problems with the restoration approach).


<!-- Sent from Reviewable.io -->

2020-08-25 14:20 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-08-25 14:21 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/838#-:-MF_z_a-6YjieWIafKO1:bnfp4nl)* status: all files reviewed, 17 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-08-26 10:22 UTC, merged