Implementation of basic_string_view class
pmem/libpmemobj-cpp pull request #846
Opened 2020-08-26 16:29 UTC by KFilipek

Commit message: ﻿Parametrized version of original string_view

2020-08-27 08:13 UTC, igchor requested changes
Please add some tests (ideally, paraemterize existing ones: ) for basic_string_view specilized with different CharT types (I propose uint8_t and wchar_t).

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-:-MFiyGFl6jk08riHRcqA:burl3hc)* status: all files reviewed, 9 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MFix9NE4B--J-FIJtmo:b7tw0rg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
> ```cpp
> 
> #if __cpp_lib_string_view
> using string_view = std::string_view;
> ```

Please add aliases for basic_string_view (and wstring_view, etc.) also.
___
*[include/libpmemobj++/string_view.hpp, line 23 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix7gv5X1Z8_A_q4Qq:-MFix7gwEkZHLjRuoptl:b-dmrjcd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L23)):*
> ```cpp
> using string_view = std::string_view;
> #else
> /* XXX: implement it as a template (basic_string_view) */
> ```

This can probably be removed
___
*[include/libpmemobj++/string_view.hpp, line 45 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixPaBDfW_2YCf7mGM:-MFixPaBDfW_2YCf7mGN:b-ns1q6q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L45)):*
> ```cpp
> 
> 	basic_string_view() noexcept;
> 	basic_string_view(const char *data, size_t size);
> ```

const CharT*
___
*[include/libpmemobj++/string_view.hpp, line 47 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixTO7AMSQj0HvIPNz:-MFixTO7AMSQj0HvIPO-:b-ns1q6q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L47)):*
> ```cpp
> 	basic_string_view(const char *data, size_t size);
> 	basic_string_view(const std::string &s);
> 	basic_string_view(const char *data);
> ```

const CharT*
___
*[include/libpmemobj++/string_view.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixVMi3uz4q2U-1iGn:-MFixVMi3uz4q2U-1iGo:b-ns1q6q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L52)):*
> ```cpp
> 	basic_string_view &operator=(const basic_string_view &rhs) noexcept = default;
> 
> 	const char *data() const noexcept;
> ```

const CharT*
___
*[include/libpmemobj++/string_view.hpp, line 53 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixWMr0NeLL1zKu3bd:-MFixWMr0NeLL1zKu3be:bdw4z3l) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L53)):*
> ```cpp
> 
> 	const char *data() const noexcept;
> 	std::size_t size() const noexcept;
> ```

nit: this, seocnd ctor's argument  and operator[] argument could be size_type
___
*[include/libpmemobj++/string_view.hpp, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixepy7A-DNK7RmK_A:-MFixepy7A-DNK7RmK_B:b-ns1q6u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L55)):*
> ```cpp
> 	std::size_t size() const noexcept;
> 
> 	const char &operator[](size_t p) const noexcept;
> ```

const CharT&
___
*[include/libpmemobj++/string_view.hpp, line 60 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixlUS1V9sXrswr4Z3:-MFixlUS1V9sXrswr4Z4:btw9xin) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L60)):*
> ```cpp
> 
> private:
> 	const value_type *__data;
> ```

We should not use double underscore: https://stackoverflow.com/questions/224397/why-do-people-use-double-underscore-so-much-in-c Tbh, using single underscore at the beginning is also not perfect, so if you're changing that change it to data_ and size_ or something.
___
*[include/libpmemobj++/string_view.hpp, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFiy6M36we5RHwsyP6v:-MFiy6M36we5RHwsyP6w:bramucd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L80)):*
> ```cpp
>  * Constructor initialized by *data* and its *size*.
>  *
>  * @param[in] data pointer to the C-like string (char *) to initialize with,
> ```

char* is not alwyas true
___
*[include/libpmemobj++/string_view.hpp, line 163 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFiyEczB1_7rqIJrKu8:-MFiyEczB1_7rqIJrKu9:b-89uybr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L163)):*
> ```cpp
> basic_string_view<CharT, Traits>::compare(const basic_string_view &other) noexcept
> {
> 	int ret = std::char_traits<char>::compare(
> ```

CharT


<!-- Sent from Reviewable.io -->

2020-08-27 08:15 UTC, igchor reviewed
As I know see, the exisiting string_view test is rather simple so I guess you should extend it ;d But still, I think the test should be templetized with CharT so that we can test different types.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-:-MFiynza57Fi5UWGpY1v:b-dcvab)* status: all files reviewed, 9 unresolved discussions (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2020-08-27 12:23 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MFjbDXy6p2RzJeul8Hn:b-fib9i9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add aliases for basic_string_view (and wstring_view, etc.) also.
</blockquote></details>

They was added below class
___
*[include/libpmemobj++/string_view.hpp, line 23 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix7gv5X1Z8_A_q4Qq:-MFjrdLaA6ua0K-uS789:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This can probably be removed
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 45 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixPaBDfW_2YCf7mGM:-MFjbJvE5o6mT2342wuV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

const CharT*
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 47 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixTO7AMSQj0HvIPNz:-MFjbKG531axTzIfkoY0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L47)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

const CharT*
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixVMi3uz4q2U-1iGn:-MFjbLb7ASd8H8v8HUxy:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

const CharT*
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixepy7A-DNK7RmK_A:-MFjbQczDcD87hdk_uGy:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L55)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

const CharT&
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 60 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFixlUS1V9sXrswr4Z3:-MFjrgaL1VyAgGXZDRoN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We should not use double underscore: https://stackoverflow.com/questions/224397/why-do-people-use-double-underscore-so-much-in-c Tbh, using single underscore at the beginning is also not perfect, so if you're changing that change it to data_ and size_ or something.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFiy6M36we5RHwsyP6v:-MFjrjMF1vz2KaCBTuzo:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L80)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

char* is not alwyas true
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 163 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFiyEczB1_7rqIJrKu8:-MFjrkh800l82ma9C4x0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L163)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

CharT
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 13:02 UTC, igchor requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MFjzyRj3A4v5SjHev7l:bkv8f6y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

They was added below class
</blockquote></details>

But the ones below the class are only present when !__cpp_lib_string_view and are aliases for pmem::obj:basic_string_view. Here you should put aliases for std::basic_string_view.

Also it would be good to run tests with string_view with std < C++17 and std >= C++17 (please make sure we have such configurations on CI).
___
*[include/libpmemobj++/string_view.hpp, line 64 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFjzvOj8BwBa5FpFHFg:-MFjzvOj8BwBa5FpFHFh:b-c35osg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/949580ff040f97f60dbda7aa7ff1ecc9ef41ffcf/include/libpmemobj++/string_view.hpp#L64)):*
> ```cpp
> };
> 
> using string_view = pmem::obj::basic_string_view<char>;
> ```

pmem::obj:: prefix is not neccessary here.


<!-- Sent from Reviewable.io -->

2020-08-27 16:12 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MFkfMzQEWVXQn8mahHI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

But the ones below the class are only present when !__cpp_lib_string_view and are aliases for pmem::obj:basic_string_view. Here you should put aliases for std::basic_string_view.

Also it would be good to run tests with string_view with std < C++17 and std >= C++17 (please make sure we have such configurations on CI).
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 64 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFjzvOj8BwBa5FpFHFg:-MFkfO8n8UntTUTLM2xP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/949580ff040f97f60dbda7aa7ff1ecc9ef41ffcf/include/libpmemobj++/string_view.hpp#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

pmem::obj:: prefix is not neccessary here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-28 08:44 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MFoDu-70R4MCpME9RjK:bhwgon4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please also add alias for the basic_string_view itself (the template class).
___
*[tests/string_view/string_view.cpp, line 12 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFoE59H16DmtgfNdSzU:-MFoE59I23V027FkdUV5:buyagmg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/94658a044f701fe4a4c5b473c25501f6d3c48bd1/tests/string_view/string_view.cpp#L12)):*
> ```cpp
> template <typename T>
> void
> test_string_view()
> ```

Please extend this test (inline_string should have 100% coverage). Add tests for missing ctors, operator[] and for different strings (instead of "abc" and "xyz" so that compare() methods is fully covered).


<!-- Sent from Reviewable.io -->

2020-08-31 09:38 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MG2s9S33v44rM2sIw0G:-MG2s9S44wBsJT8lVG34:b-sjsk0u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/30c5d57fce5970cb656c40fe4254fb521e613e2a/include/libpmemobj++/string_view.hpp#L21)):*
> ```cpp
> 
> #if __cpp_lib_string_view
> using basic_string_view = std::basic_string_view;
> ```

This won't work, use template alias https://en.cppreference.com/w/cpp/language/type_alias


<!-- Sent from Reviewable.io -->

2020-09-01 10:19 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFix9NE4B--J-FIJtmn:-MG8A94X7poP-C112zZ7:b-segl4c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/86f580a969c4865c263cc46dc6b10f868d794fd4/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also add alias for the basic_string_view itself (the template class).
</blockquote></details>

Is now okey?
___
*[include/libpmemobj++/string_view.hpp, line 21 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MG2s9S33v44rM2sIw0G:-MG8A795BNH9G2oC2ktC:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/30c5d57fce5970cb656c40fe4254fb521e613e2a/include/libpmemobj++/string_view.hpp#L21)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This won't work, use template alias https://en.cppreference.com/w/cpp/language/type_alias
</blockquote></details>

Done.
___
*[tests/string_view/string_view.cpp, line 12 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-MFoE59H16DmtgfNdSzU:-MG8AEFr-N9vq-XBcRgX:b-zg9i24) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/94658a044f701fe4a4c5b473c25501f6d3c48bd1/tests/string_view/string_view.cpp#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please extend this test (inline_string should have 100% coverage). Add tests for missing ctors, operator[] and for different strings (instead of "abc" and "xyz" so that compare() methods is fully covered).
</blockquote></details>

basic_string_view now have 100% of coverage, should I modify inline_string test or modify string_view?


<!-- Sent from Reviewable.io -->

2020-09-01 12:11 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846#-:-MG8_8gP4W7nQ2qAMWzh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-02 06:23 UTC, szyrom approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/846)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-02 06:23 UTC, merged