hetegenerous methods for radix_tree
pmem/libpmemobj-cpp pull request #847
Opened 2020-08-31 10:02 UTC by JanDorniak99

2020-08-31 10:25 UTC, igchor reviewed
> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 10 of 14 files reviewed, 9 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 173 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG3-RWb-0qRLIpccaTL:-MG3-RWb-0qRLIpccaTM:bg2wjal) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L173)):*
> ```cpp
> 		typename = typename std::enable_if<
> 			detail::has_is_transparent<BytesView>::value, M>::type>
> 	std::pair<iterator, bool> insert_or_assign(const key_type &k, M &&obj);
> ```

I think this `const key_type &k` should be changed to `const_key_reference`. The reason is that, for inline_string we accept string_view as key (instead of `const inline_string& k`).

It would be best if you add some tests for insert_or_assign with some trivial type (like int) and inline_string as key type. You can just extend radix/radix_tx_abort.cpp test.

All this relates only to const key_type&, key_type&& should remain unchanged.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30DtjEU1pIViRnOUJ:-MG30DtjEU1pIViRnOUK:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L204)):*
> ```cpp
> 		typename = typename std::enable_if<
> 			detail::has_is_transparent<BytesView>::value, K>::type>
> 	size_type count(const K &k) const;
> ```

.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1241 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30NEvBPJ4AUCUOkD9:-MG30NEvBPJ4AUCUOkDA:b-lqkm4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1241)):*
> ```cpp
> 					  const value_type &v)
> {
> 	return insert(v).first;
> ```

`.first`? Why not return insert(v)?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1251 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30TaU9vZEikm3xn4-:-MG30TaU9vZEikm3xn40:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1251)):*
> ```cpp
> 					  value_type &&v)
> {
> 	return insert(std::move(v)).first;
> ```

.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1262 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30Y3L-R2lkPTgixHA:-MG30Y3L-R2lkPTgixHB:bduzhzx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1262)):*
> ```cpp
> 	auto it = find(k);
> 	if (it == end()) {
> 		return insert(value_type(k, std::forward<M>(obj)));
> ```

A more optimal way would be to call `emplace(k, std::forward<M>(obj))`. As you may now, value_type is not actually stored in radix tree (it's only a interface type). Because of that, creating value_type will be an unnecessary copy. Moreover, I think this will fail if you run it with inline_string (inline_string cannot be constructed on stack).
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1264 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG3127d8wDEDcObgfv0:-MG3127d8wDEDcObgfv1:baapwsq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1264)):*
> ```cpp
> 		return insert(value_type(k, std::forward<M>(obj)));
> 	} else {
> 		swap(*it, value_type(k, std::forward<M>(obj)));
> ```

A swap is not the optimal way here. I would suggest:
```
it.assing_val(std::forward<M>(obj));
return {it, false};
```

Btw, you don;t need to specify full return type here, {first, second} syntax is enough.
___
*[tests/external/CMakeLists.txt, line 1186 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31lVW60HCgMRz1EuB:-MG31lVW60HCgMRz1EuC:b-mlnvzg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/tests/external/CMakeLists.txt#L1186)):*
> ```CMake
> 	add_test_generic(NAME radix_libcxx_max_size TRACERS none pmemcheck memcheck)
> 
> 	# XXX: no member named 'insert'
> ```

This is now outdated?
___
*[tests/external/CMakeLists.txt, line 1193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31noC-8wpa005DTLg:-MG31noC-8wpa005DTLh:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e11175151884ea69044828c9f718e477245984f6/tests/external/CMakeLists.txt#L1193)):*
> ```CMake
> 	add_test_generic(NAME radix_libcxx_iterator TRACERS none pmemcheck memcheck)
> 
> 	# XXX: no member named 'insert'
> ```

.
___
*[tests/external/CMakeLists.txt, line 1197 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31oJVDvm8s2RtgFVn:-MG31oJVDvm8s2RtgFVo:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/tests/external/CMakeLists.txt#L1197)):*
> ```CMake
> 	add_test_generic(NAME radix_libcxx_empty TRACERS none pmemcheck memcheck)
> 
> 	# XXX: cannot convert "C2Int" to const int&"
> ```

.


<!-- Sent from Reviewable.io -->

2020-08-31 10:35 UTC, igchor commented
@vinser52 Could you look at the approach we've taken for heterogeneous methods and bytes view here? The idea is that we enable heterogeneous methods only if bytes_view (which is kind of similar do compare in std::map) has is_transparent type. However, unlike in std::less<void> or some othe comparators, here, heterogeneity is implemented through constructors (e.g. bytes_view has ctor for both pmem::obj::string and const char*). Do you think this approach is OK, do you have any other ideas for that?

The reason why bytes_view is not stateless (it has a ctor from required types) is that converting from user-type to bytes can be slow and it's better to do it once (per function).

2020-08-31 13:07 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 9 of 15 files reviewed, 7 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30DtjEU1pIViRnOUJ:-MG3c38b2NInUuW2Jhsc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L204)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1262 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30Y3L-R2lkPTgixHA:-MG3c7LY8rJ2XiMkSnxc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1262)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

A more optimal way would be to call `emplace(k, std::forward<M>(obj))`. As you may now, value_type is not actually stored in radix tree (it's only a interface type). Because of that, creating value_type will be an unnecessary copy. Moreover, I think this will fail if you run it with inline_string (inline_string cannot be constructed on stack).
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1264 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG3127d8wDEDcObgfv0:-MG3c8N387L71lHrZI22:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1264)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

A swap is not the optimal way here. I would suggest:
```
it.assing_val(std::forward<M>(obj));
return {it, false};
```

Btw, you don;t need to specify full return type here, {first, second} syntax is enough.
</blockquote></details>

Done.
___
*[tests/external/CMakeLists.txt, line 1186 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31lVW60HCgMRz1EuB:-MG3c9Nb2mxgOiBesOlu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/tests/external/CMakeLists.txt#L1186)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is now outdated?
</blockquote></details>

Done.
___
*[tests/external/CMakeLists.txt, line 1193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31noC-8wpa005DTLg:-MG3c9do7s0qB6Ht5Ym2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e11175151884ea69044828c9f718e477245984f6/tests/external/CMakeLists.txt#L1193)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/CMakeLists.txt, line 1197 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG31oJVDvm8s2RtgFVn:-MG3c9tD0JNclYgorqnU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/tests/external/CMakeLists.txt#L1197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-02 13:22 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 9 of 17 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 173 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG3-RWb-0qRLIpccaTL:-MGDyuHtCe6BM2Fm2yji:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L173)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this `const key_type &k` should be changed to `const_key_reference`. The reason is that, for inline_string we accept string_view as key (instead of `const inline_string& k`).

It would be best if you add some tests for insert_or_assign with some trivial type (like int) and inline_string as key type. You can just extend radix/radix_tx_abort.cpp test.

All this relates only to const key_type&, key_type&& should remain unchanged.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-07 10:23 UTC, igchor reviewed
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 14 of 17 files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1262 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG30Y3L-R2lkPTgixHA:-MGc3MGs90cQ0ZRWfjD7:bafvz1c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9282b88364732faa6d807bf6ed0a822cf109443f/include/libpmemobj++/experimental/radix_tree.hpp#L1262)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm, after looking at it one more time, I think even more optimal solution would be to implement it like this:

```
auto ret = try_emplace(k, std::forward<M>(obj);
if (!ret.second)
    ret.first.assign_val(std::forward<M>(obj));

return ret.first;
```

This way we only need to find the position once.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1368 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc3nw401cJHKxE3SDI:-MGc3nw401cJHKxE3SDJ:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L1368)):*
> ```cpp
> 	auto it = find(k);
> 	if (it == end()) {
> 		return emplace(std::move(k), std::forward<M>(obj));
> ```

.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2404 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc41tM3-cryR4kFMoQ:-MGc41tM3-cryR4kFMoR:b-58tsxy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2404)):*
> ```cpp
> 	auto pop = pool_base(pmemobj_pool_by_ptr(leaf_));
> 
> 	transaction::run(pop, [&] { leaf_->value() = std::forward<T>(rhs); });
> ```

Please also add a doxygen comment for this function. It should state that it starts an internal transaction.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2770 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc4QKl-M_7Z8nlNXVM:-MGc4QKl-M_7Z8nlNXVN:bd6q2wa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2770)):*
> ```cpp
> 
> 	using is_transparent = void;
> };
> ```

I think that for now, we should not add this using here. We do not add any more ctors anyway so I don't think it changes anything.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2802 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc4ZCn2wjD-KUYQOC-:-MGc4ZCn2wjD-KUYQOC0:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2802)):*
> ```cpp
> 	const T *k;
> 
> 	using is_transparent = void;
> ```

.


<!-- Sent from Reviewable.io -->

2020-09-08 06:21 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1368 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc3nw401cJHKxE3SDI:-MGgN0jK8k3p5OsLmfD6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L1368)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2404 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc41tM3-cryR4kFMoQ:-MGgN20fCnmsNcoi0Yhh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2404)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also add a doxygen comment for this function. It should state that it starts an internal transaction.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2770 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc4QKl-M_7Z8nlNXVM:-MGgN4WIAWu3JKpW5y-o:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2770)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that for now, we should not add this using here. We do not add any more ctors anyway so I don't think it changes anything.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2802 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGc4ZCn2wjD-KUYQOC-:-MGgN4im8zfZokpiVY6B:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7c0d21620a62b5d9af214847f6ffdb8dce33775d/include/libpmemobj++/experimental/radix_tree.hpp#L2802)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-08 12:43 UTC, JanDorniak99 commented on include/libpmemobj++/experimental/radix_tree.hpp
> +	std::pair<iterator, bool> try_emplace(K &&k, Args &&... args);*/
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96976

2020-09-08 13:30 UTC, igchor reviewed
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 14 of 17 files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 45 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGhuAYl05ph027YUZSv:-MGhuAYm6Kh_lCBOxZjF:b-w5np1r) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L45)):*
> ```cpp
> {
> 
> /* XXX: move to template_helpers */
> ```

Is there any problem with moving this now?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 179 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MG2xtD3jBM_K3O1WqSW-r3-179:-MGht0vB7Lh_Ff5by-Jd:b-vkpvz2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/experimental/radix_tree.hpp#L179)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96976
</blockquote></details>

Please put this in the comment in the code.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2830 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGhtfms1tI0ugsnXG0D:-MGhtfmt9XTm_FWwCwFi:b2qvipl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/experimental/radix_tree.hpp#L2830)):*
> ```cpp
>  * Assign value to leaf pointed by the iterator.
>  *
>  * Transaction is being called internally inside this method.
> ```

... is being started ...

Or even better: "This function is transactional".


<!-- Sent from Reviewable.io -->

2020-09-09 07:28 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 13 of 20 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 45 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGhuAYl05ph027YUZSv:-MGlkwyI8PSu1xYgJF6U:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is there any problem with moving this now?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2830 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGhtfms1tI0ugsnXG0D:-MGlkzSwC9A0jOkYhfbk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/experimental/radix_tree.hpp#L2830)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

... is being started ...

Or even better: "This function is transactional".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 21:20 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 14 of 22 files reviewed, 10 unresolved discussions (waiting on @igchor and @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoYoR9A1AwDlwD7prT:-MGoYoR9A1AwDlwD7prU:b3md6li) (no related file):*
hint: for future - pls don't create sep. commit for docs. Deliver members/classes along with docs already (within a single commit).

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoZJHg-nbs5757WIKN:-MGoZJHg-nbs5757WIKO:bgacn3b) (no related file):*
in one of the commit messages you say "import from `31cbe0f240f660f15602c96b787c58a26f17e179`" - this doesn't say much, please add link to commit or point which repo it was taken from ;)

see e.g. some prev. commit importing libcxx tests:

```
commit 85c78b3932ec6089df4a3faf27b57ce62fb08eb0
Author: Krzysztof Filipek <krzysztof.filipek@intel.com>
...
Files copied from:
https://github.com/llvm-mirror/libcxx/commit/78d6a7767
```

---
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1288 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGofnv-9u8r2NSG7Ss2:-MGofnv-9u8r2NSG7Ss3:b-wsvg3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1288)):*
> ```cpp
> 
> /**
>  * Inserts element into the container, if the container doesn't already contain
> ```

inserts into **container** if the **container** doesn't **contain** ;)

I'd re-write it perhaps like this:
`Inserts element if the tree doesn't already contain an element with an equivalent key.` or even better(?) ...the same key.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1291 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohmx36lbAFZfFBRoh:-MGohmx36lbAFZfFBRoi:b-z2z4ue) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1291)):*
> ```cpp
>  * an element with an equivalent key.
>  *
>  * @param[in] v element value to insert
> ```

1. element's value
2. put `.` at the end of this sentence/line
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1323 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohcDdAo0xTgJbiQ2j:-MGohcDdAo0xTgJbiQ2k:b-87v6b5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1323)):*
> ```cpp
>  * failed.
>  * @throw rethrows constructor exception.
>  */
> ```

based on the description - what's the difference between this and prev. method? ;)
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1345 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohzt342rNGo_TtvCV:-MGohzt342rNGo_TtvCW:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1345)):*
> ```cpp
>  * failed.
>  * @throw rethrows constructor exception.
>  */
> ```

.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1357 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoiDzp-242i40Jv5Xv:-MGoiDzq6RIr3toOB9n7:bxlwjfw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1357)):*
> ```cpp
>  * Inserts elements from range [first, last).
>  *
>  * @param[in] first first element of range of elements to insert
> ```

perhaps like in concurrent_skip_list:

first iterator of inserted range.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1358 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoiNZr3aAJP56aSzrY:-MGoiNZr3aAJP56aSzrZ:b-8bu1j7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1358)):*
> ```cpp
>  *
>  * @param[in] first first element of range of elements to insert
>  * @param[in] last last element of range of elements to insert
> ```

last iterator of inserted range.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1395 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoeuX3-4t-Vlvg_Qkz:-MGoeuX3-4t-Vlvg_Ql-:b9ai6lx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1395)):*
> ```cpp
>  * If a key equivalent to k already exists in the container, does nothing.
>  * Otherwise, behaves like emplace except that the element is constructed
>  * as value_type(std::piecewise_construct, std::forward_as_tuple(std::move(k)),
> ```

...meaning (to the user)..what?


<!-- Sent from Reviewable.io -->

2020-09-10 11:17 UTC, igchor requested changes
> Reviewed 6 of 9 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: all files reviewed, 14 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 45 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGhuAYl05ph027YUZSv:-MGmjE4oBPegny2U38iW:bkdjmaq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a8b1cd5f07ee5e217c88acac39185f33899eb8/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L45)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you put that in a separate commit?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 146 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrc7xECEppx6E04sIZ:-MGrc7xECEppx6E04sI_:b-a0hon2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L146)):*
> ```cpp
> 		typename P,
> 		typename = typename std::enable_if<
> 			detail::has_is_transparent<BytesView>::value, P>::type>
> ```

I don't think this insert should depend on is_transparent. Instead you should check std::is_constructible<value_type, P &&>::value>::type (as described here: https://en.cppreference.com/w/cpp/container/map/insert)
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 163 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrdFr47nHWuIJOwyx_:-MGrdFr47nHWuIJOwyxa:b-ykejdc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L163)):*
> ```cpp
> 	std::pair<iterator, bool> try_emplace(key_type &&k, Args &&... args);
> 	template <class... Args>
> 	iterator try_emplace(const_iterator hint, const_key_reference k,
> ```

Please group the function together. All inserts next to each other, all try_emplace next to each other, etc.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 168 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrcHST62di55Kv4T7e:-MGrcHST62di55Kv4T7f:b-2ljfzx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L168)):*
> ```cpp
> 	iterator try_emplace(const_iterator hint, key_type &&k,
> 			     Args &&... args);
> 	/* XXX: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96976 */
> ```

In this issue, someone posted a workaround which you can use.
In our case it should be something like this:

```
template <typename K, typename... Args>
auto insert_or_assign(K&& k, Args&&... args) -> std::enable_if_t<detail::has_is_transparent<BytesView>::value, std::pair<iterator, bool>>::type
```
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 181 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrdTY55vMrFXbU5rsf:-MGrdTY55vMrFXbU5rsg:b-1m25uo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L181)):*
> ```cpp
> 	std::pair<iterator, bool> insert_or_assign(key_type &&k, M &&obj);
> 	template <typename M>
> 	iterator insert_or_assign(const_iterator hint, const_key_reference k,
> ```

Those to hint function could be commented out for now, right?
___
*[tests/external/libcxx/map/map.modifiers/insert_initializer_list.pass.cpp, line 43 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrhZRJ4_lNUgCLA9le:-MGrhZRJ4_lNUgCLA9lf:bd6dvxu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/tests/external/libcxx/map/map.modifiers/insert_initializer_list.pass.cpp#L43)):*
> ```cpp
> 	auto robj = pop.root();
> 	{
> #ifdef LIBPMEMOBJ_CPP_TESTS_RADIX
> ```

FYI, you can just do `using V = typename container::value_type;` without any ifdefs
___
*[tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp, line 131 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGri7eYD8nQZdF8fZhb:-MGri7eYD8nQZdF8fZhc:bzbg9uw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp#L131)):*
> ```cpp
> 		Moveable mvkey2(3, 3.0);
> 		Moveable mv2(5, 5.0);
> 		r = m.try_emplace(std::move(mvkey2), std::move(mv2));
> ```

Maybe it would be better to move this try_emplace test to try_emplace.pass.cpp?
___
*[tests/radix/radix_tx_abort.cpp, line 432 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrinBv108Y6vMc4xR2:-MGrinBv108Y6vMc4xR3:bvdj9k8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/tests/radix/radix_tx_abort.cpp#L432)):*
> ```cpp
> 	test_insert_or_assign<container_string, 1>(pop, pop.root()->radix_str);
> 	test_insert_or_assign<container_int, 1>(pop, pop.root()->radix_int);
> ```

Could you also implement try_emplace and insert tests here?


<!-- Sent from Reviewable.io -->

2020-09-14 12:52 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 17 of 22 files reviewed, 14 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoZJHg-nbs5757WIKN:-MHAdONr8NpFNFB4VkdH:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in one of the commit messages you say "import from `31cbe0f240f660f15602c96b787c58a26f17e179`" - this doesn't say much, please add link to commit or point which repo it was taken from ;)

see e.g. some prev. commit importing libcxx tests:

```
commit 85c78b3932ec6089df4a3faf27b57ce62fb08eb0
Author: Krzysztof Filipek <krzysztof.filipek@intel.com>
...
Files copied from:
https://github.com/llvm-mirror/libcxx/commit/78d6a7767
```
</blockquote></details>

Done.

---
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 146 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrc7xECEppx6E04sIZ:-MHAdROD6li1BPP2iead:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L146)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't think this insert should depend on is_transparent. Instead you should check std::is_constructible<value_type, P &&>::value>::type (as described here: https://en.cppreference.com/w/cpp/container/map/insert)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 163 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrdFr47nHWuIJOwyx_:-MHAp-B00pQ0uMPAmfyO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L163)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please group the function together. All inserts next to each other, all try_emplace next to each other, etc.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 168 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrcHST62di55Kv4T7e:-MHBVPOt93fCMahBQwdo:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L168)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

In this issue, someone posted a workaround which you can use.
In our case it should be something like this:

```
template <typename K, typename... Args>
auto insert_or_assign(K&& k, Args&&... args) -> std::enable_if_t<detail::has_is_transparent<BytesView>::value, std::pair<iterator, bool>>::type
```
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 181 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrdTY55vMrFXbU5rsf:-MHAp3JgAPB8dRXeTCoz:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L181)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Those to hint function could be commented out for now, right?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1288 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGofnv-9u8r2NSG7Ss2:-MHAdVX81YFPaP7ePptn:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1288)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

inserts into **container** if the **container** doesn't **contain** ;)

I'd re-write it perhaps like this:
`Inserts element if the tree doesn't already contain an element with an equivalent key.` or even better(?) ...the same key.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1291 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohmx36lbAFZfFBRoh:-MHAdWlz9AyEEOZtl3r4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1291)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. element's value
2. put `.` at the end of this sentence/line
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1345 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohzt342rNGo_TtvCV:-MHAdbga37-T5mKlCSn2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1345)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1357 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoiDzp-242i40Jv5Xv:-MHAdcv32sZp1KRtMO5V:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1357)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps like in concurrent_skip_list:

first iterator of inserted range.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1358 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoiNZr3aAJP56aSzrY:-MHAddEl8pAN7RVj8Xhv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1358)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

last iterator of inserted range.
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp, line 131 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGri7eYD8nQZdF8fZhb:-MHApbqz5GM0kdCJ5Gnw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp#L131)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe it would be better to move this try_emplace test to try_emplace.pass.cpp?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-15 06:37 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 17 of 22 files reviewed, 14 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1323 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGohcDdAo0xTgJbiQ2j:-MHFTtRv0esgMSdDzOtk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1323)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

based on the description - what's the difference between this and prev. method? ;)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1395 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGoeuX3-4t-Vlvg_Qkz:-MHFTuGZCx58tY39irJ2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/include/libpmemobj++/experimental/radix_tree.hpp#L1395)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

...meaning (to the user)..what?
</blockquote></details>

Done.
___
*[tests/radix/radix_tx_abort.cpp, line 432 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MGrinBv108Y6vMc4xR2:-MHFTuqz2SX4iP8wKW6K:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a6a7e0f57a542bfb3747dc44e52361965dcd50e4/tests/radix/radix_tx_abort.cpp#L432)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also implement try_emplace and insert tests here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-15 07:58 UTC, igchor reviewed
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: all files reviewed, 9 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1570 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MHFkWxJ4YDKcQAvyEuV:-MHFkWxJ4YDKcQAvyEuW:b-iajwk8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12680a68650c9639ceb8b8c19e9aab2c372e18f1/include/libpmemobj++/experimental/radix_tree.hpp#L1570)):*
> ```cpp
> radix_tree<Key, Value, BytesView>::insert_or_assign(K &&k, M &&obj)
> {
> 	auto ret = try_emplace(std::move(k), std::forward<M>(obj));
> ```

I believe it should be std::forward, not std::move. K here is a universal reference, not an rvalue reference.


<!-- Sent from Reviewable.io -->

2020-09-15 08:00 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: all files reviewed, 10 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 170 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MHFlitQ4EIai-A9j8g7:-MHFlitQ4EIai-A9j8g8:b-vo1gb0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12680a68650c9639ceb8b8c19e9aab2c372e18f1/include/libpmemobj++/experimental/radix_tree.hpp#L170)):*
> ```cpp
> 			     Args &&... args);*/
> 	template <typename K, typename BV = BytesView, class... Args>
> 	auto try_emplace(K &&k, Args &&... args) -> typename std::enable_if<
> ```

I believe you can leave the link to the gcc issue here, in case someone will want to refactor this code in future (The issue is why we are forced to check for the type quality).


<!-- Sent from Reviewable.io -->

2020-09-15 08:25 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847)* status: 21 of 22 files reviewed, 10 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 170 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MHFlitQ4EIai-A9j8g7:-MHFrZiO3pIOcpy08Gdu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12680a68650c9639ceb8b8c19e9aab2c372e18f1/include/libpmemobj++/experimental/radix_tree.hpp#L170)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe you can leave the link to the gcc issue here, in case someone will want to refactor this code in future (The issue is why we are forced to check for the type quality).
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1570 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-MHFkWxJ4YDKcQAvyEuV:-MHFr_Q60dTpyz6v-ZZv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12680a68650c9639ceb8b8c19e9aab2c372e18f1/include/libpmemobj++/experimental/radix_tree.hpp#L1570)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe it should be std::forward, not std::move. K here is a universal reference, not an rvalue reference.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-15 09:27 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/847#-:-MHG4kmx7f6RNTQabEBQ:bnfp4nl)* status: 21 of 22 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-09-15 10:08 UTC, merged