Add conversion operator to basic_string
pmem/libpmemobj-cpp pull request #865
Opened 2020-09-11 14:19 UTC by KFilipek

This PR will introduce following:
﻿- Add conversion operator to pmem::obj::string
- Extend tests according to changes in pmem::obj::string

2020-09-11 14:42 UTC, igchor requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 296 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-MGxbPfB8jVEExpDmB6P:-MGxbPfB8jVEExpDmB6Q:bu89asu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46db5637bc92342e3c99c665514b0fec86b73a4a/include/libpmemobj++/container/basic_string.hpp#L296)):*
> ```cpp
> 	void swap(basic_string &other);
> 
> 	operator basic_string_view<CharT, Traits>();
> ```

this function should be marked as const
___
*[include/libpmemobj++/container/basic_string.hpp, line 4068 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-MGxbSMc6PDKtR8vVuZO:-MGxbSMc6PDKtR8vVuZP:b1ta9t0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46db5637bc92342e3c99c665514b0fec86b73a4a/include/libpmemobj++/container/basic_string.hpp#L4068)):*
> ```cpp
> basic_string<CharT, Traits>::operator basic_string_view<CharT, Traits>()
> {
> 	return basic_string_view<CharT, Traits>(data(), length());
> ```

please use cdata() or c_str() instead of data() (for data, we might do a snapshot)


<!-- Sent from Reviewable.io -->

2020-09-13 10:10 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/container/basic_string.hpp, line 296 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-MGxbPfB8jVEExpDmB6P:-MH5wUmf7i-g2sfun-Ms:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46db5637bc92342e3c99c665514b0fec86b73a4a/include/libpmemobj++/container/basic_string.hpp#L296)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this function should be marked as const
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/basic_string.hpp, line 4068 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-MGxbSMc6PDKtR8vVuZO:-MH5wVUC9ts_5XCvc9_2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46db5637bc92342e3c99c665514b0fec86b73a4a/include/libpmemobj++/container/basic_string.hpp#L4068)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please use cdata() or c_str() instead of data() (for data, we might do a snapshot)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-14 08:34 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-:-MHAk0Fg-SFqxjgFAEze:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-14 12:55 UTC, szyrom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/865#-:-MHBfjeB6Si5RuNx653m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-14 12:55 UTC, merged