Introduce flat transaction class and change containers' behavior
pmem/libpmemobj-cpp pull request #932
Opened 2020-10-12 13:51 UTC by igchor

By using flat_transaction user can disable automatic tx abort in case of
any failure. Error handling can be then done using exceptions.

If an exception is caught inside of the transaction then the transaction
simply commits. Otherwise, exception is ignored by all inner transactions
and propagated to the outer one which calls pmemobj_tx_abort().

This patch also changes the behavior of all containers' transnational methods.
Now, they do not cause an abort on failure but only throw an exception. This
can be changed by setting a macro.

Requires: https://github.com/pmem/pmdk/pull/4654

Closes https://github.com/pmem/libpmemobj-cpp/issues/516

2020-10-12 13:55 UTC, igchor commented
For now, I changed all occurrences of transaction:: to flat_transaction in our headers. This should allow using our containers (including segment_vector) by users without changing user's code nor behavior (apart from containers' method behavior). This change is problematic as we will have to always use flat_transaction everywhere in our code (some static analyzer for that?). The alternative is to use `transaction = flat_transaction` as default but that will silently change error handling for all client code.

2020-11-03 12:20 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 16 of 18 files reviewed, 11 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/README.md, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtpbE1AGgEm5Sdt3j3:-MLD26Kr1SzXFVr5U8mI:boq2fts) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/README.md#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you wanted to put 2 links here?
</blockquote></details>

yes, but I'm not sure if this is ok. I may just link to the transaction page which has references to both basic and flat txs
___
*[include/libpmemobj++/transaction.hpp, line 96 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKuH76I5eV3RfS9H_3K:-MLD0AM44k_zxtvFf8fd:b-tytq6a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's the behavior when it is not a flat transaction? can we change it using `LIBPMEMOBJ_CPP_FLAT_TX_USE_FAILURE_RETURN` ?
</blockquote></details>

The behavior is as it is now - each transactional method failure results in an abort. I don't think there is much sense in allowing anything different in such case because for non-flat transaction something like:

pmem::obj::transaction::run(pop, [&] {
     make_persistent<huge>(); 
});

will abort the tx anyway due to the exception catched in run.

That said, the behavior can still be changed by using pmemobj_tx_set_failure_behavior but I'd prefer not to document that at the momenet.


<!-- Sent from Reviewable.io -->

2020-11-09 15:52 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 16 of 18 files reviewed, 10 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/README.md, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtpbE1AGgEm5Sdt3j3:-MLhf2EIAkfV0k_41JRZ:b-cdu4xl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/README.md#L80)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

yes, but I'm not sure if this is ok. I may just link to the transaction page which has references to both basic and flat txs
</blockquote></details>

link to a transaction page should be fine, I guess.
If you want to put two links, just make it explicit `[flat_tx](@ref pmem::obj::flat_tx) or [basic_tx](@ref pmem::obj::basic_tx)`


<!-- Sent from Reviewable.io -->

2020-11-16 13:08 UTC, KFilipek reviewed
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/transaction.hpp, line 96 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMFzAz20eKtUVge-fCo:-MMFzAz20eKtUVge-fCp:b-vlym06) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/transaction.hpp#L96)):*
> ```cpp
> 			}
> 
> 			if (IsFlat && LIBPMEMOBJ_CPP_FLAT_TX_USE_FAILURE_RETURN)
> ```

is_flat is better IMO
___
*[tests/transaction/transaction.cpp, line 1041 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMG-1im9_0YYPRSUXgy:-MMG-1im9_0YYPRSUXgz:bprvco4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/tests/transaction/transaction.cpp#L1041)):*
> ```cpp
> 					UT_ASSERT(0);
> 				} catch (pmem::transaction_scope_error &) {
> ```

remove empty line or comment


<!-- Sent from Reviewable.io -->

2020-11-17 09:46 UTC, szyrom reviewed
> Reviewed 17 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor)

___
*[examples/transaction/transaction.cpp, line 263 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKWYC95xmwrgU9CJJp:-MMKWYC95xmwrgU9CJJq:b-ue6s2o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L263)):*
> ```cpp
> 				 * basic_transaction). */
> 				assert(proot->count == 2);
> 				throw;
> ```

in order to better illustrate this example, I would suggest adding a comment here that this is pmem::transaction_error
___
*[examples/transaction/transaction.cpp, line 272 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKWkxPD00Hkc6d181E:-MMKWkxQ16CTJO0xpxxy:b70nx8m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L272)):*
> ```cpp
> 	} catch (...) {
> 		/* some other exception thrown, tx aborted
> 		 * reacquire locks if necessary */
> ```

... and here maybe assert(false) since we do not expect to get there
___
*[examples/transaction/transaction.cpp, line 300 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKYyGEAULiUPk4Jreq:-MMKYyGEAULiUPk4Jrer:bknc7cw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L300)):*
> ```cpp
> 		 * an exception. This exception will be propagated to the
> 		 * outermost transaction and only then the abort will happen.
> 		 * This allows C++ to call ptr1 in A class destructor and unwind
> ```

what is a danger in this example by not unwinding the stack correctly? can we better illustrate the danger?


<!-- Sent from Reviewable.io -->

2020-11-20 10:50 UTC, szyrom reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor)

___
*[examples/transaction/transaction.cpp, line 300 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKYyGEAULiUPk4Jreq:-MM_GZfW22q50Lf_tYiv:bru32ob) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L300)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

what is a danger in this example by not unwinding the stack correctly? can we better illustrate the danger?
</blockquote></details>

nvm, I understand now - maybe its a good idea to illustrate this 


<!-- Sent from Reviewable.io -->

2020-11-20 13:49 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 15 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtk7FJ6GqT9rtFlGyE:-MM_b1Tk3t2R6FXfCZ1Q:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/README.md#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`in this [file]`, perhaps
</blockquote></details>

Done.
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtkCQ55c42XooQdLq_:-MM_b786BMbW5YuU62v5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/README.md#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `.` at the end of the line
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 263 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKWYC95xmwrgU9CJJp:-MM_bX-NEO5Peikocton:b-cyup1t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L263)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

in order to better illustrate this example, I would suggest adding a comment here that this is pmem::transaction_error
</blockquote></details>

It's std::runtime_exception (the one which we thrown above) but I wanted to make it a more general construct. In this particular case onle one example can be thrown, but in general the behavior is the same for all of them (hence I used `...`).
___
*[examples/transaction/transaction.cpp, line 272 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKWkxPD00Hkc6d181E:-MM_btLKD6eyvEppErm0:b-3xfeqb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L272)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

... and here maybe assert(false) since we do not expect to get there
</blockquote></details>

Well, we don't expect it here, but in general this exception can happen (and this example shows most common error handling).
___
*[examples/transaction/transaction.cpp, line 293 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKu-uxV4swVSZ-APRam:-MM_cTSEEvRL0b6N_BvK:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L293)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`flat one` -> `flat transaction`
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 294 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtxrAUDPRNumh-fJIQ:-MM_cZuu-w1MIiZUNuY-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L294)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

terminate -> termination
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 300 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMKYyGEAULiUPk4Jreq:-MM_q5TM1a_U-khXlOXc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L300)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

nvm, I understand now - maybe its a good idea to illustrate this 
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 385 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKu3EgG5HHIImq3ewEx:-MM_qBOp4QIPKJd_dPMo:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L385)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`inner_flat`? did you mean `(flat) inner_tx will...`?
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 385 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKu9vT96CCqKz2nuuxs:-MM_qCB98fttAmvxauHT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/examples/transaction/transaction.cpp#L385)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

explcit -> explicit
</blockquote></details>

Done.
___
*[include/libpmemobj++/README.md, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtpbE1AGgEm5Sdt3j3:-MM_ucUr7fZZDqaY6Ml3:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/README.md#L80)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

link to a transaction page should be fine, I guess.
If you want to put two links, just make it explicit `[flat_tx](@ref pmem::obj::flat_tx) or [basic_tx](@ref pmem::obj::basic_tx)`
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 96 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMFzAz20eKtUVge-fCo:-MM_qNdG68eOOoc5LFoI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

is_flat is better IMO
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 105 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKu73xWCz0_5jzpVXsZ:-MM_qRTu5l_6y8bv_6IO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/transaction.hpp#L105)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`the outermost`
</blockquote></details>

Done.
___
*[tests/transaction/transaction.cpp, line 1031 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKuWVsC-ExdYEMz07Y_:-MM_qu12AtJUUIcY2kOe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/tests/transaction/transaction.cpp#L1031)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add a short test description, test name is rather non descriptive
</blockquote></details>

Done.
___
*[tests/transaction/transaction.cpp, line 1041 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMG-1im9_0YYPRSUXgy:-MM_qxVN2zF09SCno06M:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/tests/transaction/transaction.cpp#L1041)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove empty line or comment
</blockquote></details>

Done.
___
*[tests/transaction/transaction_basic.cpp, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKuVDHm0enPkkpuW7Jl:-MM_reXS64bl9C0nlr3t:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/tests/transaction/transaction_basic.cpp#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps you can move this into a sep. helper header for tx tests...?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-20 16:09 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 8 of 18 files reviewed, 25 unresolved discussions (waiting on @igchor, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[README.md, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaGQ9G9I_gJak4_4Wl:-MMaGQ9G9I_gJak4_4Wm:b-96kq51) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/README.md#L18)):*
> ```Markdown
> 
> # Compatibility note #
> In libpmemobj 1.12 we introduced a new transaction handler type: [pmem::obj::flat_transaction](https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1flat__transaction.html). By defining LIBPMEMOBJ_CPP_USE_FLAT_TRANSACTION you can make pmem::obj::transaction to be an alias to pmem::obj::flat_transaction. In 1.12 we have also changed the default behavior of containers' transactional methods. Now, in  case of any failure within such method, the outer transaction (if any) will not be immediately aborted. Instead, an exception will be thrown, which will lead to transaction abort only if it's not caught before tx scope ends. To change the behavior to the old one, you can set LIBPMEMOBJ_CPP_FLAT_TX_USE_FAILURE_RETURN macro to 0. Be aware that the old behavior can lead to segfaults in some cases (see tx_nested_struct_example in this [file](examples/transaction/transaction.cpp)).
> ```

perhaps make it explicit here `it's not caught before **outer** tx scope ends`
___
*[examples/transaction/transaction.cpp, line 267 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaGrcn5iFvnUCi6LZx:-MMaGrcn5iFvnUCi6LZy:bwvurrw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L267)):*
> ```cpp
> 		});
> 	} catch (pmem::transaction_error &) {
> 		/* an internal transaction error occurred, tx aborted
> ```

perhaps something more precise, like `tx aborted` -> `outer tx aborted just now.` (pls, also add `.` at the end)
___
*[examples/transaction/transaction.cpp, line 271 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaH30s99Xn8Q5LW3nn:-MMaH30s99Xn8Q5LW3no:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L271)):*
> ```cpp
> 		assert(proot->count == 0);
> 	} catch (...) {
> 		/* some other exception thrown, tx aborted
> ```

.
___
*[examples/transaction/transaction.cpp, line 324 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaE3zp82mWov_1hLdn:-MMaE3zp82mWov_1hLdo:blak9ak) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L324)):*
> ```cpp
> 		auto pop = pool_base(pmemobj_pool_by_ptr(this));
> 
> 		// Will result in crash!
> ```

**It would** result in **a** crash!
___
*[examples/transaction/transaction.cpp, line 342 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaEFEq3i6cHF0VYOmn:-MMaEFEq3i6cHF0VYOmo:b-o5dm1i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L342)):*
> ```cpp
> 	struct root {
> 		persistent_ptr<A> ptr1;
> 		persistent_ptr<B> ptr2;
> ```

perhaps rename to `ptrA` & `ptrB`
___
*[examples/transaction/transaction.cpp, line 353 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaD85R858p8es4Ix00:-MMaD85R858p8es4Ix01:bo8dnet) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L353)):*
> ```cpp
> 
> 	try {
> 		// Will result in a crash!
> ```

It would
___
*[examples/transaction/transaction.cpp, line 376 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaEiVS1_U06ux4htSc:-MMaEiVS1_U06ux4htSd:bj7z6py) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L376)):*
> ```cpp
> 		 *
> 		 * If we'd use basic_transaction the allocation failure, apart
> 		 * from throwing an exception would also cause the transaction
> ```

an exception **,** (this `apart..` sentence was an inclusion, so it should be surrounded with commas, I believe)
___
*[examples/transaction/transaction.cpp, line 389 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFHGcD3aNL7owInOh:-MMaFHGcD3aNL7owInOi:bqhh4zw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L389)):*
> ```cpp
> 		 * means that the transaction is still in WORK stage during
> 		 * stack unwinding. Only after it completes, the transaction is
> 		 * aborted (it's happending at the outermost level, when exiting
> ```

`happending` misspell
___
*[examples/transaction/transaction.cpp, line 401 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFmhLDAzV_brXCq9b:-MMaFmhLDAzV_brXCq9c:b-8xvjzl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L401)):*
> ```cpp
> 		/* Running create_b can be done both within basic and flat
> 		 * transaction. However, note that the transaction used in the B
> 		 * constructor MUST be flat_transaction. This is because
> ```

be a flat_transaction
___
*[examples/transaction/transaction.cpp, line 404 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFupi2uRY5JsbAgn4:-MMaFupi2uRY5JsbAgn5:b-nccvja) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L404)):*
> ```
> performend
> ```
misspell
___
*[examples/transaction/transaction.cpp, line 405 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFxlh5KDn6LP9rtKF:-MMaFxlh5KDn6LP9rtKG:bhd7lex) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L405)):*
> ```cpp
> 		 * exception. Instead it passes it to the outermost transaction
> 		 * - the abort is performend at that outermost level. In case of
> 		 * basic_transaction the abort would be done within the B ctor
> ```

a basic_transaction
___
*[examples/transaction/transaction.cpp, line 458 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaJu6j0Z5KizJVgnpc:-MMaJu6j0Z5KizJVgnpd:bn44g61) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L458)):*
> ```cpp
> 			 * flat_transaction::manual is destroyed because of an
> 			 * active exception.
> 			 */
> ```

I've read this comment once more and I'm not sure if I get it ;-) flat_transaction::manual will not abort, even if some exception occur here... and it will abort just only in the outermost tx...?
___
*[examples/transaction/transaction.cpp, line 465 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaL14E0SVjcLSvAJt3:-MMaL14E0SVjcLSvAJt4:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L465)):*
> ```cpp
> 		transaction::commit();
> 	} catch (pmem::transaction_error &) {
> 		/* an internal transaction error occurred, tx aborted
> ```

.
___
*[examples/transaction/transaction.cpp, line 468 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaL227515FWTMILjkA:-MMaL227515FWTMILjkB:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L468)):*
> ```cpp
> 		 * reacquire locks if necessary */
> 	} catch (...) {
> 		/* some other exception thrown, tx aborted
> ```

.
___
*[examples/transaction/transaction.cpp, line 473 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaLJGH1GAekfrypnI-:-MMaLJGH1GAekfrypnI0:b-stnvc7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb22 [...]

2020-11-20 16:28 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 8 of 18 files reviewed, 25 unresolved discussions (waiting on @igchor, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[include/libpmemobj++/README.md, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MKtpbE1AGgEm5Sdt3j3:-MMaTuvbC2HfRc36SqOr:b-j04qa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/217ff7363e90905f8d9b37d26d023274c1ac7b0c/include/libpmemobj++/README.md#L80)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've generated the docs and the link looks good.


<!-- Sent from Reviewable.io -->

2020-11-24 11:43 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 8 of 18 files reviewed, 23 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 267 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaGrcn5iFvnUCi6LZx:-MMu0tYz7aT_ojgaw8hy:bhx6xqq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L267)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps something more precise, like `tx aborted` -> `outer tx aborted just now.` (pls, also add `.` at the end)
</blockquote></details>

Hm, I'm not sure if "outer tx aborted" is 
___
*[examples/transaction/transaction.cpp, line 271 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaH30s99Xn8Q5LW3nn:-MMu0tLX8NNNO5bWlHDG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L271)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 324 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaE3zp82mWov_1hLdn:-MMu1IAvERFYRgSEgbl4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L324)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**It would** result in **a** crash!
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 342 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaEFEq3i6cHF0VYOmn:-MMu1NHj18q5QcpubnQ0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L342)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps rename to `ptrA` & `ptrB`
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 353 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaD85R858p8es4Ix00:-MMu1Q-H1mf67BL2DcBb:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L353)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

It would
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 376 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaEiVS1_U06ux4htSc:-MMu1VO3Chf_abjMqVKM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L376)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

an exception **,** (this `apart..` sentence was an inclusion, so it should be surrounded with commas, I believe)
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 389 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFHGcD3aNL7owInOh:-MMu1gxuANI9QWFXWrsU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L389)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`happending` misspell
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 401 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFmhLDAzV_brXCq9b:-MMu1jdX2iKgLNV-q8G5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L401)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

be a flat_transaction
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 404 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFupi2uRY5JsbAgn4:-MMu1mO13aV7waCMgjqP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L404)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> performend
> ```
misspell
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 405 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaFxlh5KDn6LP9rtKF:-MMu1oY-8L9IhFbNBzCO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L405)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a basic_transaction
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 458 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaJu6j0Z5KizJVgnpc:-MMu1xOV1ZL_S8NNjZG6:bdpwg9o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L458)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I've read this comment once more and I'm not sure if I get it ;-) flat_transaction::manual will not abort, even if some exception occur here... and it will abort just only in the outermost tx...?
</blockquote></details>

I've added some extra info
___
*[examples/transaction/transaction.cpp, line 465 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaL14E0SVjcLSvAJt3:-MMu2VhgDAgjMd3MOF1B:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L465)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 468 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaL227515FWTMILjkA:-MMu2VwO45O-f_jNTkQ6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L468)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 573 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaOTvK3RPCsme-VwSc:-MMu2h4vBhXXaEdUulQt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/include/libpmemobj++/transaction.hpp#L573)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`to rather use` or `to use pmem::obj::flat_transaction instead.`
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 828 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaLteDALlUY_wxYA78:-MMu3-9lE6L4LThGvz7U:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/include/libpmemobj++/transaction.hpp#L828)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you mean `manual_flat_tx_example` ? and it (by itself) doesn't show the difference, I guess

also, perhaps make this snippet the last one, the next two seems to be better examples
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 840 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaP5Zr75rXQ7LGT7_x:-MMu3-a626DV9H9YfItr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6d [...]

2020-11-24 14:48 UTC, pbalcer reviewed
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 8 of 18 files reviewed, 26 unresolved discussions (waiting on @igchor, @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 261 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMugMy3EF0MF9rfohR1:-MMugMy3EF0MF9rfohR2:bba95su) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/examples/transaction/transaction.cpp#L261)):*
> ```cpp
> 			} catch (...) {
> 				/* Transaction is not aborted yet (unlike for
> 				 * basic_transaction). */
> ```

`assert(tx_state() == WORK);`
? (not sure what's the C++ syntax)
___
*[examples/transaction/transaction.cpp, line 461 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuh1yi4aTbDAe7e0BG:-MMuh1yi4aTbDAe7e0BH:bxw4fgv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/examples/transaction/transaction.cpp#L461)):*
> ```cpp
> 			 * there are manual transaction objects). In case of
> 			 * flat_transaction, the commit has to be called only
> 			 * once, at the outermost level.
> ```

I don't like this distinction.
Can the commit be called at every level? If not, then this makes code nesting difficult.
___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuhow6BEAsw0LVQGtJ:-MMuhow6BEAsw0LVQGtK:blkic37) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/include/libpmemobj++/transaction.hpp#L96)):*
> ```cpp
> 			}
> 
> 			if (is_flat &&
> ```

can't you just abstract this away somehow? having an `if class = this {} else {}` seems odd ;)


<!-- Sent from Reviewable.io -->

2020-11-25 13:44 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 6 of 18 files reviewed, 26 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 261 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMugMy3EF0MF9rfohR1:-MMz_bcbBVF-ZyttapbI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/examples/transaction/transaction.cpp#L261)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

`assert(tx_state() == WORK);`
? (not sure what's the C++ syntax)

</blockquote></details>

Done.
___
*[examples/transaction/transaction.cpp, line 461 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuh1yi4aTbDAe7e0BG:-MMzZOoo6iGw2hDgGdfR:b-6nb55c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/examples/transaction/transaction.cpp#L461)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I don't like this distinction.
Can the commit be called at every level? If not, then this makes code nesting difficult.

</blockquote></details>

You can call commit at each level - you just don't have to. I updated the comment to make it more clear.
___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuhow6BEAsw0LVQGtJ:-MMzdHkv3omhxGl5d_5Z:b-i5iwce) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

can't you just abstract this away somehow? having an `if class = this {} else {}` seems odd ;)
</blockquote></details>

Done. It' still basically an if, but not in compile time ;d Or did you mean some other approach?


<!-- Sent from Reviewable.io -->

2020-12-02 09:46 UTC, pbalcer requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 6 of 18 files reviewed, 24 unresolved discussions (waiting on @igchor, @KFilipek, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuhow6BEAsw0LVQGtJ:-MNXpwLL9xo4vGYNy4Ij:bkze2c0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done. It' still basically an if, but not in compile time ;d Or did you mean some other approach?
</blockquote></details>

I was thinking more about just having an empty virtual function in the base class, and implementing this in the flat_transaction class.


<!-- Sent from Reviewable.io -->

2020-12-02 10:11 UTC, KFilipek reviewed
> Reviewed 8 of 13 files at r2, 3 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 26 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 355 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXuICI2QTQid6qnAN_:-MNXuICI2QTQid6qnANa:b-e6oy0d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/examples/transaction/transaction.cpp#L355)):*
> ```cpp
> 	try {
> 		// It would result in a crash!
> 		// basic_transaction::run(pop, create_a);
> ```

I think it will be removed in the future
___
*[tests/transaction/transaction_basic.cpp, line 10 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvm7w9gzLc4hTq13W:-MNXvm7xBmX3p2kHc812:b-k3avni) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_basic.cpp#L10)):*
> ```cpp
> #include <libpmemobj++/pool.hpp>
> 
> #include "transaction.hpp"
> ```

why not #include <libpmemobj++/transaction.hpp>?
___
*[tests/transaction/transaction_flat.cpp, line 7 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvTud-lr4xBlSxEwI:-MNXvTud-lr4xBlSxEwJ:bzej6a4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_flat.cpp#L7)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> #include <libpmemobj/iterator_base.h>
> #include <libpmemobj++/make_persistent.hpp>
> #include <libpmemobj++/persistent_ptr.hpp>
> #include <libpmemobj++/pool.hpp>
> ```
</details>

Please reorder the headers to looks like above
___
*[tests/transaction/transaction_flat.cpp, line 12 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvGBh201rH-1JPA3T:-MNXvGBiCAvr3fJtnRip:b-k3avni) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_flat.cpp#L12)):*
> ```cpp
> #include <libpmemobj/iterator_base.h>
> 
> #include "transaction.hpp"
> ```

why not #include <libpmemobj++/transaction.hpp>?


<!-- Sent from Reviewable.io -->

2020-12-02 10:15 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 26 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMuhow6BEAsw0LVQGtJ:-MNXtX2t8iKsvqojC47h:b-m6megz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fb04acc0d4daa245086b93cb61822fcc54dc7acf/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I was thinking more about just having an empty virtual function in the base class, and implementing this in the flat_transaction class.
</blockquote></details>

For that, I'd have to actually implement a base class for flat_transaction::manual (I can't call virtual function on transaction_base which is an outer class). And it would also broke run() method from transaction_base class. There, I use manual class directly which is always transaction_base::manual. I'd have to add some factory function or just re implement run() in flat_transaction class. I'm not sure if it's worth it ... and it's probably slightly faster this way ;d


<!-- Sent from Reviewable.io -->

2020-12-02 10:22 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 17 of 18 files reviewed, 26 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 355 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXuICI2QTQid6qnAN_:-MNXwv00AtQamlGYrhVo:bc7ouou) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/examples/transaction/transaction.cpp#L355)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think it will be removed in the future
</blockquote></details>

Probably not until libpmemobj-cpp 2.0
___
*[tests/transaction/transaction_basic.cpp, line 10 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvm7w9gzLc4hTq13W:-MNXwkCi5v2Ia6K4W4O8:b-brcmt5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_basic.cpp#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

why not #include <libpmemobj++/transaction.hpp>?
</blockquote></details>

Because it;s different file, I'm including the tests/transaction/transaction.hpp here
___
*[tests/transaction/transaction_flat.cpp, line 7 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvTud-lr4xBlSxEwI:-MNXyJcvBhQEM2bETtmj:bv5l5y2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_flat.cpp#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include <libpmemobj/iterator_base.h>
> #include <libpmemobj++/make_persistent.hpp>
> #include <libpmemobj++/persistent_ptr.hpp>
> #include <libpmemobj++/pool.hpp>
> ```
Please reorder the headers to looks like above
</blockquote></details>

Done. (but with the ordering enforced of clang-format)
___
*[tests/transaction/transaction_flat.cpp, line 12 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNXvGBh201rH-1JPA3T:-MNXwt8fAmKSLf7sP7_j:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6783d981cf23d2f5d4fe16f4ea3daf541bd81562/tests/transaction/transaction_flat.cpp#L12)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

why not #include <libpmemobj++/transaction.hpp>?
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2020-12-07 11:52 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 13 files at r2, 3 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 17 of 18 files reviewed, 13 unresolved discussions (waiting on @igchor, @KFilipek, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 267 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaGrcn5iFvnUCi6LZx:-MNwSNST03p3z7D3mPnS:b-ecfysq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L267)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I'm not sure if "outer tx aborted" is 
</blockquote></details>

you're not sure... what? it looks like you didn't end the sentence above
___
*[examples/transaction/transaction.cpp, line 458 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaJu6j0Z5KizJVgnpc:-MNwU3YR3X_K7OSUsUqd:b-ucfknh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L458)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I've added some extra info
</blockquote></details>

Thanks!
___
*[examples/transaction/transaction.cpp, line 464 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwTsAf2y4aXRANiJez:-MNwTsAg8bRBCJ-oQMmR:bkprh4s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/examples/transaction/transaction.cpp#L464)):*
> ```cpp
> 			 * have to call commit() at each level (as many times as
> 			 * there are manual transaction objects). In case of
> 			 * flat_transaction, the commit has to be called only
> ```

**a** flat_transaction
___
*[tests/transaction/transaction.cpp, line 18 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwfond6xPAA0kiAjs8:-MNwfond6xPAA0kiAjs9:b-y9sgyk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction.cpp#L18)):*
> ```cpp
> #include <libpmemobj++/shared_mutex.hpp>
> 
> #include "transaction.hpp"
> ```

you can have this include just next to `"unittest.hpp"`
___
*[tests/transaction/transaction_basic.cpp, line 346 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwj3avE4Odjh9QDvY1:-MNwj3avE4Odjh9QDvY2:b-c1bjv7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction_basic.cpp#L346)):*
> ```cpp
> 	UT_ASSERT(r->p1 == nullptr);
> }
> void
> ```

pls add an empty line
___
*[tests/transaction/transaction_basic.cpp, line 363 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwjV-b9z88aqYaoamn:-MNwjV-b9z88aqYaoamo:b2i7u29) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction_basic.cpp#L363)):*
> ```cpp
> 	test_tx_nested_behavior_scope<nvobj::transaction::manual,
> 				      nvobj::flat_transaction::manual>(pop);
> 	test_tx_nested_behavior_scope<nvobj::transaction::automatic,
> ```

isn't automatic supported only from some C++ standard (17) ?


<!-- Sent from Reviewable.io -->

2020-12-07 12:52 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @pbalcer, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-07 12:54 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 464 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwTsAf2y4aXRANiJez:-MNxFwn7BzBq7-c6_Qea:b-125oy2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/examples/transaction/transaction.cpp#L464)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**a** flat_transaction
</blockquote></details>

Not 'a', because 'the' flat_transaction was mentioned earlier


<!-- Sent from Reviewable.io -->

2020-12-07 14:25 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor, @KFilipek, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 464 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwTsAf2y4aXRANiJez:-MNx_TVmCYswPYdwoBEo:bvnhz9a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/examples/transaction/transaction.cpp#L464)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Not 'a', because 'the' flat_transaction was mentioned earlier
</blockquote></details>

I disagree
1. I can't see that we've mentioned "flat_tx" class in this section
2. it is any flat_tx, not the one specific instance or something

hence, I'd put here "a flat_tx"


<!-- Sent from Reviewable.io -->

2020-12-08 09:49 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk, @pbalcer, and @szyrom)

___
*[examples/transaction/transaction.cpp, line 267 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MMaGrcn5iFvnUCi6LZx:-MO0iZc-8jhvjDx3qUI-:b-3z2jr2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb222d32f266323706bb6dec662ceae983e7cc54/examples/transaction/transaction.cpp#L267)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you're not sure... what? it looks like you didn't end the sentence above
</blockquote></details>

I think I just didn't remove my previous answer. It's ok now, right?
___
*[examples/transaction/transaction.cpp, line 464 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwTsAf2y4aXRANiJez:-MO0j-4n1yZTS_lK9RA7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/examples/transaction/transaction.cpp#L464)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I disagree
1. I can't see that we've mentioned "flat_tx" class in this section
2. it is any flat_tx, not the one specific instance or something

hence, I'd put here "a flat_tx"
</blockquote></details>

Done.
___
*[tests/transaction/transaction.cpp, line 18 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwfond6xPAA0kiAjs8:-MO0jDW7CjKewau1TwCs:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction.cpp#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can have this include just next to `"unittest.hpp"`
</blockquote></details>

Done.
___
*[tests/transaction/transaction_basic.cpp, line 346 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwj3avE4Odjh9QDvY1:-MO0jKpm9_ehONuzGR-j:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction_basic.cpp#L346)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add an empty line
</blockquote></details>

Done.
___
*[tests/transaction/transaction_basic.cpp, line 363 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwjV-b9z88aqYaoamn:-MO0ja8l5t-0OSBr2vJI:b-12lbep) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction_basic.cpp#L363)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't automatic supported only from some C++ standard (17) ?
</blockquote></details>

Yes, because of std::uncaught_exceptions, but in the test, for previous C++ versions we just mock the uncaught_exceptions (see tests/transaction/transaction.hpp)


<!-- Sent from Reviewable.io -->

2020-12-08 15:22 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @KFilipek, @pbalcer, and @szyrom)

___
*[tests/transaction/transaction_basic.cpp, line 363 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-MNwjV-b9z88aqYaoamn:-MO1uXLO0JLQ_QR5ejK6:bwadipt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3fe34aedbb9c93d5921f0806be1a2491cf96a083/tests/transaction/transaction_basic.cpp#L363)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, because of std::uncaught_exceptions, but in the test, for previous C++ versions we just mock the uncaught_exceptions (see tests/transaction/transaction.hpp)
</blockquote></details>

och, ok. I thought we should ifdef it.


<!-- Sent from Reviewable.io -->

2020-12-14 12:23 UTC, JanDorniak99 reviewed
> Reviewed 6 of 18 files at r1, 4 of 13 files at r2, 2 of 5 files at r3, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: 16 of 18 files reviewed, 4 unresolved discussions (waiting on @KFilipek, @pbalcer, and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-14 13:59 UTC, pbalcer approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-:-MOWYBVl5fmRqFPjU85D:bnfp4nl)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-14 14:29 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932#-:-MOWe23g2_8NyKfDEt3I:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-14 15:16 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/932)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)



<!-- Sent from Reviewable.io -->

2020-12-16 09:37 UTC, merged