CMAKE: add ccache support
pmem/libpmemobj-cpp pull request #933
Opened 2020-10-12 16:28 UTC by karczex

On my not-so-fast NUC it improves build time:

clean build without ccache (and first build with ccache):
real	6m15.062s
user	19m45.633s
sys	1m48.421s

second clean build with ccache:
real	0m48.836s
user	1m48.793s
sys	0m35.407s

It's not needed for CI, as builds are done in containers and do not share
ccache anyway

2020-10-12 17:47 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSuZ-Q5HJi-HrqTh2c:-MJSuZ-Q5HJi-HrqTh2d:bxtn6zy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
> ```CMake
> find_program(CCACHE_FOUND ccache)
> if(CCACHE_FOUND)
>     set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
> ```

use tab instead of spaces to indent ;)
___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSv0wm8fD2g1MSuo9O:-MJSv0wm8fD2g1MSuo9P:bfvgefg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
> ```CMake
> find_program(CCACHE_FOUND ccache)
> if(CCACHE_FOUND)
>     set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
> ```

perhaps add a short comment to explain this line, pls
___
*[CMakeLists.txt, line 87 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSuq3r0KSn8QVCVn3O:-MJSuq3r0KSn8QVCVn3P:b-r5ygyt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L87)):*
> ```CMake
> if(CCACHE_FOUND)
>     set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
> endif(CCACHE_FOUND)
> ```

make it just `endif()`


<!-- Sent from Reviewable.io -->

2020-10-12 17:53 UTC, lukaszstolarczuk reviewed
och, and in commit message, pls make "CMAKE" lowercase ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-:-MJSwZkWAKZuV-n7CkYR:b-ebbd5a)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2020-10-13 08:46 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJW7nvZ9SRc3HPyLrDe:-MJW7nv_-wzRMAFEFSZn:bb2g5ln) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
> ```CMake
> find_program(CCACHE_FOUND ccache)
> if(CCACHE_FOUND)
>     set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
> ```

Shouldn't this be parameterized somehow? So that, user can disable ccache


<!-- Sent from Reviewable.io -->

2020-10-13 10:25 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSuZ-Q5HJi-HrqTh2c:-MJWN6K45bcttMtFXQEw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use tab instead of spaces to indent ;)
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSv0wm8fD2g1MSuo9O:-MJWUSM6CuSOcm1LaC59:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add a short comment to explain this line, pls
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJW7nvZ9SRc3HPyLrDe:-MJWUTtP5e2NFXTn2z7u:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L86)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn't this be parameterized somehow? So that, user can disable ccache
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 87 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJSuq3r0KSn8QVCVn3O:-MJWUWKd865Ae706qZ-7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/343ea99474fe6fc32a6de771f53e3dfe113c1ddc/CMakeLists.txt#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it just `endif()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-13 11:54 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-:-MJWnygA0u33vlw5Y9tD:bnfp4nl)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-10-13 13:30 UTC, lukaszstolarczuk reviewed
also, please do the same change in pmemkv repo :)

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-:-MJX8sAE51a3z-Yxa3s1:bv83alg)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8DCJEta7DdlQggjT:-MJX8DCJEta7DdlQggjU:byico7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L53)):*
> ```CMake
> option(USE_ASAN "enable AddressSanitizer (debugging)" OFF)
> option(USE_UBSAN "enable UndefinedBehaviorSanitizer (debugging)" OFF)
> option(USE_CCACHE "Use ccache if is avialable in system" ON)
> ```

`if it is available in the system`
___
*[CMakeLists.txt, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8T5WARBpVvBCVLgf:-MJX8T5WARBpVvBCVLgg:b-s7b93g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L85)):*
> ```CMake
> option(INSTALL_RADIX_TREE "enable testing of pmem::obj::experimental::radix_tree" ON)
> 
> # Configure the ccache as compiler luncher
> ```

`launcher` :wink: 


<!-- Sent from Reviewable.io -->

2020-10-13 14:31 UTC, karczex commented
___
*[CMakeLists.txt, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8T5WARBpVvBCVLgf:-MJXMm772yyng4O7rz1e:bmw7q2d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`launcher` :wink: 
</blockquote></details>

that's how it ends if you do commits before meal :) 


<!-- Sent from Reviewable.io -->

2020-10-13 14:35 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8DCJEta7DdlQggjT:-MJXNhnB8H2TK6TMRrJh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`if it is available in the system`
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8T5WARBpVvBCVLgf:-MJXNjDm8YMnmHb_jSQB:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L85)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

that's how it ends if you do commits before meal :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-13 15:05 UTC, lukaszstolarczuk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJXUK7I8ZNGYSvhO8Er:-MJXUK7I8ZNGYSvhO8Es:b-vuokif) (no related file):*
as I commented previously - pls make "CMAKE" lowercase in commit message

---
___
*[CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8DCJEta7DdlQggjT:-MJXU3dz1eiygI3iQIPy:b-7tctrw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L53)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`available` :P


<!-- Sent from Reviewable.io -->

2020-10-14 07:08 UTC, szyrom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-:-MJ_vyI3CjR_txY6C4ZX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2020-10-14 10:13 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJXUK7I8ZNGYSvhO8Er:-MJa_uRI9LC1xlXHBUrf:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as I commented previously - pls make "CMAKE" lowercase in commit message
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-10-14 10:13 UTC, karczex commented
___
*[CMakeLists.txt, line 53 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933#-MJX8DCJEta7DdlQggjT:-MJaaVH34Y0Gp7CueFa7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/34a593cb1452f3f0f0ee7fe81a83d73e64c6918d/CMakeLists.txt#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`available` :P
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-14 10:37 UTC, lukaszstolarczuk approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/933)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-14 11:47 UTC, merged