string_view: implement access API and port libcxx tests
pmem/libpmemobj-cpp pull request #938
Opened 2020-10-16 09:44 UTC by KFilipek

- string_view: add string_view access API libcxx tests
- string_view: implement access API
- string_view: port LIBCXX access tests to use pmem::obj::string_view

2020-10-16 11:26 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-:-MJl9Gpl4PKLb3-7JmjX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 15:44 UTC, lukaszstolarczuk reviewed
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938)* status: all files reviewed, 9 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 166 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlwr4Q-acCOTdG0NG5:-MJlwr4Q-acCOTdG0NG6:bwtv826) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L166)):*
> ```cpp
>  * Returns count of characters stored in this pmem::obj::string_view data.
>  *
>  * @return pointer to C-like string (char *), it may not end with null
> ```

returns pointer to c-like string? (here and above)
___
*[include/libpmemobj++/string_view.hpp, line 206 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlx8mN8JQRgspdiqfg:-MJlx8mN8JQRgspdiqfh:b-allyn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L206)):*
> ```cpp
> 
> /**
>  * Returns reference to a last character in the view.
> ```

to **the** last char
___
*[include/libpmemobj++/string_view.hpp, line 219 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlxTxPBxDKdbH7X5k_:-MJlxTxPBxDKdbH7X5ka:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L219)):*
> ```cpp
> 
> /**
>  * Returns reference to a first character in the view.
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 220 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlx_Z-DqfS-PPnvWfF:-MJlx_Z-DqfS-PPnvWfG:b-t9m4yo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L220)):*
> ```cpp
> /**
>  * Returns reference to a first character in the view.
>  *
> ```

perhaps also worth mention what if empty() == true
___
*[tests/external/libcxx/string.view/string.view.access/at.pass.cpp, line 37 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlzqTjC_gCTm7mTftn:-MJlzqTk3jB_ly9gKv2T:b4qj8mz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/at.pass.cpp#L37)):*
> ```cpp
> 	}
> 
> #ifndef TEST_HAS_NO_EXCEPTIONS
> ```

I know it's ported from libcxx, but I'd remove this `if`. We throw exceptions in `at` and if we *ever* change it, this test will just fail... which is good, I guess
___
*[tests/external/libcxx/string.view/string.view.access/back.pass.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1PhoAMg-jGJAOSI4:-MJm1PhoAMg-jGJAOSI5:b-9ge731) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/back.pass.cpp#L55)):*
> ```cpp
> 	{
> 		constexpr pmem::obj::basic_string_view<char> sv("ABC", 2);
> 		static_assert(sv.length() == 2, "");
> ```

why not UT_ASSERT?
___
*[tests/external/libcxx/string.view/string.view.access/data.pass.cpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1Q_JCKQOb_-iF3u6:-MJm1Q_JCKQOb_-iF3u7:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/data.pass.cpp#L49)):*
> ```cpp
> 		constexpr const char *s = "ABC";
> 		constexpr pmem::obj::basic_string_view<char> sv(s, 2);
> 		static_assert(sv.length() == 2, "");
> ```

.
___
*[tests/external/libcxx/string.view/string.view.access/front.pass.cpp, line 54 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1WSk44Zj5s8cUabd:-MJm1WSl-phcw7GEMJiS:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/front.pass.cpp#L54)):*
> ```cpp
> 	{
> 		constexpr pmem::obj::basic_string_view<char> sv("ABC", 2);
> 		static_assert(sv.length() == 2, "");
> ```

.
___
*[tests/external/libcxx/string.view/string.view.access/index.pass.cpp, line 59 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1lXU3KVe_CxQSApv:-MJm1lXU3KVe_CxQSApw:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/index.pass.cpp#L59)):*
> ```cpp
> 		constexpr pmem::obj::basic_string_view<char> sv("ABC", 2);
> 		static_assert(sv.length() == 2, "");
> 		static_assert(sv[0] == 'A', "");
> ```

.


<!-- Sent from Reviewable.io -->

2020-10-19 09:33 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 166 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlwr4Q-acCOTdG0NG5:-MK-5S01-YOirGBT_SDt:b-6z4fzc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L166)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

returns pointer to c-like string? (here and above)
</blockquote></details>

No, I don't see any reason to duplicate "return" word:
https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1basic__string.html#afec7256ef676461b095a0e2f662893e0
The same here in return section:
https://en.cppreference.com/w/cpp/string/basic_string_view/front
___
*[include/libpmemobj++/string_view.hpp, line 206 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlx8mN8JQRgspdiqfg:-MK-63p3ELYShCHrsmYJ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L206)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to **the** last char
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 219 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlxTxPBxDKdbH7X5k_:-MK-65LG5e1pY1fne6Cg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L219)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 220 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlx_Z-DqfS-PPnvWfF:-MK-65h00MagofdB573H:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L220)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps also worth mention what if empty() == true
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.access/at.pass.cpp, line 37 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlzqTjC_gCTm7mTftn:-MK-BC8K-y2Cdsoq1aNW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/at.pass.cpp#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know it's ported from libcxx, but I'd remove this `if`. We throw exceptions in `at` and if we *ever* change it, this test will just fail... which is good, I guess
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.access/back.pass.cpp, line 55 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1PhoAMg-jGJAOSI4:-MK-BQQE0JfErMVZad7V:b-hgrjwu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/back.pass.cpp#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why not UT_ASSERT?
</blockquote></details>

because static_assert is evaluated in compile-time in opposite to assert which is underlying.
___
*[tests/external/libcxx/string.view/string.view.access/data.pass.cpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1Q_JCKQOb_-iF3u6:-MK-C0hV-vfe9n2uTc8Q:beotz0g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/data.pass.cpp#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

The same here, above is the constexpr
___
*[tests/external/libcxx/string.view/string.view.access/front.pass.cpp, line 54 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1WSk44Zj5s8cUabd:-MK-C5R_Axvpmav_7ATA:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/front.pass.cpp#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tests/external/libcxx/string.view/string.view.access/index.pass.cpp, line 59 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJm1lXU3KVe_CxQSApv:-MK-C6M51LEJsjL-4Yjy:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/tests/external/libcxx/string.view/string.view.access/index.pass.cpp#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2020-10-19 11:40 UTC, igchor requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938)* status: 6 of 7 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 13 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MK-e4nrCsc9dE1T6B57:-MK-e4nsE4IOHMAM5JEM:b7jjq98) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/03f95a5d094179263693cad53100f25abd424638/include/libpmemobj++/string_view.hpp#L13)):*
> ```cpp
> 
> #include <algorithm>
> #include <stdexcept>
> ```

You should leave stdexcept here - for out_of_range


<!-- Sent from Reviewable.io -->

2020-10-19 12:31 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 166 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlwr4Q-acCOTdG0NG5:-MK-okrh6WLkk1qpuqTf:b-c4kn1s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L166)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

No, I don't see any reason to duplicate "return" word:
https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1basic__string.html#afec7256ef676461b095a0e2f662893e0
The same here in return section:
https://en.cppreference.com/w/cpp/string/basic_string_view/front
</blockquote></details>

no, no. You didn't understand me ;) this are `length` and `size` - do they return a pointer to a string? I don't thinks so... ;)


<!-- Sent from Reviewable.io -->

2020-10-19 12:37 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 13 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MK-e4nrCsc9dE1T6B57:-MK-rNIiBIOr5r1H1naa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/03f95a5d094179263693cad53100f25abd424638/include/libpmemobj++/string_view.hpp#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You should leave stdexcept here - for out_of_range
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 166 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlwr4Q-acCOTdG0NG5:-MK-rOSJBG0QLPcD_05c:b3atktk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L166)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no, no. You didn't understand me ;) this are `length` and `size` - do they return a pointer to a string? I don't thinks so... ;)
</blockquote></details>

Done. Sorry xD


<!-- Sent from Reviewable.io -->

2020-10-19 12:47 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-:-MK-tc-a-af08CkPidux:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 166 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-MJlwr4Q-acCOTdG0NG5:-MK-tNsR2oFl4YM5aoFi:b-yqnuj9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/23879ec3661c09c8fb5f830fef7fbca0b6c9d4da/include/libpmemobj++/string_view.hpp#L166)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. Sorry xD
</blockquote></details>

no problem, thx


<!-- Sent from Reviewable.io -->

2020-10-19 13:47 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/938#-:-MK06J8T-OxNjNFtDpWZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-19 13:47 UTC, merged