string_view: implement capacity API and port libcxx tests
pmem/libpmemobj-cpp pull request #940
Opened 2020-10-16 13:04 UTC by KFilipek

This PR contains:
- string_view: add capacity related methods for string_view
- string_view: add string_view capacity API libcxx tests
- string_view: port LIBCXX capacity test to use pmem::obj::string_view

PR depends on #938.
Please merge it after #938.

2020-10-19 08:12 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940#-:-MJzujB77RY9_OSXLB50:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-19 14:44 UTC, KFilipek reviewed
> Reviewed 2 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-19 18:19 UTC, karczex reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940#-:-MK14Z9D20EX4N8TuiGs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-20 09:46 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 174 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940#-MK4OlQX4offdaxOOLvV:-MK4OlQX4offdaxOOLvW:borsaf0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f602c227a5238e4b059abe82518543e2e8f78341/include/libpmemobj++/string_view.hpp#L174)):*
> ```cpp
> template <typename CharT, typename Traits>
> constexpr inline typename basic_string_view<CharT, Traits>::size_type
> basic_string_view<CharT, Traits>::length() const noexcept
> ```

why removed?


<!-- Sent from Reviewable.io -->

2020-10-20 09:50 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 174 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940#-MK4OlQX4offdaxOOLvV:-MK4PcGqCsx1MQnQMOrz:b-cyk31c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f602c227a5238e4b059abe82518543e2e8f78341/include/libpmemobj++/string_view.hpp#L174)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

Also, it would be good to add test for that.


<!-- Sent from Reviewable.io -->

2020-10-20 10:33 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 174 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940#-MK4OlQX4offdaxOOLvV:-MK4Z8go9OPfywVt4NZA:bzif5ko) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f602c227a5238e4b059abe82518543e2e8f78341/include/libpmemobj++/string_view.hpp#L174)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, it would be good to add test for that.
</blockquote></details>

Why removed? After rebase length was moved below max_size.
Additionally this test also test length function.


<!-- Sent from Reviewable.io -->

2020-10-20 10:34 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/940)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-20 10:35 UTC, merged