readme: update build instructions for Windows and VC++
pmem/libpmemobj-cpp pull request #985
Opened 2020-11-25 10:07 UTC by KFilipek

Update instructions for Windows build using VC++2015
and disability to build with radix_tree.

2020-11-26 13:48 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[README.md, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MMyscIE92HYloUT4rlY:-MMzYSJ93bMh2g6rCS-C:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b50854e115f597bc78ef6aa9abb83985181f0faf/README.md#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. drop "installing" - we don't have an option for that anymore
2. make the cmake option just an extra explanation, in parenthesis

so in general I'd re-write it like:
`...2017 is needed. Testing of radix_tree can be disabled via CMake option (use -DTEST_RADIX_TREE=OFF).`
</blockquote></details>

Done.
___
*[README.md, line 77 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MMyuBY55lYs_6R7xCcM:-MN3nleADnTpmMTZCZXj:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b50854e115f597bc78ef6aa9abb83985181f0faf/README.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you also add a sub-section with installing our lib using completely vcpkg (I mean using libpmemobj-cpp port available in vcpkg; not compiling from sources)
</blockquote></details>

Done.
___
*[README.md, line 91 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MMyu1EX1Azl2Vjee09x:-MN3nrmr8d4NgZJF_RHm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b50854e115f597bc78ef6aa9abb83985181f0faf/README.md#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you also put a command for other VS, or just link to our GHA file; or both - a short list of commands (live for VS2015) and a link to comprehensive solution like in our gha.yml. To show the differences between various VS's (if any significant)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 09:22 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 1 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vHYv6N2yFzk9W7Z6:-MN7vHYv6N2yFzk9W7Z7:b-bh1gaq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L1)):*
> ```Markdown
> # libpmemobj-cpp
> ```

you don't have to add this `#` - it's taken care by the `===` below ;)

BTW, I recommend to see some md files preview when submitting changes (VSC supports that, but also you can check it here: https://github.com/KFilipek/libpmemobj-cpp/tree/fix-readme_windows_build#libpmemobj-cpp )
___
*[README.md, line 17 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vhx39iAzhCXv-2OQ:-MN7vhx39iAzhCXv-2OR:bg7jntz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L17)):*
> ```Markdown
> Up-to-date support/maintenance status of branches/releases is available on [pmem.io](https://pmem.io/libpmemobj-cpp).
> 
> # Table of contents
> ```

to be honest I'd make this a secondary header (use `##` instead of just one) - it seems a little to big;
as a result all other headers should be also turned down ("one level down" :wink: )
___
*[README.md, line 18 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7w5PG03nMadxVigvL:-MN7w5PG03nMadxVigvM:bog9e1p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L18)):*
> ```Markdown
> 
> # Table of contents
> - [Overview](#libpmemobj-cpp)
> ```

we don't have to link here to above section ;)
___
*[README.md, line 19 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7wHDk3t59--LkGLLT:-MN7wHDk3t59--LkGLLU:b-unbp6t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L19)):*
> ```Markdown
> # Table of contents
> - [Overview](#libpmemobj-cpp)
> - [Build instructions](#build-instructions)
> ```

since we don't have much more in this readme then just building information, I believe we can skip/remove this header
___
*[README.md, line 98 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7yFTqB7Ao984x9DvF:-MN7yFTqB7Ao984x9DvG:b-ozkof5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L98)):*
> ```Markdown
> 
> ## Windows build
> ### Libpmemobj++ installation via vcpkg
> ```

please add some short description, like - "if your looking for a stable release ..."
___
*[README.md, line 109 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7y3YaAGyUYCRo7rgd:-MN7y3Yb9dhWSC1k826b:b-btp7vi) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L109)):*
> ```Markdown
> ```
> 
> ### Compilation with Visual Studio 2015
> ```

this and the section right above should be perhaps a one section, called "standard compilation"...?
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7ww2p7oidI_FUwx5Q:-MN7ww2p7oidI_FUwx5R:b-k73efw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
> ```Markdown
> ### Compilation with Visual Studio 2017 or above
> ```sh
> cmake . -Bbuild -G "Visual Studio 15 2017" -A "x64" -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
> ```

please break the line, like we have in above cmake command
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7x0b94kF3gYEMc8uG:-MN7x0b94kF3gYEMc8uH:bkfb9uh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
> ```Markdown
> ### Compilation with Visual Studio 2017 or above
> ```sh
> cmake . -Bbuild -G "Visual Studio 15 2017" -A "x64" -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
> ```

I'm not sure if `-A "x64"` is required; but I'm also not sure what happend when we try to compile it on x86 arch...
Do we have any information that we require 64bit OS? I can see some info about it in PMDK's readme...
___
*[README.md, line 124 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7zIdm84BB7T0nYyH9:-MN7zIdm84BB7T0nYyHA:b-275iiu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L124)):*
> ```Markdown
> ```
> 
> ## Extra CMake compilation flags
> ```

I'm not sure if we need this section - it may become outdated very quickly - if you feel like it's useful to have this info here, perhaps a link to CMake top section, where we keep these options, or an information about using `ccmake` command (which helps a little with all the options)


<!-- Sent from Reviewable.io -->

2020-11-27 10:56 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 16 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN8KxwnDG73_x_pNc1k:-MN8KxwnDG73_x_pNc1l:b2ohkh4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L16)):*
> ```Markdown
> Latest releases can be found on the ["releases" tab](https://github.com/pmem/libpmemobj-cpp/releases).
> Up-to-date support/maintenance status of branches/releases is available on [pmem.io](https://pmem.io/libpmemobj-cpp).
> ```

perhaps also add 'contact us' information as a simple sentence here or as another subsection on the bottom


<!-- Sent from Reviewable.io -->

2020-11-27 14:26 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 1 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vHYv6N2yFzk9W7Z6:-MN907hC3ObXnuCN0z7M:b3h07ks) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't have to add this `#` - it's taken care by the `===` below ;)

BTW, I recommend to see some md files preview when submitting changes (VSC supports that, but also you can check it here: https://github.com/KFilipek/libpmemobj-cpp/tree/fix-readme_windows_build#libpmemobj-cpp )
</blockquote></details>

Done.
Right, but it worked for me under VSCode
___
*[README.md, line 16 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN8KxwnDG73_x_pNc1k:-MN90DjQ8lESvu44ZDKb:b-kwgc8c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps also add 'contact us' information as a simple sentence here or as another subsection on the bottom
</blockquote></details>

Done. I've added section at the end
___
*[README.md, line 17 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vhx39iAzhCXv-2OQ:-MN911Cx1V81-in8BZAC:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to be honest I'd make this a secondary header (use `##` instead of just one) - it seems a little to big;
as a result all other headers should be also turned down ("one level down" :wink: )
</blockquote></details>

Done.
___
*[README.md, line 18 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7w5PG03nMadxVigvL:-MN91Hm_AG65gq7rqZhG:b-cw52vh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we don't have to link here to above section ;)
</blockquote></details>

Done.
As you wish
___
*[README.md, line 19 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7wHDk3t59--LkGLLT:-MN91NgGDmHVsUFVm_5Q:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since we don't have much more in this readme then just building information, I believe we can skip/remove this header
</blockquote></details>

Done.
___
*[README.md, line 98 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7yFTqB7Ao984x9DvF:-MN921HY7Y2FiBxSO6Na:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L98)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add some short description, like - "if your looking for a stable release ..."
</blockquote></details>

Done.
___
*[README.md, line 109 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7y3YaAGyUYCRo7rgd:-MN925MGEd_-yK3Baid2:biemtgd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L109)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this and the section right above should be perhaps a one section, called "standard compilation"...?
</blockquote></details>

I've splitted sections between Windows and Linux
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7ww2p7oidI_FUwx5Q:-MN92Phn1tcLtgGtlsXw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please break the line, like we have in above cmake command
</blockquote></details>

Done.
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7x0b94kF3gYEMc8uG:-MN92Rt-7hHtDAlccGUq:b-j8vznt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if `-A "x64"` is required; but I'm also not sure what happend when we try to compile it on x86 arch...
Do we have any information that we require 64bit OS? I can see some info about it in PMDK's readme...
</blockquote></details>

I suggested this option due to GHA configuration, there we have generator and architecture specified. Also under cmake .. --help we have generators listed at the end.


<!-- Sent from Reviewable.io -->

2020-11-27 14:26 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 124 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7zIdm84BB7T0nYyH9:-MN95MtE3SF6bk8Qo4BP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L124)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if we need this section - it may become outdated very quickly - if you feel like it's useful to have this info here, perhaps a link to CMake top section, where we keep these options, or an information about using `ccmake` command (which helps a little with all the options)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 15:14 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 17 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN9EXme8wEK1x5lWJHA:-MN9EXme8wEK1x5lWJHB:bht277w) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f8a4e70196827559e3db9dddbe3f4d766c4f44ec/README.md#L17)):*
> ```Markdown
> 
> ## Table of contents
> 1. [Pre-built packages for Windows](#pre-built-packages-for-windows)
> ```

nit: This may be changed to "Pre-built packages", and  you may also mention  linux disto packages. 


<!-- Sent from Reviewable.io -->

2020-11-30 11:51 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 11 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-11-30 15:51 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 18 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOqT_ECCF2Z1Pz2QX9:-MNOqT_ECCF2Z1Pz2QXA:bklg9e4) (no related file):*
commit message seems a bit outdated now 

---
___
*[README.md, line 1 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vHYv6N2yFzk9W7Z6:-MNOgIn27o1uVluFgah9:b-ft9qbx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
Right, but it worked for me under VSCode
</blockquote></details>

as I commented on pmemkv - it seems redundant to use `**`
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7x0b94kF3gYEMc8uG:-MNOpdrf18I0kTp0EHmh:b-b0uiuj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I suggested this option due to GHA configuration, there we have generator and architecture specified. Also under cmake .. --help we have generators listed at the end.
</blockquote></details>

then perhaps it should be added also in VS2015 compilation...?
___
*[README.md, line 34 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhY1nAPN-nn9dZxB4:-MNOhY1o9ItCEoOTPBFn:bt57bnv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L34)):*
> ```Markdown
> 6. [Contact us](#contact-us)
> 
> ## Pre-built packages
> ```

perhaps add a sentence with info, that this is the way to install stable releases
___
*[README.md, line 44 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhGmE6HE5ptPAciuN:-MNOhGmE6HE5ptPAciuO:b4dxevf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L44)):*
> ```Markdown
> For installation on Debian-related distros please execute following commands:
> ```sh
> $ apt install libpmemobj-cpp-dev
> ```

I believe `#` instead of `$` - you have to do this as root/sudoer
___
*[README.md, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhQ-w-0XOJNH4bcpD:-MNOhQ-w-0XOJNH4bcpE:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L50)):*
> ```Markdown
> To install **libpmemobj-cpp** on Fedora or RedHat execute:
> ```sh
> $ dnf install libpmemobj++-devel
> ```

.
___
*[README.md, line 54 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOi3Mo-EgyamAQ1JlP:-MNOi3Mo-EgyamAQ1JlQ:bxb3rbr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L54)):*
> ```Markdown
> 
> ## Dependencies
> You will need to install the following required packages on the build system:
> ```

what do you mean by "required packages on the build system" ?
___
*[README.md, line 58 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOkXubBM4xgla_p9tK:-MNOkXucCIAaHF_2scv7:b4z8hf6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L58)):*
> ```Markdown
> - **libpmemobj-dev(el)** >= 1.8 (https://pmem.io/pmdk/)
> - compiler with C++11 support
> 	- **gcc** >= 4.8.1<sup>1</sup>
> ```

this `1` is really badly visible, it "merges" with the `4.8.1` - perhaps add a space before and make it like `[1]`
___
*[README.md, line 60 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmKaBE8B3vIIJGSSU:-MNOmKaBE8B3vIIJGSSV:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L60)):*
> ```Markdown
> 	- **gcc** >= 4.8.1<sup>1</sup>
> 	- **clang** >= 3.3
> 	- **msbuild** >= 14<sup>2</sup>
> ```

.
___
*[README.md, line 68 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmLeA5l-U91dnyDKt:-MNOmLeB9by1wpBosT_r:blr5knl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L68)):*
> ```Markdown
> 	- [**vcpkg**](https://github.com/microsoft/vcpkg#quick-start-windows)
> 
>  ><sup>1</sup>C++11 is supported in GCC since version 4.8.1, but it does not support expanding variadic template variables in lambda expressions, which is required to build persistent containers and is possible with GCC >= 4.9.0. If you want to build libpmemobj-cpp without testing containers, use flag TEST_XXX=OFF (separate flag for each container).
> ```

add a space before `C++11` please
___
*[README.md, line 70 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmaAADgbyvnoXfZrf:-MNOmaAADgbyvnoXfZrg:b-7ch8zs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L70)):*
> ```Markdown
>  ><sup>1</sup>C++11 is supported in GCC since version 4.8.1, but it does not support expanding variadic template variables in lambda expressions, which is required to build persistent containers and is possible with GCC >= 4.9.0. If you want to build libpmemobj-cpp without testing containers, use flag TEST_XXX=OFF (separate flag for each container).
> 
>  ><sup>2</sup>**radix_tree**: on Windows, Visual Studio in version at least 2017 is needed (MSBuild >=15). Testing radix_tree can be disabled via CMake options (use -DTEST_RADIX_TREE=OFF).
> ```

if you want to use it like this, I believe you should re-write this sentence a bit - e.g. `radix_tree is supported on Windows in msbuild >= 15 (VS in version at least 201). Testing...`
___
*[README.md, line 70 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOnDrgByegBczKk_6N:-MNOnDrgByegBczKk_6O:b-714re8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L70)):*
> ```Markdown
>  ><sup>1</sup>C++11 is supported in GCC since version 4.8.1, but it does not support expanding variadic template variables in lambda expressions, which is required to build persistent containers and is possible with GCC >= 4.9.0. If you want to build libpmemobj-cpp without testing containers, use flag TEST_XXX=OFF (separate flag for each container).
> 
>  ><sup>2</sup>**radix_tree**: on Windows, Visual Studio in version at least 2017 is needed (MSBuild >=15). Testing radix_tree can be disabled via CMake options (use -DTEST_RADIX_TREE=OFF).
> ```

also there's a misspell `options` -> `option`
___
*[README.md, line 72 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOoRYgANbfRa0S4lNS:-MNOoRYgANbfRa0S4lNT:bbixcco) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L72)):*
> ```Markdown
>  ><sup>2</sup>**radix_tree**: on Windows, Visual Studio in version at least 2017 is needed (MSBuild >=15). Testing radix_tree can be disabled via CMake options (use -DTEST_RADIX_TREE=OFF).
> 
> ### Linux build
> ```

make it `##`
___
*[README.md, line 77 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOonkx6Ji0Uks2jvJr:-MNOonkx6Ji0Uks2jvJs:b-k8rr7n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L77)):*
> ```Markdown
> $ mkdir build
> $ cd build
> $ cmake ..
> ```

use in this cmake command `-DCMAKE_INSTALL_PREFIX=...`
___
*[README.md, line 85 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOoWI69hhRBWCkq6q3:-MNOoWI69hhRBWCkq6q4:b44ykim) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L85)):*
> ```Markdown
> ```sh
> $ mkdir build
> $ cd build
> ```

I'm not sure if you have to re-write every time `mkdir build && cd build` - it seems pretty obvious
___
*[README.md, line 145 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOpwI15KESIS9_L_8f:-MNOpwI15KESIS [...]

2020-12-01 13:39 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 18 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOqT_ECCF2Z1Pz2QX9:-MNTWlAM6hyBRkJZbXSk:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

commit message seems a bit outdated now 
</blockquote></details>

Done.

---
___
*[README.md, line 1 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vHYv6N2yFzk9W7Z6:-MNTOUJf8y4ilIDxFsWa:b4k9rjq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as I commented on pmemkv - it seems redundant to use `**`
</blockquote></details>

https://github.com/pmem/pmdk/blob/master/README.md
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7x0b94kF3gYEMc8uG:-MNTVYa-4aPYAzOrHm76:b90u962) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

then perhaps it should be added also in VS2015 compilation...?
</blockquote></details>

cmake generator list has full name "Visual Studio 14 2015 Win64"
___
*[README.md, line 34 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhY1nAPN-nn9dZxB4:-MNTEArc5EcyZWRM98N_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add a sentence with info, that this is the way to install stable releases
</blockquote></details>

Done.
___
*[README.md, line 44 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhGmE6HE5ptPAciuN:-MNTOSfQC8zeCPSmHiAn:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe `#` instead of `$` - you have to do this as root/sudoer
</blockquote></details>

Done.
___
*[README.md, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhQ-w-0XOJNH4bcpD:-MNTOTOt7pfWsCx7xxUy:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[README.md, line 54 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOi3Mo-EgyamAQ1JlP:-MNTPje07R38X5v0HdJW:b93l03t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what do you mean by "required packages on the build system" ?
</blockquote></details>

Done. I change this sentence.
___
*[README.md, line 58 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOkXubBM4xgla_p9tK:-MNTQUd5CWoAVk_RSbyp:b4ct65k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this `1` is really badly visible, it "merges" with the `4.8.1` - perhaps add a space before and make it like `[1]`
</blockquote></details>

It's not a bibliography, it works for PMDK
___
*[README.md, line 60 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmKaBE8B3vIIJGSSU:-MNTRUY18tkAeC6H6yrX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[README.md, line 68 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmLeA5l-U91dnyDKt:-MNTSMpo9Ro0frBZiGZM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add a space before `C++11` please
</blockquote></details>

Done.
___
*[README.md, line 70 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOmaAADgbyvnoXfZrf:-MNTScUp78BF_k-6eGyQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to use it like this, I believe you should re-write this sentence a bit - e.g. `radix_tree is supported on Windows in msbuild >= 15 (VS in version at least 201). Testing...`
</blockquote></details>

Done.
___
*[README.md, line 70 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOnDrgByegBczKk_6N:-MNTSgh19TxgqJpjYDHX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

also there's a misspell `options` -> `option`
</blockquote></details>

Done.
___
*[README.md, line 72 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOoRYgANbfRa0S4lNS:-MNTToCe572pANYasOA-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it `##`
</blockquote></details>

Done.
___
*[README.md, line 77 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOonkx6Ji0Uks2jvJr:-MNTUr-G4trK9BSzPtxG:b-b3xvwf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use in this cmake command `-DCMAKE_INSTALL_PREFIX=...`
</blockquote></details>

Why? It is not "must have" for basic compilation.
___
*[README.md, line 85 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOoWI69hhRBWCkq6q3:-MNTV0_fEsVngUi4zm82:bjzurbg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if you have to re-write every time `mkdir build && cd build` - it seems pretty obvious
</blockquote></details>

It's better than previous "...".
We don't prefer in-place compilation
___
*[README.md, line 145 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOpwI15KESIS9_L_8f:-MNTVitIC9R_HAg3oj_Y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[README.md, line 148 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOq3yr0AMMxNnm_QLa:-MNTVjeSDTTpZjUDc1AH:b-93f5wb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it actually lists more then just our CMake *options*, but I guess `ccmake` does the same...
</blockquote></details>

I mentioned below about it, but you d [...]

2020-12-04 09:28 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 1 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7vHYv6N2yFzk9W7Z6:-MNh-sjQ7bzYAlRY8e_R:b-uf70lo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://github.com/pmem/pmdk/blob/master/README.md
</blockquote></details>

who says they have it correctly ;) but anyway, it just doesn't change anything ;)
___
*[README.md, line 119 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MN7x0b94kF3gYEMc8uG:-MNh2zfZ1h_adasLokFL:bwuvo0n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bc3afbaaf707e67774888a30535ab68b95f0f5ee/README.md#L119)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

cmake generator list has full name "Visual Studio 14 2015 Win64"
</blockquote></details>

Och, ok, that MS works in curious ways sometimes... :D
___
*[README.md, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhQ-w-0XOJNH4bcpD:-MNh04Wk2KCrNgTQG75q:b7wkqys) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done, still $
___
*[README.md, line 58 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOkXubBM4xgla_p9tK:-MNh0NcR9aEMFCHT24T1:b-p1ajdn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L58)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's not a bibliography, it works for PMDK
</blockquote></details>

but they don't use it next to another number, I believe adding a space would be sufficient
___
*[README.md, line 77 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOonkx6Ji0Uks2jvJr:-MNh1HMI2YHJtUPO-gPV:bthlj6c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L77)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why? It is not "must have" for basic compilation.
</blockquote></details>

my thinking is: this is an instruction for people, who may not be familiar with cmake, and they may not know this param; anyway, we can make it like:
`cmake .. [-DCMAKE_INSTALL_PREFIX=...]`
or e.g.
`cmake ..              \t \t  # or to specify install path prefix: cmake .. -DCMAKE_INSTALL_PREFIX=...`
___
*[README.md, line 148 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOq3yr0AMMxNnm_QLa:-MNh2FDHD2bHPR8EaEBV:bql5hn8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L148)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I mentioned below about it, but you don't need to install external tools in container or reading files, cmake -LH does the job here
</blockquote></details>

this comment is just a "thinking out loud" that `ccmake` and `cmake -LH` shows much more then just *options*... I'm just curious if we can limit it only to the options...
___
*[README.md, line 153 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOgeIo5dILlgKiRE4m:-MNh2WOg52x3UV4AA_Fd:by8s8b6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L153)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I've added the break, but text of footer was agreed with Szymon
</blockquote></details>

I can see it as a single, long line.
Also, I personally think we can add info about google group, perhaps some people can't/don't want to use Slack...
___
*[README.md, line 19 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1Vhd2a065V32wkDW:-MNh1Vhd2a065V32wkDX:b-707u0q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L19)):*
> ```Markdown
> 1. [Pre-built packages](#pre-built-packages)
> 	- [Windows](#windows)
> 	- [Ubuntu/Debian](#ubuntu/debian)
> ```

I don't believe this link to section will work, please verify and fix all (if needed)
___
*[README.md, line 46 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1plS3C8jFJ50xchy:-MNh1plS3C8jFJ50xchz:bnx5mag) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L46)):*
> ```Markdown
> ### Ubuntu/Debian
> For installation on Debian-related distros please execute following commands:
> ```
> ```

pls add `sh` here
___
*[README.md, line 52 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1xSj2P4Vkt2rCS-A:-MNh1xSj2P4Vkt2rCS-B:b32wwq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L52)):*
> ```Markdown
> ### Fedora/RHEL
> To install **libpmemobj-cpp** on Fedora or RedHat execute:
> ```
> ```

sh
___
*[README.md, line 66 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh0gxj0BzjV4DAd-vO:-MNh0gxj0BzjV4DAd-vP:bbxdv70) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L66)):*
> ```Markdown
> 	- **msbuild** >= 14<sup>2</sup>
> - for testing and development:
> 	- **valgrind-devel** (at best with [pmemcheck support](https://github.com/pmem/valgrind))
> ```

did you check perhaps if these deps. are sufficient? (perhaps we're missing some dependencies like in pmemkv a.k.a. your recent PR on pmemkv)
___
*[README.md, line 78 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1zVA-3xz2UKLcKiP:-MNh1zVA-3xz2UKLcKiQ:b32wwq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L78)):*
> ```Markdown
> ## Linux build
> ### Standard compilation
> ```
> ```

sh
___
*[README.md, line 87 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh2-0sA9OAE8BHgUGe:-MNh2-0sA9OAE8BHgUGf:b32wwq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L87)):*
> ```Markdown
> 
> ### Developer compilation
> ```
> ```

sh
___
*[README.md, line 96 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh2-f94B6obv-DusFj:-MNh2-f94B6obv-DusFk:b32wwq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L96)):*
> ```Markdown
> 
> ### Distribution package build
> ```
> ```

sh
___
*[README.md, line 130 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh22FiDwMrPw1A-p4Z:-MNh22FiDwMrPw1A-p4_:b5gups2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L130)):*
> ```Markdown
> 
> ### Compilation with Visual Studio 2015
> ```sh
> ```

`ps` I guess
___
*[README.md, line 138 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh24G9DpCB_KTTa5GS:-MNh24G9DpCB_KTTa5GT:b32wug) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L138)):*
> ```Markdown
> ```
> ### Compilation with Visual Studio 2017 or above
> ```sh
> ```

ps
___
*[README.md, line 147 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh3unj7mTf0SKCA3KG:-MNh3unk65KKYarKdtZo:b-41iez7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L147)):*
> ```Markdown
> ## Extra CMake compilation flags
> 
> To list all CMake flags use the following:
> ```

I'm just thinking, maybe add a short sentence, what are these flags/options for
___
*[README.md, line 148 at r8](https://reviewab [...]

2020-12-16 10:55 UTC, igchor reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 18 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 57 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MOfAbkI7KHvp9GrzNY_:-MOfAbkI7KHvp9GrzNYa:bk3uyjk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L57)):*
> ```Markdown
> 
> ## Dependencies
> You will need the following packages in compilation environment:
> ```

compilation environment? Maybe "... packages for compilation"? 


<!-- Sent from Reviewable.io -->

2020-12-16 11:51 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[README.md, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOhQ-w-0XOJNH4bcpD:-MOfMmcs5QZdnbKVgdFQ:b-81la7d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done, still $
</blockquote></details>

Right
___
*[README.md, line 58 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOkXubBM4xgla_p9tK:-MOfN2zWAN3wP-iQGbfK:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but they don't use it next to another number, I believe adding a space would be sufficient
</blockquote></details>

Done.
___
*[README.md, line 153 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOgeIo5dILlgKiRE4m:-MOfNg6r4Xb_Erq-Nf9Z:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L153)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I can see it as a single, long line.
Also, I personally think we can add info about google group, perhaps some people can't/don't want to use Slack...
</blockquote></details>

Done.
___
*[README.md, line 19 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1Vhd2a065V32wkDW:-MOfMJJi6yt84_awoCmy:b-8rxc2o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't believe this link to section will work, please verify and fix all (if needed)
</blockquote></details>

I've also changed Fedora's link
Done.
___
*[README.md, line 46 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1plS3C8jFJ50xchy:-MOfMSHrArYfQsirYyNz:b-ms9wye) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `sh` here
</blockquote></details>

Then whole command will be treat as comment xD
___
*[README.md, line 52 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1xSj2P4Vkt2rCS-A:-MOfMWKcBbWJBumGFj5W:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sh
</blockquote></details>

Done.
___
*[README.md, line 130 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh22FiDwMrPw1A-p4Z:-MOfNGQd8f1jnAMTW0Bd:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L130)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`ps` I guess
</blockquote></details>

Done.
___
*[README.md, line 138 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh24G9DpCB_KTTa5GS:-MOfNGnu-nSBQM198QSJ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L138)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ps
</blockquote></details>

Done.
___
*[README.md, line 148 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh26TN6VLuEe-Dxo3y:-MOfNKeW-d8YUIliilXa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L148)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sh
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-16 12:02 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[README.md, line 58 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOkXubBM4xgla_p9tK:-MOfQ6_I-a0HsgZFLQlm:b-k73z76) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L58)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks
___
*[README.md, line 153 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOgeIo5dILlgKiRE4m:-MOfQQm2CWjHmUcekuCI:b-7po4i6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L153)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no google group
___
*[README.md, line 46 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1plS3C8jFJ50xchy:-MOfPwPK0w9wqULbVYYU:b-mmpe4i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L46)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Then whole command will be treat as comment xD
</blockquote></details>

haha :D true, then sorry, maybe not
___
*[README.md, line 52 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1xSj2P4Vkt2rCS-A:-MOfQ19_6OnM6QI66pLi:b-xlqtzl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L52)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, maybe not
___
*[README.md, line 78 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1zVA-3xz2UKLcKiP:-MOfQBVa2W9oeaJJACJz:b-xlqtzl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sh
</blockquote></details>

sorry, maybe not


<!-- Sent from Reviewable.io -->

2020-12-16 12:15 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[README.md, line 77 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOonkx6Ji0Uks2jvJr:-MOfTZEiCTCjkK-inF9a:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

my thinking is: this is an instruction for people, who may not be familiar with cmake, and they may not know this param; anyway, we can make it like:
`cmake .. [-DCMAKE_INSTALL_PREFIX=...]`
or e.g.
`cmake ..              \t \t  # or to specify install path prefix: cmake .. -DCMAKE_INSTALL_PREFIX=...`
</blockquote></details>

Done.
___
*[README.md, line 153 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOgeIo5dILlgKiRE4m:-MOfSvYqAJCGEvRXMkfR:btpodx6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L153)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no google group
</blockquote></details>

Ups, I've added.
___
*[README.md, line 46 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1plS3C8jFJ50xchy:-MOfRiPH7sijOdE4_3Hw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

haha :D true, then sorry, maybe not
</blockquote></details>

Done.
___
*[README.md, line 66 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh0gxj0BzjV4DAd-vO:-MOfS-8q51x2_FzEfAJY:b-2yeldw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

did you check perhaps if these deps. are sufficient? (perhaps we're missing some dependencies like in pmemkv a.k.a. your recent PR on pmemkv)
</blockquote></details>

I didn't try building with these options, but it should be considered 
___
*[README.md, line 78 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh1zVA-3xz2UKLcKiP:-MOfSHi07ja4JuWT_wna:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sorry, maybe not
</blockquote></details>

Done.
___
*[README.md, line 87 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh2-0sA9OAE8BHgUGe:-MOfSJ6g6OwmKq1u_bCs:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L87)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sh
</blockquote></details>

Done.
___
*[README.md, line 96 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh2-f94B6obv-DusFj:-MOfSJk_C_dOloACoE6L:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

sh
</blockquote></details>

Done.
___
*[README.md, line 147 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh3unj7mTf0SKCA3KG:-MOfSRMf4B9j43pGgq8o:bv0gaw5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L147)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm just thinking, maybe add a short sentence, what are these flags/options for
</blockquote></details>

Previously I've added nice-looking table with all options and argument against this table was difficulty of maintaining. I'm not going to do the same job twice...


<!-- Sent from Reviewable.io -->

2020-12-16 12:17 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 9 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[README.md, line 66 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh0gxj0BzjV4DAd-vO:-MOfToa75Soaj_zhXp7H:bqoqgp8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L66)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I didn't try building with these options, but it should be considered 
</blockquote></details>

Please open issue and I will check this in separate PR


<!-- Sent from Reviewable.io -->

2020-12-16 13:42 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[README.md, line 153 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNOgeIo5dILlgKiRE4m:-MOflfbz8y8TedUHRTXp:b-k73z76) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd9c8c8ff83a79667bcc69435b77bc1224007fb5/README.md#L153)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Ups, I've added.
</blockquote></details>

thanks
___
*[README.md, line 147 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh3unj7mTf0SKCA3KG:-MOflK7EAooMfT6nK0er:bwqdq53) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L147)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Previously I've added nice-looking table with all options and argument against this table was difficulty of maintaining. I'm not going to do the same job twice...
</blockquote></details>

hah, I never said to describe *all the options* - just a general, short comment what are these extra CMake flags. You know it, I know it, but we're not sure if pmemkv user knows it :wink:
___
*[README.md, line 41 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MOflrm74KbcULRvKgns:-MOflrm74KbcULRvKgnt:b5gups2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88358850faaba87c16b47569e325098969be900c/README.md#L41)):*
> ```Markdown
> The recommended and the easiest way to install **libpmemobj-cpp** on Windows is to use Microsoft's vcpkg. Vcpkg is an open source tool and ecosystem created for library management.
> For more information about vcpkg please see [vcpkg repository](https://github.com/microsoft/vcpkg#quick-start-windows).
> ```sh
> ```

`ps` I guess


<!-- Sent from Reviewable.io -->

2020-12-17 08:39 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[README.md, line 32 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MOjpj4K3enNXNbVGGFR:-MOjpj4K3enNXNbVGGFS:b-1i9bsp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88358850faaba87c16b47569e325098969be900c/README.md#L32)):*
> ```Markdown
> 	- [Compilation with Visual Studio 2017 or above](#compilation-with-visual-studio-2017-or-above)
> 5. [Extra CMake compilation flags](#extra-cmake-compilation-flags)
> 6. [Compatibility note](#compatibility-note)
> ```

I added this section on top on purpose - I wanted it to be well visible. I think it's much more likely to be missed if it's at the bottom (and it's rather important information). Do you think we could move it back up?


<!-- Sent from Reviewable.io -->

2020-12-17 11:45 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[README.md, line 147 at r8](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MNh3unj7mTf0SKCA3KG:-MOkWCDw2LlXGz0osCF7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fed1e784997803eb7c17e62b8d18e95b792b359e/README.md#L147)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hah, I never said to describe *all the options* - just a general, short comment what are these extra CMake flags. You know it, I know it, but we're not sure if pmemkv user knows it :wink:
</blockquote></details>

Done.
___
*[README.md, line 32 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MOjpj4K3enNXNbVGGFR:-MOkPycn9OI-Zs9V3lGt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88358850faaba87c16b47569e325098969be900c/README.md#L32)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I added this section on top on purpose - I wanted it to be well visible. I think it's much more likely to be missed if it's at the bottom (and it's rather important information). Do you think we could move it back up?
</blockquote></details>

Done.
___
*[README.md, line 41 at r10](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-MOflrm74KbcULRvKgns:-MOkPzAr6PE_qf4AYxJ5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88358850faaba87c16b47569e325098969be900c/README.md#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`ps` I guess
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-17 12:00 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2020-12-17 12:03 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985#-:-MOk_Fxc8sukkWt9WfwC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2020-12-17 14:31 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2020-12-17 14:32 UTC, merged